networks:
  tyk-network:

services:
  midsommar:
    networks:
      - tyk-network
    image: tykio/tyk-ai-studio-ent:v2.0.0
    volumes:
      - ../confs/midsommar-ent.env:/app/.env
      - ./keys/plugins/plugin-live.pub:/app/keys/plugins/plugin-live.pub:ro
      - ./data/cache/plugins:/app/data/cache/plugins
      - ./data/midsommar/:/app/data/db
    env_file:
      - ../required.env
      - ../confs/midsommar-ent.env
    ports:
      - 8585:8080
      - 9595:9090
    restart: always
  mgw:
    networks:
      - tyk-network
    image: tykio/tyk-microgateway-ent:v2.0.0
    volumes:
      - ../confs/mgw-ent.env:/app/.env
      - ../confs/mgw-analytics.yaml:/app/mgw-analytics.yaml
      - ./data/mgw:/app/data
      - ./data/cache/plugins:/data/cache/plugins
    env_file:
    - ../required.env
    - ../confs/mgw-ent.env
    ports:
      - 9091:9091
    restart: always
    depends_on:
      midsommar:
        condition: service_started
