networks:
  tyk-network:

services:
  midsommar:
    networks:
      - tyk-network
    image: tykio/tyk-ai-studio-ent:v2.1.0
    volumes:
      - ../confs/midsommar-ent.env:/opt/tyk-ai-studio/.env
      - ./keys/plugins/plugin-live.pub:/opt/tyk-ai-studio/keys/plugins/plugin-live.pub:ro
      - ./data/midsommar:/opt/tyk-ai-studio/data
      - ./data/cache/plugins:/opt/tyk-ai-studio/data/cache/plugins
    env_file:
      - ../required.env
      - ../confs/midsommar-ent.env
    ports:
      - 8585:8080
      - 9595:9090
    restart: always
  mgw:
    networks:
      - tyk-network
    image: tykio/tyk-microgateway-ent:v2.1.0
    volumes:
      - ../confs/mgw-ent.env:/opt/tyk-microgateway/.env
      - ../confs/mgw-analytics.yaml:/opt/tyk-microgateway/mgw-analytics.yaml
      - ./data/mgw:/app/data
      - ./data/cache/plugins:/data/cache/plugins
    env_file:
    - ../required.env
    - ../confs/mgw-ent.env
    ports:
      - 9091:9091
    restart: always
    depends_on:
      midsommar:
        condition: service_started
