/**
 * Maps the model-facing generative UI tree onto the wire format the
 * @assistant-ui/react-generative-ui renderer expects.
 *
 * The library keys nodes with `$type`, `$key` and `$action`, but Anthropic
 * rejects tool schema property names that start with `$`, so the embedded
 * schema (models/generative_ui_present_schema.json, generated by
 * scripts/gen-present-schema.mjs) uses `component`, `key` and `action`
 * instead. A node is any object carrying a string `component`; `action` is
 * also renamed on a Card's `confirm` / `cancel` footer buttons, which are
 * plain objects rather than nodes.
 */
const FOOTER_KEYS = new Set(['confirm', 'cancel']);

const isObject = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);

const convert = (value, parentKey) => {
  if (Array.isArray(value)) return value.map((v) => convert(v, parentKey));
  if (!isObject(value)) return value;

  const isNode = typeof value.component === 'string';
  const isFooter = FOOTER_KEYS.has(parentKey);
  const out = {};
  Object.entries(value).forEach(([k, v]) => {
    if (isNode && k === 'component') out.$type = v;
    else if (isNode && k === 'key') out.$key = v;
    else if ((isNode || isFooter) && k === 'action') out.$action = v;
    else if (isNode && k === 'children') out.children = convert(v, k);
    else if (isNode && FOOTER_KEYS.has(k)) out[k] = convert(v, k);
    else out[k] = isNode ? convert(v, k) : v;
  });
  return out;
};

/** Model-facing tree (`component`/`key`/`action`) -> renderer tree (`$type`/`$key`/`$action`). */
export const toGenerativeTree = (args) => convert(args, undefined);

export default toGenerativeTree;
