// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/ai_studio_management.proto

package ai_studio_management

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIStudioManagementService_ListPlugins_FullMethodName         = "/ai_studio_management.AIStudioManagementService/ListPlugins"
	AIStudioManagementService_GetPlugin_FullMethodName           = "/ai_studio_management.AIStudioManagementService/GetPlugin"
	AIStudioManagementService_UpdatePluginConfig_FullMethodName  = "/ai_studio_management.AIStudioManagementService/UpdatePluginConfig"
	AIStudioManagementService_ListLLMs_FullMethodName            = "/ai_studio_management.AIStudioManagementService/ListLLMs"
	AIStudioManagementService_GetLLM_FullMethodName              = "/ai_studio_management.AIStudioManagementService/GetLLM"
	AIStudioManagementService_GetLLMPlugins_FullMethodName       = "/ai_studio_management.AIStudioManagementService/GetLLMPlugins"
	AIStudioManagementService_GetAnalyticsSummary_FullMethodName = "/ai_studio_management.AIStudioManagementService/GetAnalyticsSummary"
	AIStudioManagementService_GetUsageStatistics_FullMethodName  = "/ai_studio_management.AIStudioManagementService/GetUsageStatistics"
	AIStudioManagementService_GetCostAnalysis_FullMethodName     = "/ai_studio_management.AIStudioManagementService/GetCostAnalysis"
	AIStudioManagementService_ListApps_FullMethodName            = "/ai_studio_management.AIStudioManagementService/ListApps"
	AIStudioManagementService_GetApp_FullMethodName              = "/ai_studio_management.AIStudioManagementService/GetApp"
)

// AIStudioManagementServiceClient is the client API for AIStudioManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AIStudioManagementService provides AI Studio plugins with access to core management operations
// Plugins must be authorized by admin and have appropriate scopes to access these services
type AIStudioManagementServiceClient interface {
	// Plugin Management Operations
	ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error)
	GetPlugin(ctx context.Context, in *GetPluginRequest, opts ...grpc.CallOption) (*GetPluginResponse, error)
	UpdatePluginConfig(ctx context.Context, in *UpdatePluginConfigRequest, opts ...grpc.CallOption) (*UpdatePluginConfigResponse, error)
	// LLM Management Operations
	ListLLMs(ctx context.Context, in *ListLLMsRequest, opts ...grpc.CallOption) (*ListLLMsResponse, error)
	GetLLM(ctx context.Context, in *GetLLMRequest, opts ...grpc.CallOption) (*GetLLMResponse, error)
	GetLLMPlugins(ctx context.Context, in *GetLLMPluginsRequest, opts ...grpc.CallOption) (*GetLLMPluginsResponse, error)
	// Analytics Operations (with caching)
	GetAnalyticsSummary(ctx context.Context, in *GetAnalyticsSummaryRequest, opts ...grpc.CallOption) (*GetAnalyticsSummaryResponse, error)
	GetUsageStatistics(ctx context.Context, in *GetUsageStatisticsRequest, opts ...grpc.CallOption) (*GetUsageStatisticsResponse, error)
	GetCostAnalysis(ctx context.Context, in *GetCostAnalysisRequest, opts ...grpc.CallOption) (*GetCostAnalysisResponse, error)
	// App Management Operations
	ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error)
	GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*GetAppResponse, error)
}

type aIStudioManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIStudioManagementServiceClient(cc grpc.ClientConnInterface) AIStudioManagementServiceClient {
	return &aIStudioManagementServiceClient{cc}
}

func (c *aIStudioManagementServiceClient) ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginsResponse)
	err := c.cc.Invoke(ctx, AIStudioManagementService_ListPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIStudioManagementServiceClient) GetPlugin(ctx context.Context, in *GetPluginRequest, opts ...grpc.CallOption) (*GetPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPluginResponse)
	err := c.cc.Invoke(ctx, AIStudioManagementService_GetPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIStudioManagementServiceClient) UpdatePluginConfig(ctx context.Context, in *UpdatePluginConfigRequest, opts ...grpc.CallOption) (*UpdatePluginConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePluginConfigResponse)
	err := c.cc.Invoke(ctx, AIStudioManagementService_UpdatePluginConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIStudioManagementServiceClient) ListLLMs(ctx context.Context, in *ListLLMsRequest, opts ...grpc.CallOption) (*ListLLMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLLMsResponse)
	err := c.cc.Invoke(ctx, AIStudioManagementService_ListLLMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIStudioManagementServiceClient) GetLLM(ctx context.Context, in *GetLLMRequest, opts ...grpc.CallOption) (*GetLLMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLLMResponse)
	err := c.cc.Invoke(ctx, AIStudioManagementService_GetLLM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIStudioManagementServiceClient) GetLLMPlugins(ctx context.Context, in *GetLLMPluginsRequest, opts ...grpc.CallOption) (*GetLLMPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLLMPluginsResponse)
	err := c.cc.Invoke(ctx, AIStudioManagementService_GetLLMPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIStudioManagementServiceClient) GetAnalyticsSummary(ctx context.Context, in *GetAnalyticsSummaryRequest, opts ...grpc.CallOption) (*GetAnalyticsSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnalyticsSummaryResponse)
	err := c.cc.Invoke(ctx, AIStudioManagementService_GetAnalyticsSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIStudioManagementServiceClient) GetUsageStatistics(ctx context.Context, in *GetUsageStatisticsRequest, opts ...grpc.CallOption) (*GetUsageStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsageStatisticsResponse)
	err := c.cc.Invoke(ctx, AIStudioManagementService_GetUsageStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIStudioManagementServiceClient) GetCostAnalysis(ctx context.Context, in *GetCostAnalysisRequest, opts ...grpc.CallOption) (*GetCostAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCostAnalysisResponse)
	err := c.cc.Invoke(ctx, AIStudioManagementService_GetCostAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIStudioManagementServiceClient) ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppsResponse)
	err := c.cc.Invoke(ctx, AIStudioManagementService_ListApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIStudioManagementServiceClient) GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*GetAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppResponse)
	err := c.cc.Invoke(ctx, AIStudioManagementService_GetApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIStudioManagementServiceServer is the server API for AIStudioManagementService service.
// All implementations must embed UnimplementedAIStudioManagementServiceServer
// for forward compatibility.
//
// AIStudioManagementService provides AI Studio plugins with access to core management operations
// Plugins must be authorized by admin and have appropriate scopes to access these services
type AIStudioManagementServiceServer interface {
	// Plugin Management Operations
	ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error)
	GetPlugin(context.Context, *GetPluginRequest) (*GetPluginResponse, error)
	UpdatePluginConfig(context.Context, *UpdatePluginConfigRequest) (*UpdatePluginConfigResponse, error)
	// LLM Management Operations
	ListLLMs(context.Context, *ListLLMsRequest) (*ListLLMsResponse, error)
	GetLLM(context.Context, *GetLLMRequest) (*GetLLMResponse, error)
	GetLLMPlugins(context.Context, *GetLLMPluginsRequest) (*GetLLMPluginsResponse, error)
	// Analytics Operations (with caching)
	GetAnalyticsSummary(context.Context, *GetAnalyticsSummaryRequest) (*GetAnalyticsSummaryResponse, error)
	GetUsageStatistics(context.Context, *GetUsageStatisticsRequest) (*GetUsageStatisticsResponse, error)
	GetCostAnalysis(context.Context, *GetCostAnalysisRequest) (*GetCostAnalysisResponse, error)
	// App Management Operations
	ListApps(context.Context, *ListAppsRequest) (*ListAppsResponse, error)
	GetApp(context.Context, *GetAppRequest) (*GetAppResponse, error)
	mustEmbedUnimplementedAIStudioManagementServiceServer()
}

// UnimplementedAIStudioManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIStudioManagementServiceServer struct{}

func (UnimplementedAIStudioManagementServiceServer) ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedAIStudioManagementServiceServer) GetPlugin(context.Context, *GetPluginRequest) (*GetPluginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlugin not implemented")
}
func (UnimplementedAIStudioManagementServiceServer) UpdatePluginConfig(context.Context, *UpdatePluginConfigRequest) (*UpdatePluginConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePluginConfig not implemented")
}
func (UnimplementedAIStudioManagementServiceServer) ListLLMs(context.Context, *ListLLMsRequest) (*ListLLMsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLLMs not implemented")
}
func (UnimplementedAIStudioManagementServiceServer) GetLLM(context.Context, *GetLLMRequest) (*GetLLMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLLM not implemented")
}
func (UnimplementedAIStudioManagementServiceServer) GetLLMPlugins(context.Context, *GetLLMPluginsRequest) (*GetLLMPluginsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLLMPlugins not implemented")
}
func (UnimplementedAIStudioManagementServiceServer) GetAnalyticsSummary(context.Context, *GetAnalyticsSummaryRequest) (*GetAnalyticsSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnalyticsSummary not implemented")
}
func (UnimplementedAIStudioManagementServiceServer) GetUsageStatistics(context.Context, *GetUsageStatisticsRequest) (*GetUsageStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsageStatistics not implemented")
}
func (UnimplementedAIStudioManagementServiceServer) GetCostAnalysis(context.Context, *GetCostAnalysisRequest) (*GetCostAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCostAnalysis not implemented")
}
func (UnimplementedAIStudioManagementServiceServer) ListApps(context.Context, *ListAppsRequest) (*ListAppsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApps not implemented")
}
func (UnimplementedAIStudioManagementServiceServer) GetApp(context.Context, *GetAppRequest) (*GetAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApp not implemented")
}
func (UnimplementedAIStudioManagementServiceServer) mustEmbedUnimplementedAIStudioManagementServiceServer() {
}
func (UnimplementedAIStudioManagementServiceServer) testEmbeddedByValue() {}

// UnsafeAIStudioManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIStudioManagementServiceServer will
// result in compilation errors.
type UnsafeAIStudioManagementServiceServer interface {
	mustEmbedUnimplementedAIStudioManagementServiceServer()
}

func RegisterAIStudioManagementServiceServer(s grpc.ServiceRegistrar, srv AIStudioManagementServiceServer) {
	// If the following call pancis, it indicates UnimplementedAIStudioManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIStudioManagementService_ServiceDesc, srv)
}

func _AIStudioManagementService_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIStudioManagementServiceServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIStudioManagementService_ListPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIStudioManagementServiceServer).ListPlugins(ctx, req.(*ListPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIStudioManagementService_GetPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIStudioManagementServiceServer).GetPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIStudioManagementService_GetPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIStudioManagementServiceServer).GetPlugin(ctx, req.(*GetPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIStudioManagementService_UpdatePluginConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePluginConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIStudioManagementServiceServer).UpdatePluginConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIStudioManagementService_UpdatePluginConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIStudioManagementServiceServer).UpdatePluginConfig(ctx, req.(*UpdatePluginConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIStudioManagementService_ListLLMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLLMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIStudioManagementServiceServer).ListLLMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIStudioManagementService_ListLLMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIStudioManagementServiceServer).ListLLMs(ctx, req.(*ListLLMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIStudioManagementService_GetLLM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLLMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIStudioManagementServiceServer).GetLLM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIStudioManagementService_GetLLM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIStudioManagementServiceServer).GetLLM(ctx, req.(*GetLLMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIStudioManagementService_GetLLMPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLLMPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIStudioManagementServiceServer).GetLLMPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIStudioManagementService_GetLLMPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIStudioManagementServiceServer).GetLLMPlugins(ctx, req.(*GetLLMPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIStudioManagementService_GetAnalyticsSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalyticsSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIStudioManagementServiceServer).GetAnalyticsSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIStudioManagementService_GetAnalyticsSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIStudioManagementServiceServer).GetAnalyticsSummary(ctx, req.(*GetAnalyticsSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIStudioManagementService_GetUsageStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsageStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIStudioManagementServiceServer).GetUsageStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIStudioManagementService_GetUsageStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIStudioManagementServiceServer).GetUsageStatistics(ctx, req.(*GetUsageStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIStudioManagementService_GetCostAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCostAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIStudioManagementServiceServer).GetCostAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIStudioManagementService_GetCostAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIStudioManagementServiceServer).GetCostAnalysis(ctx, req.(*GetCostAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIStudioManagementService_ListApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIStudioManagementServiceServer).ListApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIStudioManagementService_ListApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIStudioManagementServiceServer).ListApps(ctx, req.(*ListAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIStudioManagementService_GetApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIStudioManagementServiceServer).GetApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIStudioManagementService_GetApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIStudioManagementServiceServer).GetApp(ctx, req.(*GetAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIStudioManagementService_ServiceDesc is the grpc.ServiceDesc for AIStudioManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIStudioManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_studio_management.AIStudioManagementService",
	HandlerType: (*AIStudioManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPlugins",
			Handler:    _AIStudioManagementService_ListPlugins_Handler,
		},
		{
			MethodName: "GetPlugin",
			Handler:    _AIStudioManagementService_GetPlugin_Handler,
		},
		{
			MethodName: "UpdatePluginConfig",
			Handler:    _AIStudioManagementService_UpdatePluginConfig_Handler,
		},
		{
			MethodName: "ListLLMs",
			Handler:    _AIStudioManagementService_ListLLMs_Handler,
		},
		{
			MethodName: "GetLLM",
			Handler:    _AIStudioManagementService_GetLLM_Handler,
		},
		{
			MethodName: "GetLLMPlugins",
			Handler:    _AIStudioManagementService_GetLLMPlugins_Handler,
		},
		{
			MethodName: "GetAnalyticsSummary",
			Handler:    _AIStudioManagementService_GetAnalyticsSummary_Handler,
		},
		{
			MethodName: "GetUsageStatistics",
			Handler:    _AIStudioManagementService_GetUsageStatistics_Handler,
		},
		{
			MethodName: "GetCostAnalysis",
			Handler:    _AIStudioManagementService_GetCostAnalysis_Handler,
		},
		{
			MethodName: "ListApps",
			Handler:    _AIStudioManagementService_ListApps_Handler,
		},
		{
			MethodName: "GetApp",
			Handler:    _AIStudioManagementService_GetApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ai_studio_management.proto",
}
