// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: proto/ai_studio_management.proto

package ai_studio_management

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common request context for all operations
type PluginContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      uint32                 `protobuf:"varint,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`         // Authenticated plugin ID
	MethodScope   string                 `protobuf:"bytes,2,opt,name=method_scope,json=methodScope,proto3" json:"method_scope,omitempty"` // Required service scope (e.g., "plugins.read")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginContext) Reset() {
	*x = PluginContext{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginContext) ProtoMessage() {}

func (x *PluginContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginContext.ProtoReflect.Descriptor instead.
func (*PluginContext) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{0}
}

func (x *PluginContext) GetPluginId() uint32 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

func (x *PluginContext) GetMethodScope() string {
	if x != nil {
		return x.MethodScope
	}
	return ""
}

type ListPluginsRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Context *PluginContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// Filtering options
	HookType  string `protobuf:"bytes,2,opt,name=hook_type,json=hookType,proto3" json:"hook_type,omitempty"`
	IsActive  *bool  `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Pagination
	Page          int32 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{1}
}

func (x *ListPluginsRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ListPluginsRequest) GetHookType() string {
	if x != nil {
		return x.HookType
	}
	return ""
}

func (x *ListPluginsRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *ListPluginsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListPluginsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPluginsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginInfo          `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{2}
}

func (x *ListPluginsResponse) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *ListPluginsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListPluginsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *PluginContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	PluginId      uint32                 `protobuf:"varint,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginRequest) Reset() {
	*x = GetPluginRequest{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginRequest) ProtoMessage() {}

func (x *GetPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginRequest.ProtoReflect.Descriptor instead.
func (*GetPluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{3}
}

func (x *GetPluginRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetPluginRequest) GetPluginId() uint32 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

type GetPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        *PluginInfo            `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginResponse) Reset() {
	*x = GetPluginResponse{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginResponse) ProtoMessage() {}

func (x *GetPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginResponse.ProtoReflect.Descriptor instead.
func (*GetPluginResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{4}
}

func (x *GetPluginResponse) GetPlugin() *PluginInfo {
	if x != nil {
		return x.Plugin
	}
	return nil
}

type UpdatePluginConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *PluginContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	PluginId      uint32                 `protobuf:"varint,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // JSON string of new configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePluginConfigRequest) Reset() {
	*x = UpdatePluginConfigRequest{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePluginConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePluginConfigRequest) ProtoMessage() {}

func (x *UpdatePluginConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePluginConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdatePluginConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePluginConfigRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UpdatePluginConfigRequest) GetPluginId() uint32 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

func (x *UpdatePluginConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type UpdatePluginConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePluginConfigResponse) Reset() {
	*x = UpdatePluginConfigResponse{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePluginConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePluginConfigResponse) ProtoMessage() {}

func (x *UpdatePluginConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePluginConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdatePluginConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePluginConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePluginConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PluginInfo struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug                    string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description             string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Command                 string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	ConfigJson              string                 `protobuf:"bytes,6,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	HookType                string                 `protobuf:"bytes,7,opt,name=hook_type,json=hookType,proto3" json:"hook_type,omitempty"`
	IsActive                bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Namespace               string                 `protobuf:"bytes,9,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PluginType              string                 `protobuf:"bytes,10,opt,name=plugin_type,json=pluginType,proto3" json:"plugin_type,omitempty"`
	ServiceAccessAuthorized bool                   `protobuf:"varint,11,opt,name=service_access_authorized,json=serviceAccessAuthorized,proto3" json:"service_access_authorized,omitempty"`
	ServiceScopes           []string               `protobuf:"bytes,12,rep,name=service_scopes,json=serviceScopes,proto3" json:"service_scopes,omitempty"`
	CreatedAt               *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt               *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{7}
}

func (x *PluginInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *PluginInfo) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *PluginInfo) GetHookType() string {
	if x != nil {
		return x.HookType
	}
	return ""
}

func (x *PluginInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *PluginInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PluginInfo) GetPluginType() string {
	if x != nil {
		return x.PluginType
	}
	return ""
}

func (x *PluginInfo) GetServiceAccessAuthorized() bool {
	if x != nil {
		return x.ServiceAccessAuthorized
	}
	return false
}

func (x *PluginInfo) GetServiceScopes() []string {
	if x != nil {
		return x.ServiceScopes
	}
	return nil
}

func (x *PluginInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PluginInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListLLMsRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Context *PluginContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// Filtering options
	Vendor    string `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	IsActive  *bool  `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Pagination
	Page          int32 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLLMsRequest) Reset() {
	*x = ListLLMsRequest{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLLMsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLLMsRequest) ProtoMessage() {}

func (x *ListLLMsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLLMsRequest.ProtoReflect.Descriptor instead.
func (*ListLLMsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{8}
}

func (x *ListLLMsRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ListLLMsRequest) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *ListLLMsRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *ListLLMsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListLLMsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLLMsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLLMsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Llms          []*LLMInfo             `protobuf:"bytes,1,rep,name=llms,proto3" json:"llms,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLLMsResponse) Reset() {
	*x = ListLLMsResponse{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLLMsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLLMsResponse) ProtoMessage() {}

func (x *ListLLMsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLLMsResponse.ProtoReflect.Descriptor instead.
func (*ListLLMsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{9}
}

func (x *ListLLMsResponse) GetLlms() []*LLMInfo {
	if x != nil {
		return x.Llms
	}
	return nil
}

func (x *ListLLMsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetLLMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *PluginContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	LlmId         uint32                 `protobuf:"varint,2,opt,name=llm_id,json=llmId,proto3" json:"llm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLLMRequest) Reset() {
	*x = GetLLMRequest{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLLMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLLMRequest) ProtoMessage() {}

func (x *GetLLMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLLMRequest.ProtoReflect.Descriptor instead.
func (*GetLLMRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{10}
}

func (x *GetLLMRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetLLMRequest) GetLlmId() uint32 {
	if x != nil {
		return x.LlmId
	}
	return 0
}

type GetLLMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Llm           *LLMInfo               `protobuf:"bytes,1,opt,name=llm,proto3" json:"llm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLLMResponse) Reset() {
	*x = GetLLMResponse{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLLMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLLMResponse) ProtoMessage() {}

func (x *GetLLMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLLMResponse.ProtoReflect.Descriptor instead.
func (*GetLLMResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{11}
}

func (x *GetLLMResponse) GetLlm() *LLMInfo {
	if x != nil {
		return x.Llm
	}
	return nil
}

type GetLLMPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *PluginContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	LlmId         uint32                 `protobuf:"varint,2,opt,name=llm_id,json=llmId,proto3" json:"llm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLLMPluginsRequest) Reset() {
	*x = GetLLMPluginsRequest{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLLMPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLLMPluginsRequest) ProtoMessage() {}

func (x *GetLLMPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLLMPluginsRequest.ProtoReflect.Descriptor instead.
func (*GetLLMPluginsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{12}
}

func (x *GetLLMPluginsRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetLLMPluginsRequest) GetLlmId() uint32 {
	if x != nil {
		return x.LlmId
	}
	return 0
}

type GetLLMPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginInfo          `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLLMPluginsResponse) Reset() {
	*x = GetLLMPluginsResponse{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLLMPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLLMPluginsResponse) ProtoMessage() {}

func (x *GetLLMPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLLMPluginsResponse.ProtoReflect.Descriptor instead.
func (*GetLLMPluginsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{13}
}

func (x *GetLLMPluginsResponse) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type LLMInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Vendor           string                 `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	ApiEndpoint      string                 `protobuf:"bytes,4,opt,name=api_endpoint,json=apiEndpoint,proto3" json:"api_endpoint,omitempty"`
	HasApiKey        bool                   `protobuf:"varint,5,opt,name=has_api_key,json=hasApiKey,proto3" json:"has_api_key,omitempty"` // Don't expose actual key
	PrivacyScore     int32                  `protobuf:"varint,6,opt,name=privacy_score,json=privacyScore,proto3" json:"privacy_score,omitempty"`
	ShortDescription string                 `protobuf:"bytes,7,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	DefaultModel     string                 `protobuf:"bytes,8,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	AllowedModels    []string               `protobuf:"bytes,9,rep,name=allowed_models,json=allowedModels,proto3" json:"allowed_models,omitempty"`
	Active           bool                   `protobuf:"varint,10,opt,name=active,proto3" json:"active,omitempty"`
	Namespace        string                 `protobuf:"bytes,11,opt,name=namespace,proto3" json:"namespace,omitempty"`
	MonthlyBudget    *float64               `protobuf:"fixed64,12,opt,name=monthly_budget,json=monthlyBudget,proto3,oneof" json:"monthly_budget,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LLMInfo) Reset() {
	*x = LLMInfo{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMInfo) ProtoMessage() {}

func (x *LLMInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMInfo.ProtoReflect.Descriptor instead.
func (*LLMInfo) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{14}
}

func (x *LLMInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LLMInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LLMInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *LLMInfo) GetApiEndpoint() string {
	if x != nil {
		return x.ApiEndpoint
	}
	return ""
}

func (x *LLMInfo) GetHasApiKey() bool {
	if x != nil {
		return x.HasApiKey
	}
	return false
}

func (x *LLMInfo) GetPrivacyScore() int32 {
	if x != nil {
		return x.PrivacyScore
	}
	return 0
}

func (x *LLMInfo) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *LLMInfo) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

func (x *LLMInfo) GetAllowedModels() []string {
	if x != nil {
		return x.AllowedModels
	}
	return nil
}

func (x *LLMInfo) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *LLMInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LLMInfo) GetMonthlyBudget() float64 {
	if x != nil && x.MonthlyBudget != nil {
		return *x.MonthlyBudget
	}
	return 0
}

func (x *LLMInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LLMInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetAnalyticsSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *PluginContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	TimeRange     string                 `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"` // "24h", "7d", "30d", etc.
	AppId         *uint32                `protobuf:"varint,3,opt,name=app_id,json=appId,proto3,oneof" json:"app_id,omitempty"`      // Filter by specific app
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyticsSummaryRequest) Reset() {
	*x = GetAnalyticsSummaryRequest{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsSummaryRequest) ProtoMessage() {}

func (x *GetAnalyticsSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetAnalyticsSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{15}
}

func (x *GetAnalyticsSummaryRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetAnalyticsSummaryRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *GetAnalyticsSummaryRequest) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

type GetAnalyticsSummaryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests      int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	SuccessfulRequests int64                  `protobuf:"varint,2,opt,name=successful_requests,json=successfulRequests,proto3" json:"successful_requests,omitempty"`
	FailedRequests     int64                  `protobuf:"varint,3,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	TotalCost          float64                `protobuf:"fixed64,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Currency           string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	TotalTokens        int64                  `protobuf:"varint,6,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TopEndpoints       []*TopEndpoint         `protobuf:"bytes,7,rep,name=top_endpoints,json=topEndpoints,proto3" json:"top_endpoints,omitempty"`
	ModelUsage         []*ModelUsage          `protobuf:"bytes,8,rep,name=model_usage,json=modelUsage,proto3" json:"model_usage,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetAnalyticsSummaryResponse) Reset() {
	*x = GetAnalyticsSummaryResponse{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsSummaryResponse) ProtoMessage() {}

func (x *GetAnalyticsSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetAnalyticsSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{16}
}

func (x *GetAnalyticsSummaryResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *GetAnalyticsSummaryResponse) GetSuccessfulRequests() int64 {
	if x != nil {
		return x.SuccessfulRequests
	}
	return 0
}

func (x *GetAnalyticsSummaryResponse) GetFailedRequests() int64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *GetAnalyticsSummaryResponse) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *GetAnalyticsSummaryResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetAnalyticsSummaryResponse) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *GetAnalyticsSummaryResponse) GetTopEndpoints() []*TopEndpoint {
	if x != nil {
		return x.TopEndpoints
	}
	return nil
}

func (x *GetAnalyticsSummaryResponse) GetModelUsage() []*ModelUsage {
	if x != nil {
		return x.ModelUsage
	}
	return nil
}

type GetUsageStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *PluginContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	TimeRange     string                 `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	GroupBy       string                 `protobuf:"bytes,3,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"` // "app", "llm", "model", "day"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageStatisticsRequest) Reset() {
	*x = GetUsageStatisticsRequest{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageStatisticsRequest) ProtoMessage() {}

func (x *GetUsageStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetUsageStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{17}
}

func (x *GetUsageStatisticsRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetUsageStatisticsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *GetUsageStatisticsRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

type GetUsageStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statistics    []*UsageStatistic      `protobuf:"bytes,1,rep,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageStatisticsResponse) Reset() {
	*x = GetUsageStatisticsResponse{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageStatisticsResponse) ProtoMessage() {}

func (x *GetUsageStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetUsageStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{18}
}

func (x *GetUsageStatisticsResponse) GetStatistics() []*UsageStatistic {
	if x != nil {
		return x.Statistics
	}
	return nil
}

type GetCostAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *PluginContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	TimeRange     string                 `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	AppId         *uint32                `protobuf:"varint,3,opt,name=app_id,json=appId,proto3,oneof" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCostAnalysisRequest) Reset() {
	*x = GetCostAnalysisRequest{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCostAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCostAnalysisRequest) ProtoMessage() {}

func (x *GetCostAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCostAnalysisRequest.ProtoReflect.Descriptor instead.
func (*GetCostAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{19}
}

func (x *GetCostAnalysisRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetCostAnalysisRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *GetCostAnalysisRequest) GetAppId() uint32 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

type GetCostAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCost     float64                `protobuf:"fixed64,1,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Breakdown     []*CostBreakdown       `protobuf:"bytes,3,rep,name=breakdown,proto3" json:"breakdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCostAnalysisResponse) Reset() {
	*x = GetCostAnalysisResponse{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCostAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCostAnalysisResponse) ProtoMessage() {}

func (x *GetCostAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCostAnalysisResponse.ProtoReflect.Descriptor instead.
func (*GetCostAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{20}
}

func (x *GetCostAnalysisResponse) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *GetCostAnalysisResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetCostAnalysisResponse) GetBreakdown() []*CostBreakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

type TopEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	RequestCount  int64                  `protobuf:"varint,2,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	BlockedCount  int64                  `protobuf:"varint,3,opt,name=blocked_count,json=blockedCount,proto3" json:"blocked_count,omitempty"`
	SuccessRate   float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopEndpoint) Reset() {
	*x = TopEndpoint{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopEndpoint) ProtoMessage() {}

func (x *TopEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopEndpoint.ProtoReflect.Descriptor instead.
func (*TopEndpoint) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{21}
}

func (x *TopEndpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TopEndpoint) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *TopEndpoint) GetBlockedCount() int64 {
	if x != nil {
		return x.BlockedCount
	}
	return 0
}

func (x *TopEndpoint) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

type ModelUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	RequestCount  int64                  `protobuf:"varint,3,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	TotalTokens   int64                  `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TotalCost     float64                `protobuf:"fixed64,5,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelUsage) Reset() {
	*x = ModelUsage{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUsage) ProtoMessage() {}

func (x *ModelUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUsage.ProtoReflect.Descriptor instead.
func (*ModelUsage) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{22}
}

func (x *ModelUsage) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelUsage) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *ModelUsage) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *ModelUsage) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ModelUsage) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

type UsageStatistic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // Group identifier (app_id, llm_id, model_name, date)
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // Human readable label
	RequestCount  int64                  `protobuf:"varint,3,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	TokenCount    int64                  `protobuf:"varint,4,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	Cost          float64                `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageStatistic) Reset() {
	*x = UsageStatistic{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageStatistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageStatistic) ProtoMessage() {}

func (x *UsageStatistic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageStatistic.ProtoReflect.Descriptor instead.
func (*UsageStatistic) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{23}
}

func (x *UsageStatistic) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UsageStatistic) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UsageStatistic) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *UsageStatistic) GetTokenCount() int64 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *UsageStatistic) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *UsageStatistic) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CostBreakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // "vendor", "model", "app"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`         // Specific name within category
	Cost          float64                `protobuf:"fixed64,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Percentage    float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostBreakdown) Reset() {
	*x = CostBreakdown{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostBreakdown) ProtoMessage() {}

func (x *CostBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostBreakdown.ProtoReflect.Descriptor instead.
func (*CostBreakdown) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{24}
}

func (x *CostBreakdown) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CostBreakdown) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CostBreakdown) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CostBreakdown) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type ListAppsRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Context *PluginContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// Filtering options
	IsActive  *bool  `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Pagination
	Page          int32 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsRequest) Reset() {
	*x = ListAppsRequest{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsRequest) ProtoMessage() {}

func (x *ListAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsRequest.ProtoReflect.Descriptor instead.
func (*ListAppsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{25}
}

func (x *ListAppsRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ListAppsRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *ListAppsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListAppsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAppsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*AppInfo             `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsResponse) Reset() {
	*x = ListAppsResponse{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsResponse) ProtoMessage() {}

func (x *ListAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsResponse.ProtoReflect.Descriptor instead.
func (*ListAppsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{26}
}

func (x *ListAppsResponse) GetApps() []*AppInfo {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *ListAppsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *PluginContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	AppId         uint32                 `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppRequest) Reset() {
	*x = GetAppRequest{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppRequest) ProtoMessage() {}

func (x *GetAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppRequest.ProtoReflect.Descriptor instead.
func (*GetAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{27}
}

func (x *GetAppRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetAppRequest) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type GetAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *AppInfo               `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppResponse) Reset() {
	*x = GetAppResponse{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppResponse) ProtoMessage() {}

func (x *GetAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppResponse.ProtoReflect.Descriptor instead.
func (*GetAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{28}
}

func (x *GetAppResponse) GetApp() *AppInfo {
	if x != nil {
		return x.App
	}
	return nil
}

type AppInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	MonthlyBudget *float64               `protobuf:"fixed64,6,opt,name=monthly_budget,json=monthlyBudget,proto3,oneof" json:"monthly_budget,omitempty"`
	LlmIds        []uint32               `protobuf:"varint,7,rep,packed,name=llm_ids,json=llmIds,proto3" json:"llm_ids,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppInfo) Reset() {
	*x = AppInfo{}
	mi := &file_proto_ai_studio_management_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo) ProtoMessage() {}

func (x *AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_studio_management_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo.ProtoReflect.Descriptor instead.
func (*AppInfo) Descriptor() ([]byte, []int) {
	return file_proto_ai_studio_management_proto_rawDescGZIP(), []int{29}
}

func (x *AppInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AppInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *AppInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AppInfo) GetMonthlyBudget() float64 {
	if x != nil && x.MonthlyBudget != nil {
		return *x.MonthlyBudget
	}
	return 0
}

func (x *AppInfo) GetLlmIds() []uint32 {
	if x != nil {
		return x.LlmIds
	}
	return nil
}

func (x *AppInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AppInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_ai_studio_management_proto protoreflect.FileDescriptor

const file_proto_ai_studio_management_proto_rawDesc = "" +
	"\n" +
	" proto/ai_studio_management.proto\x12\x14ai_studio_management\x1a\x1fgoogle/protobuf/timestamp.proto\"O\n" +
	"\rPluginContext\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\rR\bpluginId\x12!\n" +
	"\fmethod_scope\x18\x02 \x01(\tR\vmethodScope\"\xe8\x01\n" +
	"\x12ListPluginsRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.ai_studio_management.PluginContextR\acontext\x12\x1b\n" +
	"\thook_type\x18\x02 \x01(\tR\bhookType\x12 \n" +
	"\tis_active\x18\x03 \x01(\bH\x00R\bisActive\x88\x01\x01\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limitB\f\n" +
	"\n" +
	"_is_active\"\x93\x01\n" +
	"\x13ListPluginsResponse\x12:\n" +
	"\aplugins\x18\x01 \x03(\v2 .ai_studio_management.PluginInfoR\aplugins\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\"n\n" +
	"\x10GetPluginRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.ai_studio_management.PluginContextR\acontext\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\rR\bpluginId\"M\n" +
	"\x11GetPluginResponse\x128\n" +
	"\x06plugin\x18\x01 \x01(\v2 .ai_studio_management.PluginInfoR\x06plugin\"\x98\x01\n" +
	"\x19UpdatePluginConfigRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.ai_studio_management.PluginContextR\acontext\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\rR\bpluginId\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\tR\n" +
	"configJson\"P\n" +
	"\x1aUpdatePluginConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf3\x03\n" +
	"\n" +
	"PluginInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12\x1f\n" +
	"\vconfig_json\x18\x06 \x01(\tR\n" +
	"configJson\x12\x1b\n" +
	"\thook_type\x18\a \x01(\tR\bhookType\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12\x1c\n" +
	"\tnamespace\x18\t \x01(\tR\tnamespace\x12\x1f\n" +
	"\vplugin_type\x18\n" +
	" \x01(\tR\n" +
	"pluginType\x12:\n" +
	"\x19service_access_authorized\x18\v \x01(\bR\x17serviceAccessAuthorized\x12%\n" +
	"\x0eservice_scopes\x18\f \x03(\tR\rserviceScopes\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe0\x01\n" +
	"\x0fListLLMsRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.ai_studio_management.PluginContextR\acontext\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12 \n" +
	"\tis_active\x18\x03 \x01(\bH\x00R\bisActive\x88\x01\x01\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limitB\f\n" +
	"\n" +
	"_is_active\"f\n" +
	"\x10ListLLMsResponse\x121\n" +
	"\x04llms\x18\x01 \x03(\v2\x1d.ai_studio_management.LLMInfoR\x04llms\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"e\n" +
	"\rGetLLMRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.ai_studio_management.PluginContextR\acontext\x12\x15\n" +
	"\x06llm_id\x18\x02 \x01(\rR\x05llmId\"A\n" +
	"\x0eGetLLMResponse\x12/\n" +
	"\x03llm\x18\x01 \x01(\v2\x1d.ai_studio_management.LLMInfoR\x03llm\"l\n" +
	"\x14GetLLMPluginsRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.ai_studio_management.PluginContextR\acontext\x12\x15\n" +
	"\x06llm_id\x18\x02 \x01(\rR\x05llmId\"S\n" +
	"\x15GetLLMPluginsResponse\x12:\n" +
	"\aplugins\x18\x01 \x03(\v2 .ai_studio_management.PluginInfoR\aplugins\"\x91\x04\n" +
	"\aLLMInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\tR\x06vendor\x12!\n" +
	"\fapi_endpoint\x18\x04 \x01(\tR\vapiEndpoint\x12\x1e\n" +
	"\vhas_api_key\x18\x05 \x01(\bR\thasApiKey\x12#\n" +
	"\rprivacy_score\x18\x06 \x01(\x05R\fprivacyScore\x12+\n" +
	"\x11short_description\x18\a \x01(\tR\x10shortDescription\x12#\n" +
	"\rdefault_model\x18\b \x01(\tR\fdefaultModel\x12%\n" +
	"\x0eallowed_models\x18\t \x03(\tR\rallowedModels\x12\x16\n" +
	"\x06active\x18\n" +
	" \x01(\bR\x06active\x12\x1c\n" +
	"\tnamespace\x18\v \x01(\tR\tnamespace\x12*\n" +
	"\x0emonthly_budget\x18\f \x01(\x01H\x00R\rmonthlyBudget\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x11\n" +
	"\x0f_monthly_budget\"\xa1\x01\n" +
	"\x1aGetAnalyticsSummaryRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.ai_studio_management.PluginContextR\acontext\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\x12\x1a\n" +
	"\x06app_id\x18\x03 \x01(\rH\x00R\x05appId\x88\x01\x01B\t\n" +
	"\a_app_id\"\x87\x03\n" +
	"\x1bGetAnalyticsSummaryResponse\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12/\n" +
	"\x13successful_requests\x18\x02 \x01(\x03R\x12successfulRequests\x12'\n" +
	"\x0ffailed_requests\x18\x03 \x01(\x03R\x0efailedRequests\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x04 \x01(\x01R\ttotalCost\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12!\n" +
	"\ftotal_tokens\x18\x06 \x01(\x03R\vtotalTokens\x12F\n" +
	"\rtop_endpoints\x18\a \x03(\v2!.ai_studio_management.TopEndpointR\ftopEndpoints\x12A\n" +
	"\vmodel_usage\x18\b \x03(\v2 .ai_studio_management.ModelUsageR\n" +
	"modelUsage\"\x94\x01\n" +
	"\x19GetUsageStatisticsRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.ai_studio_management.PluginContextR\acontext\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\x12\x19\n" +
	"\bgroup_by\x18\x03 \x01(\tR\agroupBy\"b\n" +
	"\x1aGetUsageStatisticsResponse\x12D\n" +
	"\n" +
	"statistics\x18\x01 \x03(\v2$.ai_studio_management.UsageStatisticR\n" +
	"statistics\"\x9d\x01\n" +
	"\x16GetCostAnalysisRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.ai_studio_management.PluginContextR\acontext\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\x12\x1a\n" +
	"\x06app_id\x18\x03 \x01(\rH\x00R\x05appId\x88\x01\x01B\t\n" +
	"\a_app_id\"\x97\x01\n" +
	"\x17GetCostAnalysisResponse\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x01 \x01(\x01R\ttotalCost\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12A\n" +
	"\tbreakdown\x18\x03 \x03(\v2#.ai_studio_management.CostBreakdownR\tbreakdown\"\x8e\x01\n" +
	"\vTopEndpoint\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\rrequest_count\x18\x02 \x01(\x03R\frequestCount\x12#\n" +
	"\rblocked_count\x18\x03 \x01(\x03R\fblockedCount\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\"\xaa\x01\n" +
	"\n" +
	"ModelUsage\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12#\n" +
	"\rrequest_count\x18\x03 \x01(\x03R\frequestCount\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x03R\vtotalTokens\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x05 \x01(\x01R\ttotalCost\"\xcc\x01\n" +
	"\x0eUsageStatistic\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12#\n" +
	"\rrequest_count\x18\x03 \x01(\x03R\frequestCount\x12\x1f\n" +
	"\vtoken_count\x18\x04 \x01(\x03R\n" +
	"tokenCount\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x01R\x04cost\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"s\n" +
	"\rCostBreakdown\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x01R\x04cost\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\"\xc8\x01\n" +
	"\x0fListAppsRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.ai_studio_management.PluginContextR\acontext\x12 \n" +
	"\tis_active\x18\x02 \x01(\bH\x00R\bisActive\x88\x01\x01\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limitB\f\n" +
	"\n" +
	"_is_active\"f\n" +
	"\x10ListAppsResponse\x121\n" +
	"\x04apps\x18\x01 \x03(\v2\x1d.ai_studio_management.AppInfoR\x04apps\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"e\n" +
	"\rGetAppRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.ai_studio_management.PluginContextR\acontext\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\rR\x05appId\"A\n" +
	"\x0eGetAppResponse\x12/\n" +
	"\x03app\x18\x01 \x01(\v2\x1d.ai_studio_management.AppInfoR\x03app\"\xd8\x02\n" +
	"\aAppInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12*\n" +
	"\x0emonthly_budget\x18\x06 \x01(\x01H\x00R\rmonthlyBudget\x88\x01\x01\x12\x17\n" +
	"\allm_ids\x18\a \x03(\rR\x06llmIds\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x11\n" +
	"\x0f_monthly_budget2\x85\t\n" +
	"\x19AIStudioManagementService\x12b\n" +
	"\vListPlugins\x12(.ai_studio_management.ListPluginsRequest\x1a).ai_studio_management.ListPluginsResponse\x12\\\n" +
	"\tGetPlugin\x12&.ai_studio_management.GetPluginRequest\x1a'.ai_studio_management.GetPluginResponse\x12w\n" +
	"\x12UpdatePluginConfig\x12/.ai_studio_management.UpdatePluginConfigRequest\x1a0.ai_studio_management.UpdatePluginConfigResponse\x12Y\n" +
	"\bListLLMs\x12%.ai_studio_management.ListLLMsRequest\x1a&.ai_studio_management.ListLLMsResponse\x12S\n" +
	"\x06GetLLM\x12#.ai_studio_management.GetLLMRequest\x1a$.ai_studio_management.GetLLMResponse\x12h\n" +
	"\rGetLLMPlugins\x12*.ai_studio_management.GetLLMPluginsRequest\x1a+.ai_studio_management.GetLLMPluginsResponse\x12z\n" +
	"\x13GetAnalyticsSummary\x120.ai_studio_management.GetAnalyticsSummaryRequest\x1a1.ai_studio_management.GetAnalyticsSummaryResponse\x12w\n" +
	"\x12GetUsageStatistics\x12/.ai_studio_management.GetUsageStatisticsRequest\x1a0.ai_studio_management.GetUsageStatisticsResponse\x12n\n" +
	"\x0fGetCostAnalysis\x12,.ai_studio_management.GetCostAnalysisRequest\x1a-.ai_studio_management.GetCostAnalysisResponse\x12Y\n" +
	"\bListApps\x12%.ai_studio_management.ListAppsRequest\x1a&.ai_studio_management.ListAppsResponse\x12S\n" +
	"\x06GetApp\x12#.ai_studio_management.GetAppRequest\x1a$.ai_studio_management.GetAppResponseBDZBgithub.com/TykTechnologies/midsommar/v2/proto/ai_studio_managementb\x06proto3"

var (
	file_proto_ai_studio_management_proto_rawDescOnce sync.Once
	file_proto_ai_studio_management_proto_rawDescData []byte
)

func file_proto_ai_studio_management_proto_rawDescGZIP() []byte {
	file_proto_ai_studio_management_proto_rawDescOnce.Do(func() {
		file_proto_ai_studio_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_studio_management_proto_rawDesc), len(file_proto_ai_studio_management_proto_rawDesc)))
	})
	return file_proto_ai_studio_management_proto_rawDescData
}

var file_proto_ai_studio_management_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_ai_studio_management_proto_goTypes = []any{
	(*PluginContext)(nil),               // 0: ai_studio_management.PluginContext
	(*ListPluginsRequest)(nil),          // 1: ai_studio_management.ListPluginsRequest
	(*ListPluginsResponse)(nil),         // 2: ai_studio_management.ListPluginsResponse
	(*GetPluginRequest)(nil),            // 3: ai_studio_management.GetPluginRequest
	(*GetPluginResponse)(nil),           // 4: ai_studio_management.GetPluginResponse
	(*UpdatePluginConfigRequest)(nil),   // 5: ai_studio_management.UpdatePluginConfigRequest
	(*UpdatePluginConfigResponse)(nil),  // 6: ai_studio_management.UpdatePluginConfigResponse
	(*PluginInfo)(nil),                  // 7: ai_studio_management.PluginInfo
	(*ListLLMsRequest)(nil),             // 8: ai_studio_management.ListLLMsRequest
	(*ListLLMsResponse)(nil),            // 9: ai_studio_management.ListLLMsResponse
	(*GetLLMRequest)(nil),               // 10: ai_studio_management.GetLLMRequest
	(*GetLLMResponse)(nil),              // 11: ai_studio_management.GetLLMResponse
	(*GetLLMPluginsRequest)(nil),        // 12: ai_studio_management.GetLLMPluginsRequest
	(*GetLLMPluginsResponse)(nil),       // 13: ai_studio_management.GetLLMPluginsResponse
	(*LLMInfo)(nil),                     // 14: ai_studio_management.LLMInfo
	(*GetAnalyticsSummaryRequest)(nil),  // 15: ai_studio_management.GetAnalyticsSummaryRequest
	(*GetAnalyticsSummaryResponse)(nil), // 16: ai_studio_management.GetAnalyticsSummaryResponse
	(*GetUsageStatisticsRequest)(nil),   // 17: ai_studio_management.GetUsageStatisticsRequest
	(*GetUsageStatisticsResponse)(nil),  // 18: ai_studio_management.GetUsageStatisticsResponse
	(*GetCostAnalysisRequest)(nil),      // 19: ai_studio_management.GetCostAnalysisRequest
	(*GetCostAnalysisResponse)(nil),     // 20: ai_studio_management.GetCostAnalysisResponse
	(*TopEndpoint)(nil),                 // 21: ai_studio_management.TopEndpoint
	(*ModelUsage)(nil),                  // 22: ai_studio_management.ModelUsage
	(*UsageStatistic)(nil),              // 23: ai_studio_management.UsageStatistic
	(*CostBreakdown)(nil),               // 24: ai_studio_management.CostBreakdown
	(*ListAppsRequest)(nil),             // 25: ai_studio_management.ListAppsRequest
	(*ListAppsResponse)(nil),            // 26: ai_studio_management.ListAppsResponse
	(*GetAppRequest)(nil),               // 27: ai_studio_management.GetAppRequest
	(*GetAppResponse)(nil),              // 28: ai_studio_management.GetAppResponse
	(*AppInfo)(nil),                     // 29: ai_studio_management.AppInfo
	(*timestamppb.Timestamp)(nil),       // 30: google.protobuf.Timestamp
}
var file_proto_ai_studio_management_proto_depIdxs = []int32{
	0,  // 0: ai_studio_management.ListPluginsRequest.context:type_name -> ai_studio_management.PluginContext
	7,  // 1: ai_studio_management.ListPluginsResponse.plugins:type_name -> ai_studio_management.PluginInfo
	0,  // 2: ai_studio_management.GetPluginRequest.context:type_name -> ai_studio_management.PluginContext
	7,  // 3: ai_studio_management.GetPluginResponse.plugin:type_name -> ai_studio_management.PluginInfo
	0,  // 4: ai_studio_management.UpdatePluginConfigRequest.context:type_name -> ai_studio_management.PluginContext
	30, // 5: ai_studio_management.PluginInfo.created_at:type_name -> google.protobuf.Timestamp
	30, // 6: ai_studio_management.PluginInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: ai_studio_management.ListLLMsRequest.context:type_name -> ai_studio_management.PluginContext
	14, // 8: ai_studio_management.ListLLMsResponse.llms:type_name -> ai_studio_management.LLMInfo
	0,  // 9: ai_studio_management.GetLLMRequest.context:type_name -> ai_studio_management.PluginContext
	14, // 10: ai_studio_management.GetLLMResponse.llm:type_name -> ai_studio_management.LLMInfo
	0,  // 11: ai_studio_management.GetLLMPluginsRequest.context:type_name -> ai_studio_management.PluginContext
	7,  // 12: ai_studio_management.GetLLMPluginsResponse.plugins:type_name -> ai_studio_management.PluginInfo
	30, // 13: ai_studio_management.LLMInfo.created_at:type_name -> google.protobuf.Timestamp
	30, // 14: ai_studio_management.LLMInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 15: ai_studio_management.GetAnalyticsSummaryRequest.context:type_name -> ai_studio_management.PluginContext
	21, // 16: ai_studio_management.GetAnalyticsSummaryResponse.top_endpoints:type_name -> ai_studio_management.TopEndpoint
	22, // 17: ai_studio_management.GetAnalyticsSummaryResponse.model_usage:type_name -> ai_studio_management.ModelUsage
	0,  // 18: ai_studio_management.GetUsageStatisticsRequest.context:type_name -> ai_studio_management.PluginContext
	23, // 19: ai_studio_management.GetUsageStatisticsResponse.statistics:type_name -> ai_studio_management.UsageStatistic
	0,  // 20: ai_studio_management.GetCostAnalysisRequest.context:type_name -> ai_studio_management.PluginContext
	24, // 21: ai_studio_management.GetCostAnalysisResponse.breakdown:type_name -> ai_studio_management.CostBreakdown
	30, // 22: ai_studio_management.UsageStatistic.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 23: ai_studio_management.ListAppsRequest.context:type_name -> ai_studio_management.PluginContext
	29, // 24: ai_studio_management.ListAppsResponse.apps:type_name -> ai_studio_management.AppInfo
	0,  // 25: ai_studio_management.GetAppRequest.context:type_name -> ai_studio_management.PluginContext
	29, // 26: ai_studio_management.GetAppResponse.app:type_name -> ai_studio_management.AppInfo
	30, // 27: ai_studio_management.AppInfo.created_at:type_name -> google.protobuf.Timestamp
	30, // 28: ai_studio_management.AppInfo.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 29: ai_studio_management.AIStudioManagementService.ListPlugins:input_type -> ai_studio_management.ListPluginsRequest
	3,  // 30: ai_studio_management.AIStudioManagementService.GetPlugin:input_type -> ai_studio_management.GetPluginRequest
	5,  // 31: ai_studio_management.AIStudioManagementService.UpdatePluginConfig:input_type -> ai_studio_management.UpdatePluginConfigRequest
	8,  // 32: ai_studio_management.AIStudioManagementService.ListLLMs:input_type -> ai_studio_management.ListLLMsRequest
	10, // 33: ai_studio_management.AIStudioManagementService.GetLLM:input_type -> ai_studio_management.GetLLMRequest
	12, // 34: ai_studio_management.AIStudioManagementService.GetLLMPlugins:input_type -> ai_studio_management.GetLLMPluginsRequest
	15, // 35: ai_studio_management.AIStudioManagementService.GetAnalyticsSummary:input_type -> ai_studio_management.GetAnalyticsSummaryRequest
	17, // 36: ai_studio_management.AIStudioManagementService.GetUsageStatistics:input_type -> ai_studio_management.GetUsageStatisticsRequest
	19, // 37: ai_studio_management.AIStudioManagementService.GetCostAnalysis:input_type -> ai_studio_management.GetCostAnalysisRequest
	25, // 38: ai_studio_management.AIStudioManagementService.ListApps:input_type -> ai_studio_management.ListAppsRequest
	27, // 39: ai_studio_management.AIStudioManagementService.GetApp:input_type -> ai_studio_management.GetAppRequest
	2,  // 40: ai_studio_management.AIStudioManagementService.ListPlugins:output_type -> ai_studio_management.ListPluginsResponse
	4,  // 41: ai_studio_management.AIStudioManagementService.GetPlugin:output_type -> ai_studio_management.GetPluginResponse
	6,  // 42: ai_studio_management.AIStudioManagementService.UpdatePluginConfig:output_type -> ai_studio_management.UpdatePluginConfigResponse
	9,  // 43: ai_studio_management.AIStudioManagementService.ListLLMs:output_type -> ai_studio_management.ListLLMsResponse
	11, // 44: ai_studio_management.AIStudioManagementService.GetLLM:output_type -> ai_studio_management.GetLLMResponse
	13, // 45: ai_studio_management.AIStudioManagementService.GetLLMPlugins:output_type -> ai_studio_management.GetLLMPluginsResponse
	16, // 46: ai_studio_management.AIStudioManagementService.GetAnalyticsSummary:output_type -> ai_studio_management.GetAnalyticsSummaryResponse
	18, // 47: ai_studio_management.AIStudioManagementService.GetUsageStatistics:output_type -> ai_studio_management.GetUsageStatisticsResponse
	20, // 48: ai_studio_management.AIStudioManagementService.GetCostAnalysis:output_type -> ai_studio_management.GetCostAnalysisResponse
	26, // 49: ai_studio_management.AIStudioManagementService.ListApps:output_type -> ai_studio_management.ListAppsResponse
	28, // 50: ai_studio_management.AIStudioManagementService.GetApp:output_type -> ai_studio_management.GetAppResponse
	40, // [40:51] is the sub-list for method output_type
	29, // [29:40] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_proto_ai_studio_management_proto_init() }
func file_proto_ai_studio_management_proto_init() {
	if File_proto_ai_studio_management_proto != nil {
		return
	}
	file_proto_ai_studio_management_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_ai_studio_management_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_ai_studio_management_proto_msgTypes[14].OneofWrappers = []any{}
	file_proto_ai_studio_management_proto_msgTypes[15].OneofWrappers = []any{}
	file_proto_ai_studio_management_proto_msgTypes[19].OneofWrappers = []any{}
	file_proto_ai_studio_management_proto_msgTypes[25].OneofWrappers = []any{}
	file_proto_ai_studio_management_proto_msgTypes[29].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_studio_management_proto_rawDesc), len(file_proto_ai_studio_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_studio_management_proto_goTypes,
		DependencyIndexes: file_proto_ai_studio_management_proto_depIdxs,
		MessageInfos:      file_proto_ai_studio_management_proto_msgTypes,
	}.Build()
	File_proto_ai_studio_management_proto = out.File
	file_proto_ai_studio_management_proto_goTypes = nil
	file_proto_ai_studio_management_proto_depIdxs = nil
}
