networks:
  tyk-network:

services:
  midsommar:
    networks:
      - tyk-network
    image: tykio/tyk-ai-studio:v2.2.1
    volumes:
      - ../confs/midsommar-ce.env:/opt/tyk-ai-studio/.env
      - ./data/midsommar:/opt/tyk-ai-studio/data
      - ./data/cache/plugins:/opt/tyk-ai-studio/data/cache/plugins
    env_file:
      - ../confs/midsommar-ce.env
    ports:
      - 3000:8080
      - 9595:9090
    restart: always
  mgw:
    networks:
      - tyk-network
    image: tykio/tyk-microgateway:v2.2.1
    volumes:
      - ../confs/mgw-ce.env:/opt/tyk-microgateway/.env
      - ../confs/mgw-analytics.yaml:/opt/tyk-microgateway/mgw-analytics.yaml
      - ./data/mgw:/app/data
      - ./data/cache/plugins:/data/cache/plugins
    env_file:
    - ../required.env
    - ../confs/mgw-ce.env
    ports:
      - 9091:9091
    restart: always
    depends_on:
      midsommar:
        condition: service_started
