version: "3.8"
services:
  dev:
    platform: linux/${TARGETARCH:-amd64}
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/ui/admin-frontend/node_modules
      - ./midsommar.db:/app/midsommar.db # Bind mount SQLite database file
      - ./.env:/app/.env # Mount .env file
    ports:
      - "3000:3000" # Frontend
      - "8080:8080" # Backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
