// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: proto/plugin_events.proto

package plugin_events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishRequest is sent by a plugin to publish an event
type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// topic is the logical topic name (e.g., "cache.hit", "config.reload")
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// payload is the JSON-encoded event payload
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// direction controls event routing:
	// 0 = DirLocal (stays on local bus)
	// 1 = DirUp (edge to control)
	// 2 = DirDown (control to edge)
	Direction int32 `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`
	// plugin_id identifies the plugin publishing the event (for origin tracking)
	PluginId      string `protobuf:"bytes,4,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_plugin_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_events_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishRequest) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *PublishRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

// PublishResponse is returned after publishing an event
type PublishResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the event was published successfully
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// error_message contains the error description if success is false
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// event_id is the generated UUID for the published event
	EventId       string `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_plugin_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_events_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PublishResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// SubscribeRequest is sent by a plugin to subscribe to events
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// topic is the topic to subscribe to. If empty and subscribe_all is false,
	// no events will be received.
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// subscribe_all subscribes to all events regardless of topic
	SubscribeAll bool `protobuf:"varint,2,opt,name=subscribe_all,json=subscribeAll,proto3" json:"subscribe_all,omitempty"`
	// plugin_id identifies the subscribing plugin (for tracking/logging)
	PluginId      string `protobuf:"bytes,3,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_plugin_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_events_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetSubscribeAll() bool {
	if x != nil {
		return x.SubscribeAll
	}
	return false
}

func (x *SubscribeRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

// EventMessage is streamed to plugins for matching events
type EventMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique event identifier (UUID)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// topic is the logical topic name
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// origin is the node/plugin that created the event
	Origin string `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	// direction indicates the original routing direction (informational)
	// When received via Subscribe, events are always effectively "local"
	Direction int32 `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
	// payload is the JSON-encoded event payload
	Payload       []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_proto_plugin_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_proto_plugin_events_proto_rawDescGZIP(), []int{3}
}

func (x *EventMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *EventMessage) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *EventMessage) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *EventMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// UnsubscribeRequest is sent to remove a subscription
type UnsubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subscription_id is the ID returned from Subscribe (client-generated)
	SubscriptionId string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_proto_plugin_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_events_proto_rawDescGZIP(), []int{4}
}

func (x *UnsubscribeRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// UnsubscribeResponse is returned after unsubscribing
type UnsubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the unsubscribe was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// error_message contains the error description if success is false
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_proto_plugin_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_events_proto_rawDescGZIP(), []int{5}
}

func (x *UnsubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnsubscribeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_plugin_events_proto protoreflect.FileDescriptor

const file_proto_plugin_events_proto_rawDesc = "" +
	"\n" +
	"\x19proto/plugin_events.proto\x12\rplugin_events\"{\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\x05R\tdirection\x12\x1b\n" +
	"\tplugin_id\x18\x04 \x01(\tR\bpluginId\"k\n" +
	"\x0fPublishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\"j\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12#\n" +
	"\rsubscribe_all\x18\x02 \x01(\bR\fsubscribeAll\x12\x1b\n" +
	"\tplugin_id\x18\x03 \x01(\tR\bpluginId\"\x84\x01\n" +
	"\fEventMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\x05R\tdirection\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"=\n" +
	"\x12UnsubscribeRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"T\n" +
	"\x13UnsubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\x81\x02\n" +
	"\x12PluginEventService\x12H\n" +
	"\aPublish\x12\x1d.plugin_events.PublishRequest\x1a\x1e.plugin_events.PublishResponse\x12K\n" +
	"\tSubscribe\x12\x1f.plugin_events.SubscribeRequest\x1a\x1b.plugin_events.EventMessage0\x01\x12T\n" +
	"\vUnsubscribe\x12!.plugin_events.UnsubscribeRequest\x1a\".plugin_events.UnsubscribeResponseB=Z;github.com/TykTechnologies/midsommar/v2/proto/plugin_eventsb\x06proto3"

var (
	file_proto_plugin_events_proto_rawDescOnce sync.Once
	file_proto_plugin_events_proto_rawDescData []byte
)

func file_proto_plugin_events_proto_rawDescGZIP() []byte {
	file_proto_plugin_events_proto_rawDescOnce.Do(func() {
		file_proto_plugin_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_events_proto_rawDesc), len(file_proto_plugin_events_proto_rawDesc)))
	})
	return file_proto_plugin_events_proto_rawDescData
}

var file_proto_plugin_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_plugin_events_proto_goTypes = []any{
	(*PublishRequest)(nil),      // 0: plugin_events.PublishRequest
	(*PublishResponse)(nil),     // 1: plugin_events.PublishResponse
	(*SubscribeRequest)(nil),    // 2: plugin_events.SubscribeRequest
	(*EventMessage)(nil),        // 3: plugin_events.EventMessage
	(*UnsubscribeRequest)(nil),  // 4: plugin_events.UnsubscribeRequest
	(*UnsubscribeResponse)(nil), // 5: plugin_events.UnsubscribeResponse
}
var file_proto_plugin_events_proto_depIdxs = []int32{
	0, // 0: plugin_events.PluginEventService.Publish:input_type -> plugin_events.PublishRequest
	2, // 1: plugin_events.PluginEventService.Subscribe:input_type -> plugin_events.SubscribeRequest
	4, // 2: plugin_events.PluginEventService.Unsubscribe:input_type -> plugin_events.UnsubscribeRequest
	1, // 3: plugin_events.PluginEventService.Publish:output_type -> plugin_events.PublishResponse
	3, // 4: plugin_events.PluginEventService.Subscribe:output_type -> plugin_events.EventMessage
	5, // 5: plugin_events.PluginEventService.Unsubscribe:output_type -> plugin_events.UnsubscribeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_plugin_events_proto_init() }
func file_proto_plugin_events_proto_init() {
	if File_proto_plugin_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_events_proto_rawDesc), len(file_proto_plugin_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugin_events_proto_goTypes,
		DependencyIndexes: file_proto_plugin_events_proto_depIdxs,
		MessageInfos:      file_proto_plugin_events_proto_msgTypes,
	}.Build()
	File_proto_plugin_events_proto = out.File
	file_proto_plugin_events_proto_goTypes = nil
	file_proto_plugin_events_proto_depIdxs = nil
}
