apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "midsommar.fullname" . }}-config
data:
  .env: |
    ALLOW_REGISTRATIONS={{ .Values.config.allowRegistrations }}
    ADMIN_EMAIL={{ .Values.config.adminEmail }}
    SITE_URL={{ .Values.config.siteUrl }}
    FROM_EMAIL={{ .Values.config.fromEmail }}
    DEVMODE={{ .Values.config.devMode }}
    DATABASE_TYPE={{ .Values.config.databaseType }}
