apiVersion: v1
kind: Secret
metadata:
  name: {{ include "midsommar.fullname" . }}-secrets
type: Opaque
data:
  {{- if .Values.config.smtpPass }}
  smtp-password: {{ .Values.config.smtpPass | b64enc }}
  {{- end }}
