apiVersion: v1
kind: Secret
metadata:
  name: {{ include "midsommar.fullname" . }}-secrets
type: Opaque
stringData:
  {{- if .Values.config.smtpPass }}
  SMTP_PASS: {{ .Values.config.smtpPass | quote }}
  {{- end }}
  {{- if .Values.config.tykAiSecretKey }}
  TYK_AI_SECRET_KEY: {{ .Values.config.tykAiSecretKey | quote }}
  {{- end }}
  {{- if .Values.config.tykAiLicense }}
  TYK_AI_LICENSE: {{ .Values.config.tykAiLicense | quote }}
  {{- end }}
  {{- if .Values.config.grpcAuthToken }}
  GRPC_AUTH_TOKEN: {{ .Values.config.grpcAuthToken | quote }}
  {{- end }}
  {{- if .Values.config.microgatewayEncryptionKey }}
  MICROGATEWAY_ENCRYPTION_KEY: {{ .Values.config.microgatewayEncryptionKey | quote }}
  {{- end }}
