enabled: false # Disabled by default

image:
  repository: midsommar/transformer-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

# Deployment configuration
replicaCount: 1
