# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install gunicorn

# Make port 8000 available for the app
EXPOSE 8000

# Run the server using Gunicorn when the container launches
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "lc_server:app"]
