// Code generated by aliasgen when the package moved; DO NOT EDIT.

// Package microgateway_management is the old import path of the gateway
// management gRPC API.
//
// Deprecated: import github.com/TykTechnologies/midsommar/v2/proto/microgateway_management.
// The generated code moved into the root module (proto/microgateway_management.proto)
// so that pkg/studio can be imported without the microgateway module. This
// package only forwards to it and registers nothing, so the proto types are
// registered once.
package microgateway_management

import (
	moved "github.com/TykTechnologies/midsommar/v2/proto/microgateway_management"
	"google.golang.org/grpc"
)

type (
	PluginContext                                    = moved.PluginContext
	ListLLMsRequest                                  = moved.ListLLMsRequest
	ListLLMsResponse                                 = moved.ListLLMsResponse
	GetLLMRequest                                    = moved.GetLLMRequest
	GetLLMResponse                                   = moved.GetLLMResponse
	LLMInfo                                          = moved.LLMInfo
	ListAppsRequest                                  = moved.ListAppsRequest
	ListAppsResponse                                 = moved.ListAppsResponse
	GetAppRequest                                    = moved.GetAppRequest
	GetAppResponse                                   = moved.GetAppResponse
	AppInfo                                          = moved.AppInfo
	StoreAppRequest                                  = moved.StoreAppRequest
	StoreAppResponse                                 = moved.StoreAppResponse
	GetBudgetStatusRequest                           = moved.GetBudgetStatusRequest
	GetBudgetStatusResponse                          = moved.GetBudgetStatusResponse
	ListModelPricesRequest                           = moved.ListModelPricesRequest
	ListModelPricesResponse                          = moved.ListModelPricesResponse
	GetModelPriceRequest                             = moved.GetModelPriceRequest
	GetModelPriceResponse                            = moved.GetModelPriceResponse
	ModelPriceInfo                                   = moved.ModelPriceInfo
	ValidateCredentialRequest                        = moved.ValidateCredentialRequest
	ValidateCredentialResponse                       = moved.ValidateCredentialResponse
	WritePluginKVRequest                             = moved.WritePluginKVRequest
	WritePluginKVResponse                            = moved.WritePluginKVResponse
	ReadPluginKVRequest                              = moved.ReadPluginKVRequest
	ReadPluginKVResponse                             = moved.ReadPluginKVResponse
	DeletePluginKVRequest                            = moved.DeletePluginKVRequest
	DeletePluginKVResponse                           = moved.DeletePluginKVResponse
	QueueControlPayloadRequest                       = moved.QueueControlPayloadRequest
	QueueControlPayloadResponse                      = moved.QueueControlPayloadResponse
	GetLicenseInfoRequest                            = moved.GetLicenseInfoRequest
	GetLicenseInfoResponse                           = moved.GetLicenseInfoResponse
	MicrogatewayManagementServiceClient              = moved.MicrogatewayManagementServiceClient
	MicrogatewayManagementServiceServer              = moved.MicrogatewayManagementServiceServer
	UnimplementedMicrogatewayManagementServiceServer = moved.UnimplementedMicrogatewayManagementServiceServer
	UnsafeMicrogatewayManagementServiceServer        = moved.UnsafeMicrogatewayManagementServiceServer
)

const (
	MicrogatewayManagementService_ListLLMs_FullMethodName            = moved.MicrogatewayManagementService_ListLLMs_FullMethodName
	MicrogatewayManagementService_GetLLM_FullMethodName              = moved.MicrogatewayManagementService_GetLLM_FullMethodName
	MicrogatewayManagementService_ListApps_FullMethodName            = moved.MicrogatewayManagementService_ListApps_FullMethodName
	MicrogatewayManagementService_GetApp_FullMethodName              = moved.MicrogatewayManagementService_GetApp_FullMethodName
	MicrogatewayManagementService_StoreApp_FullMethodName            = moved.MicrogatewayManagementService_StoreApp_FullMethodName
	MicrogatewayManagementService_GetBudgetStatus_FullMethodName     = moved.MicrogatewayManagementService_GetBudgetStatus_FullMethodName
	MicrogatewayManagementService_ListModelPrices_FullMethodName     = moved.MicrogatewayManagementService_ListModelPrices_FullMethodName
	MicrogatewayManagementService_GetModelPrice_FullMethodName       = moved.MicrogatewayManagementService_GetModelPrice_FullMethodName
	MicrogatewayManagementService_ValidateCredential_FullMethodName  = moved.MicrogatewayManagementService_ValidateCredential_FullMethodName
	MicrogatewayManagementService_WritePluginKV_FullMethodName       = moved.MicrogatewayManagementService_WritePluginKV_FullMethodName
	MicrogatewayManagementService_ReadPluginKV_FullMethodName        = moved.MicrogatewayManagementService_ReadPluginKV_FullMethodName
	MicrogatewayManagementService_DeletePluginKV_FullMethodName      = moved.MicrogatewayManagementService_DeletePluginKV_FullMethodName
	MicrogatewayManagementService_QueueControlPayload_FullMethodName = moved.MicrogatewayManagementService_QueueControlPayload_FullMethodName
	MicrogatewayManagementService_GetLicenseInfo_FullMethodName      = moved.MicrogatewayManagementService_GetLicenseInfo_FullMethodName
)

var (
	File_proto_microgateway_management_proto  = moved.File_proto_microgateway_management_proto
	MicrogatewayManagementService_ServiceDesc = moved.MicrogatewayManagementService_ServiceDesc
)

// NewMicrogatewayManagementServiceClient forwards to microgateway_management.NewMicrogatewayManagementServiceClient.
func NewMicrogatewayManagementServiceClient(cc grpc.ClientConnInterface) MicrogatewayManagementServiceClient {
	return moved.NewMicrogatewayManagementServiceClient(cc)
}

// RegisterMicrogatewayManagementServiceServer forwards to microgateway_management.RegisterMicrogatewayManagementServiceServer.
func RegisterMicrogatewayManagementServiceServer(s grpc.ServiceRegistrar, srv MicrogatewayManagementServiceServer) {
	moved.RegisterMicrogatewayManagementServiceServer(s, srv)
}
