// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: microgateway/proto/microgateway_management/service.proto

package microgateway_management

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MicrogatewayManagementService_ListLLMs_FullMethodName           = "/microgateway_management.MicrogatewayManagementService/ListLLMs"
	MicrogatewayManagementService_GetLLM_FullMethodName             = "/microgateway_management.MicrogatewayManagementService/GetLLM"
	MicrogatewayManagementService_ListApps_FullMethodName           = "/microgateway_management.MicrogatewayManagementService/ListApps"
	MicrogatewayManagementService_GetApp_FullMethodName             = "/microgateway_management.MicrogatewayManagementService/GetApp"
	MicrogatewayManagementService_GetBudgetStatus_FullMethodName    = "/microgateway_management.MicrogatewayManagementService/GetBudgetStatus"
	MicrogatewayManagementService_ListModelPrices_FullMethodName    = "/microgateway_management.MicrogatewayManagementService/ListModelPrices"
	MicrogatewayManagementService_GetModelPrice_FullMethodName      = "/microgateway_management.MicrogatewayManagementService/GetModelPrice"
	MicrogatewayManagementService_ValidateCredential_FullMethodName = "/microgateway_management.MicrogatewayManagementService/ValidateCredential"
	MicrogatewayManagementService_WritePluginKV_FullMethodName      = "/microgateway_management.MicrogatewayManagementService/WritePluginKV"
	MicrogatewayManagementService_ReadPluginKV_FullMethodName       = "/microgateway_management.MicrogatewayManagementService/ReadPluginKV"
	MicrogatewayManagementService_DeletePluginKV_FullMethodName     = "/microgateway_management.MicrogatewayManagementService/DeletePluginKV"
)

// MicrogatewayManagementServiceClient is the client API for MicrogatewayManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MicrogatewayManagementService provides microgateway plugins with access to core management operations
// Plugins must be authorized and have appropriate scopes to access these services
type MicrogatewayManagementServiceClient interface {
	// LLM Management Operations (Read-Only)
	ListLLMs(ctx context.Context, in *ListLLMsRequest, opts ...grpc.CallOption) (*ListLLMsResponse, error)
	GetLLM(ctx context.Context, in *GetLLMRequest, opts ...grpc.CallOption) (*GetLLMResponse, error)
	// App Management Operations (Read-Only)
	ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error)
	GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*GetAppResponse, error)
	// Budget Operations (Read-Only)
	GetBudgetStatus(ctx context.Context, in *GetBudgetStatusRequest, opts ...grpc.CallOption) (*GetBudgetStatusResponse, error)
	// Model Price Management Operations (Read-Only)
	ListModelPrices(ctx context.Context, in *ListModelPricesRequest, opts ...grpc.CallOption) (*ListModelPricesResponse, error)
	GetModelPrice(ctx context.Context, in *GetModelPriceRequest, opts ...grpc.CallOption) (*GetModelPriceResponse, error)
	// Credential Operations (Read-Only - for plugin auth use cases)
	ValidateCredential(ctx context.Context, in *ValidateCredentialRequest, opts ...grpc.CallOption) (*ValidateCredentialResponse, error)
	// Plugin Key-Value Storage Operations
	WritePluginKV(ctx context.Context, in *WritePluginKVRequest, opts ...grpc.CallOption) (*WritePluginKVResponse, error)
	ReadPluginKV(ctx context.Context, in *ReadPluginKVRequest, opts ...grpc.CallOption) (*ReadPluginKVResponse, error)
	DeletePluginKV(ctx context.Context, in *DeletePluginKVRequest, opts ...grpc.CallOption) (*DeletePluginKVResponse, error)
}

type microgatewayManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMicrogatewayManagementServiceClient(cc grpc.ClientConnInterface) MicrogatewayManagementServiceClient {
	return &microgatewayManagementServiceClient{cc}
}

func (c *microgatewayManagementServiceClient) ListLLMs(ctx context.Context, in *ListLLMsRequest, opts ...grpc.CallOption) (*ListLLMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLLMsResponse)
	err := c.cc.Invoke(ctx, MicrogatewayManagementService_ListLLMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microgatewayManagementServiceClient) GetLLM(ctx context.Context, in *GetLLMRequest, opts ...grpc.CallOption) (*GetLLMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLLMResponse)
	err := c.cc.Invoke(ctx, MicrogatewayManagementService_GetLLM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microgatewayManagementServiceClient) ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppsResponse)
	err := c.cc.Invoke(ctx, MicrogatewayManagementService_ListApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microgatewayManagementServiceClient) GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*GetAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppResponse)
	err := c.cc.Invoke(ctx, MicrogatewayManagementService_GetApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microgatewayManagementServiceClient) GetBudgetStatus(ctx context.Context, in *GetBudgetStatusRequest, opts ...grpc.CallOption) (*GetBudgetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBudgetStatusResponse)
	err := c.cc.Invoke(ctx, MicrogatewayManagementService_GetBudgetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microgatewayManagementServiceClient) ListModelPrices(ctx context.Context, in *ListModelPricesRequest, opts ...grpc.CallOption) (*ListModelPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelPricesResponse)
	err := c.cc.Invoke(ctx, MicrogatewayManagementService_ListModelPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microgatewayManagementServiceClient) GetModelPrice(ctx context.Context, in *GetModelPriceRequest, opts ...grpc.CallOption) (*GetModelPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelPriceResponse)
	err := c.cc.Invoke(ctx, MicrogatewayManagementService_GetModelPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microgatewayManagementServiceClient) ValidateCredential(ctx context.Context, in *ValidateCredentialRequest, opts ...grpc.CallOption) (*ValidateCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCredentialResponse)
	err := c.cc.Invoke(ctx, MicrogatewayManagementService_ValidateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microgatewayManagementServiceClient) WritePluginKV(ctx context.Context, in *WritePluginKVRequest, opts ...grpc.CallOption) (*WritePluginKVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WritePluginKVResponse)
	err := c.cc.Invoke(ctx, MicrogatewayManagementService_WritePluginKV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microgatewayManagementServiceClient) ReadPluginKV(ctx context.Context, in *ReadPluginKVRequest, opts ...grpc.CallOption) (*ReadPluginKVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadPluginKVResponse)
	err := c.cc.Invoke(ctx, MicrogatewayManagementService_ReadPluginKV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microgatewayManagementServiceClient) DeletePluginKV(ctx context.Context, in *DeletePluginKVRequest, opts ...grpc.CallOption) (*DeletePluginKVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePluginKVResponse)
	err := c.cc.Invoke(ctx, MicrogatewayManagementService_DeletePluginKV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MicrogatewayManagementServiceServer is the server API for MicrogatewayManagementService service.
// All implementations must embed UnimplementedMicrogatewayManagementServiceServer
// for forward compatibility.
//
// MicrogatewayManagementService provides microgateway plugins with access to core management operations
// Plugins must be authorized and have appropriate scopes to access these services
type MicrogatewayManagementServiceServer interface {
	// LLM Management Operations (Read-Only)
	ListLLMs(context.Context, *ListLLMsRequest) (*ListLLMsResponse, error)
	GetLLM(context.Context, *GetLLMRequest) (*GetLLMResponse, error)
	// App Management Operations (Read-Only)
	ListApps(context.Context, *ListAppsRequest) (*ListAppsResponse, error)
	GetApp(context.Context, *GetAppRequest) (*GetAppResponse, error)
	// Budget Operations (Read-Only)
	GetBudgetStatus(context.Context, *GetBudgetStatusRequest) (*GetBudgetStatusResponse, error)
	// Model Price Management Operations (Read-Only)
	ListModelPrices(context.Context, *ListModelPricesRequest) (*ListModelPricesResponse, error)
	GetModelPrice(context.Context, *GetModelPriceRequest) (*GetModelPriceResponse, error)
	// Credential Operations (Read-Only - for plugin auth use cases)
	ValidateCredential(context.Context, *ValidateCredentialRequest) (*ValidateCredentialResponse, error)
	// Plugin Key-Value Storage Operations
	WritePluginKV(context.Context, *WritePluginKVRequest) (*WritePluginKVResponse, error)
	ReadPluginKV(context.Context, *ReadPluginKVRequest) (*ReadPluginKVResponse, error)
	DeletePluginKV(context.Context, *DeletePluginKVRequest) (*DeletePluginKVResponse, error)
	mustEmbedUnimplementedMicrogatewayManagementServiceServer()
}

// UnimplementedMicrogatewayManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMicrogatewayManagementServiceServer struct{}

func (UnimplementedMicrogatewayManagementServiceServer) ListLLMs(context.Context, *ListLLMsRequest) (*ListLLMsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLLMs not implemented")
}
func (UnimplementedMicrogatewayManagementServiceServer) GetLLM(context.Context, *GetLLMRequest) (*GetLLMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLLM not implemented")
}
func (UnimplementedMicrogatewayManagementServiceServer) ListApps(context.Context, *ListAppsRequest) (*ListAppsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApps not implemented")
}
func (UnimplementedMicrogatewayManagementServiceServer) GetApp(context.Context, *GetAppRequest) (*GetAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApp not implemented")
}
func (UnimplementedMicrogatewayManagementServiceServer) GetBudgetStatus(context.Context, *GetBudgetStatusRequest) (*GetBudgetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBudgetStatus not implemented")
}
func (UnimplementedMicrogatewayManagementServiceServer) ListModelPrices(context.Context, *ListModelPricesRequest) (*ListModelPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModelPrices not implemented")
}
func (UnimplementedMicrogatewayManagementServiceServer) GetModelPrice(context.Context, *GetModelPriceRequest) (*GetModelPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelPrice not implemented")
}
func (UnimplementedMicrogatewayManagementServiceServer) ValidateCredential(context.Context, *ValidateCredentialRequest) (*ValidateCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateCredential not implemented")
}
func (UnimplementedMicrogatewayManagementServiceServer) WritePluginKV(context.Context, *WritePluginKVRequest) (*WritePluginKVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WritePluginKV not implemented")
}
func (UnimplementedMicrogatewayManagementServiceServer) ReadPluginKV(context.Context, *ReadPluginKVRequest) (*ReadPluginKVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPluginKV not implemented")
}
func (UnimplementedMicrogatewayManagementServiceServer) DeletePluginKV(context.Context, *DeletePluginKVRequest) (*DeletePluginKVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePluginKV not implemented")
}
func (UnimplementedMicrogatewayManagementServiceServer) mustEmbedUnimplementedMicrogatewayManagementServiceServer() {
}
func (UnimplementedMicrogatewayManagementServiceServer) testEmbeddedByValue() {}

// UnsafeMicrogatewayManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MicrogatewayManagementServiceServer will
// result in compilation errors.
type UnsafeMicrogatewayManagementServiceServer interface {
	mustEmbedUnimplementedMicrogatewayManagementServiceServer()
}

func RegisterMicrogatewayManagementServiceServer(s grpc.ServiceRegistrar, srv MicrogatewayManagementServiceServer) {
	// If the following call pancis, it indicates UnimplementedMicrogatewayManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MicrogatewayManagementService_ServiceDesc, srv)
}

func _MicrogatewayManagementService_ListLLMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLLMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicrogatewayManagementServiceServer).ListLLMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicrogatewayManagementService_ListLLMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicrogatewayManagementServiceServer).ListLLMs(ctx, req.(*ListLLMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicrogatewayManagementService_GetLLM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLLMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicrogatewayManagementServiceServer).GetLLM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicrogatewayManagementService_GetLLM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicrogatewayManagementServiceServer).GetLLM(ctx, req.(*GetLLMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicrogatewayManagementService_ListApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicrogatewayManagementServiceServer).ListApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicrogatewayManagementService_ListApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicrogatewayManagementServiceServer).ListApps(ctx, req.(*ListAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicrogatewayManagementService_GetApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicrogatewayManagementServiceServer).GetApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicrogatewayManagementService_GetApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicrogatewayManagementServiceServer).GetApp(ctx, req.(*GetAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicrogatewayManagementService_GetBudgetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicrogatewayManagementServiceServer).GetBudgetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicrogatewayManagementService_GetBudgetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicrogatewayManagementServiceServer).GetBudgetStatus(ctx, req.(*GetBudgetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicrogatewayManagementService_ListModelPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicrogatewayManagementServiceServer).ListModelPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicrogatewayManagementService_ListModelPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicrogatewayManagementServiceServer).ListModelPrices(ctx, req.(*ListModelPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicrogatewayManagementService_GetModelPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicrogatewayManagementServiceServer).GetModelPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicrogatewayManagementService_GetModelPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicrogatewayManagementServiceServer).GetModelPrice(ctx, req.(*GetModelPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicrogatewayManagementService_ValidateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicrogatewayManagementServiceServer).ValidateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicrogatewayManagementService_ValidateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicrogatewayManagementServiceServer).ValidateCredential(ctx, req.(*ValidateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicrogatewayManagementService_WritePluginKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WritePluginKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicrogatewayManagementServiceServer).WritePluginKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicrogatewayManagementService_WritePluginKV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicrogatewayManagementServiceServer).WritePluginKV(ctx, req.(*WritePluginKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicrogatewayManagementService_ReadPluginKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPluginKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicrogatewayManagementServiceServer).ReadPluginKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicrogatewayManagementService_ReadPluginKV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicrogatewayManagementServiceServer).ReadPluginKV(ctx, req.(*ReadPluginKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MicrogatewayManagementService_DeletePluginKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePluginKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicrogatewayManagementServiceServer).DeletePluginKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MicrogatewayManagementService_DeletePluginKV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicrogatewayManagementServiceServer).DeletePluginKV(ctx, req.(*DeletePluginKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MicrogatewayManagementService_ServiceDesc is the grpc.ServiceDesc for MicrogatewayManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MicrogatewayManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microgateway_management.MicrogatewayManagementService",
	HandlerType: (*MicrogatewayManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLLMs",
			Handler:    _MicrogatewayManagementService_ListLLMs_Handler,
		},
		{
			MethodName: "GetLLM",
			Handler:    _MicrogatewayManagementService_GetLLM_Handler,
		},
		{
			MethodName: "ListApps",
			Handler:    _MicrogatewayManagementService_ListApps_Handler,
		},
		{
			MethodName: "GetApp",
			Handler:    _MicrogatewayManagementService_GetApp_Handler,
		},
		{
			MethodName: "GetBudgetStatus",
			Handler:    _MicrogatewayManagementService_GetBudgetStatus_Handler,
		},
		{
			MethodName: "ListModelPrices",
			Handler:    _MicrogatewayManagementService_ListModelPrices_Handler,
		},
		{
			MethodName: "GetModelPrice",
			Handler:    _MicrogatewayManagementService_GetModelPrice_Handler,
		},
		{
			MethodName: "ValidateCredential",
			Handler:    _MicrogatewayManagementService_ValidateCredential_Handler,
		},
		{
			MethodName: "WritePluginKV",
			Handler:    _MicrogatewayManagementService_WritePluginKV_Handler,
		},
		{
			MethodName: "ReadPluginKV",
			Handler:    _MicrogatewayManagementService_ReadPluginKV_Handler,
		},
		{
			MethodName: "DeletePluginKV",
			Handler:    _MicrogatewayManagementService_DeletePluginKV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microgateway/proto/microgateway_management/service.proto",
}
