// Code generated by aliasgen when the package moved; DO NOT EDIT.

// Package interfaces is the old import path of the gateway plugin interfaces.
//
// Deprecated: import github.com/TykTechnologies/midsommar/v2/pkg/gatewayplugin/interfaces.
// The package moved into the root module so that pkg/studio can be imported
// without the microgateway module; this path only forwards to it.
package interfaces

import (
	moved "github.com/TykTechnologies/midsommar/v2/pkg/gatewayplugin/interfaces"
)

type (
	AuthRequest            = moved.AuthRequest
	AuthResponse           = moved.AuthResponse
	AuthPlugin             = moved.AuthPlugin
	HookType               = moved.HookType
	BasePlugin             = moved.BasePlugin
	ConfigSchemaProvider   = moved.ConfigSchemaProvider
	PluginContext          = moved.PluginContext
	PluginRequest          = moved.PluginRequest
	PluginResponse         = moved.PluginResponse
	DataCollectionPlugin   = moved.DataCollectionPlugin
	ProxyLogData           = moved.ProxyLogData
	AnalyticsData          = moved.AnalyticsData
	BudgetUsageData        = moved.BudgetUsageData
	DataCollectionResponse = moved.DataCollectionResponse
	DataCollectionHookType = moved.DataCollectionHookType
	EnrichedRequest        = moved.EnrichedRequest
	PostAuthPlugin         = moved.PostAuthPlugin
	PreAuthPlugin          = moved.PreAuthPlugin
	ResponseData           = moved.ResponseData
	HeadersRequest         = moved.HeadersRequest
	HeadersResponse        = moved.HeadersResponse
	ResponseWriteRequest   = moved.ResponseWriteRequest
	ResponseWriteResponse  = moved.ResponseWriteResponse
	ResponsePlugin         = moved.ResponsePlugin
)

const (
	HookTypePreAuth        = moved.HookTypePreAuth
	HookTypeAuth           = moved.HookTypeAuth
	HookTypePostAuth       = moved.HookTypePostAuth
	HookTypeOnResponse     = moved.HookTypeOnResponse
	HookTypeDataCollection = moved.HookTypeDataCollection
	HookTypeCustomEndpoint = moved.HookTypeCustomEndpoint
	ProxyLogHook           = moved.ProxyLogHook
	AnalyticsHook          = moved.AnalyticsHook
	BudgetHook             = moved.BudgetHook
)

// IsSupportedGatewayHookType forwards to interfaces.IsSupportedGatewayHookType.
func IsSupportedGatewayHookType(hookType string) bool {
	return moved.IsSupportedGatewayHookType(hookType)
}

// IsValidDataCollectionHookType forwards to interfaces.IsValidDataCollectionHookType.
func IsValidDataCollectionHookType(hookType string) bool {
	return moved.IsValidDataCollectionHookType(hookType)
}
