version: "3"
services:
  midsommar:
    image: tykio/midsommar:latest
    volumes:
      - ./confs/.env:/app/.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - DATABASE_TYPE=postgres
    depends_on:
      - postgres
    ports:
      - 8080:8080
      - 9090:9090

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
