// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/config_sync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigurationSyncService_RegisterEdge_FullMethodName         = "/microgateway.ConfigurationSyncService/RegisterEdge"
	ConfigurationSyncService_GetFullConfiguration_FullMethodName = "/microgateway.ConfigurationSyncService/GetFullConfiguration"
	ConfigurationSyncService_SubscribeToChanges_FullMethodName   = "/microgateway.ConfigurationSyncService/SubscribeToChanges"
	ConfigurationSyncService_SendHeartbeat_FullMethodName        = "/microgateway.ConfigurationSyncService/SendHeartbeat"
	ConfigurationSyncService_UnregisterEdge_FullMethodName       = "/microgateway.ConfigurationSyncService/UnregisterEdge"
	ConfigurationSyncService_ValidateToken_FullMethodName        = "/microgateway.ConfigurationSyncService/ValidateToken"
	ConfigurationSyncService_SendAnalyticsPulse_FullMethodName   = "/microgateway.ConfigurationSyncService/SendAnalyticsPulse"
)

// ConfigurationSyncServiceClient is the client API for ConfigurationSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigurationSyncService defines the gRPC service for hub-and-spoke configuration synchronization
type ConfigurationSyncServiceClient interface {
	// RegisterEdge registers an edge instance with the control instance
	RegisterEdge(ctx context.Context, in *EdgeRegistrationRequest, opts ...grpc.CallOption) (*EdgeRegistrationResponse, error)
	// GetFullConfiguration retrieves a complete configuration snapshot for an edge
	GetFullConfiguration(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*ConfigurationSnapshot, error)
	// SubscribeToChanges establishes a bidirectional stream for real-time configuration updates
	SubscribeToChanges(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EdgeMessage, ControlMessage], error)
	// SendHeartbeat sends periodic health status updates
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// UnregisterEdge unregisters an edge instance
	UnregisterEdge(ctx context.Context, in *EdgeUnregistrationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ValidateToken validates an API token on-demand (NEW)
	ValidateToken(ctx context.Context, in *TokenValidationRequest, opts ...grpc.CallOption) (*TokenValidationResponse, error)
	// SendAnalyticsPulse sends batched analytics data from edge to control (NEW)
	SendAnalyticsPulse(ctx context.Context, in *AnalyticsPulse, opts ...grpc.CallOption) (*AnalyticsPulseResponse, error)
}

type configurationSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigurationSyncServiceClient(cc grpc.ClientConnInterface) ConfigurationSyncServiceClient {
	return &configurationSyncServiceClient{cc}
}

func (c *configurationSyncServiceClient) RegisterEdge(ctx context.Context, in *EdgeRegistrationRequest, opts ...grpc.CallOption) (*EdgeRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EdgeRegistrationResponse)
	err := c.cc.Invoke(ctx, ConfigurationSyncService_RegisterEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationSyncServiceClient) GetFullConfiguration(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*ConfigurationSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigurationSnapshot)
	err := c.cc.Invoke(ctx, ConfigurationSyncService_GetFullConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationSyncServiceClient) SubscribeToChanges(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EdgeMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigurationSyncService_ServiceDesc.Streams[0], ConfigurationSyncService_SubscribeToChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EdgeMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigurationSyncService_SubscribeToChangesClient = grpc.BidiStreamingClient[EdgeMessage, ControlMessage]

func (c *configurationSyncServiceClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ConfigurationSyncService_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationSyncServiceClient) UnregisterEdge(ctx context.Context, in *EdgeUnregistrationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConfigurationSyncService_UnregisterEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationSyncServiceClient) ValidateToken(ctx context.Context, in *TokenValidationRequest, opts ...grpc.CallOption) (*TokenValidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenValidationResponse)
	err := c.cc.Invoke(ctx, ConfigurationSyncService_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationSyncServiceClient) SendAnalyticsPulse(ctx context.Context, in *AnalyticsPulse, opts ...grpc.CallOption) (*AnalyticsPulseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyticsPulseResponse)
	err := c.cc.Invoke(ctx, ConfigurationSyncService_SendAnalyticsPulse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigurationSyncServiceServer is the server API for ConfigurationSyncService service.
// All implementations must embed UnimplementedConfigurationSyncServiceServer
// for forward compatibility.
//
// ConfigurationSyncService defines the gRPC service for hub-and-spoke configuration synchronization
type ConfigurationSyncServiceServer interface {
	// RegisterEdge registers an edge instance with the control instance
	RegisterEdge(context.Context, *EdgeRegistrationRequest) (*EdgeRegistrationResponse, error)
	// GetFullConfiguration retrieves a complete configuration snapshot for an edge
	GetFullConfiguration(context.Context, *ConfigurationRequest) (*ConfigurationSnapshot, error)
	// SubscribeToChanges establishes a bidirectional stream for real-time configuration updates
	SubscribeToChanges(grpc.BidiStreamingServer[EdgeMessage, ControlMessage]) error
	// SendHeartbeat sends periodic health status updates
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// UnregisterEdge unregisters an edge instance
	UnregisterEdge(context.Context, *EdgeUnregistrationRequest) (*emptypb.Empty, error)
	// ValidateToken validates an API token on-demand (NEW)
	ValidateToken(context.Context, *TokenValidationRequest) (*TokenValidationResponse, error)
	// SendAnalyticsPulse sends batched analytics data from edge to control (NEW)
	SendAnalyticsPulse(context.Context, *AnalyticsPulse) (*AnalyticsPulseResponse, error)
	mustEmbedUnimplementedConfigurationSyncServiceServer()
}

// UnimplementedConfigurationSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigurationSyncServiceServer struct{}

func (UnimplementedConfigurationSyncServiceServer) RegisterEdge(context.Context, *EdgeRegistrationRequest) (*EdgeRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterEdge not implemented")
}
func (UnimplementedConfigurationSyncServiceServer) GetFullConfiguration(context.Context, *ConfigurationRequest) (*ConfigurationSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullConfiguration not implemented")
}
func (UnimplementedConfigurationSyncServiceServer) SubscribeToChanges(grpc.BidiStreamingServer[EdgeMessage, ControlMessage]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToChanges not implemented")
}
func (UnimplementedConfigurationSyncServiceServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedConfigurationSyncServiceServer) UnregisterEdge(context.Context, *EdgeUnregistrationRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterEdge not implemented")
}
func (UnimplementedConfigurationSyncServiceServer) ValidateToken(context.Context, *TokenValidationRequest) (*TokenValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedConfigurationSyncServiceServer) SendAnalyticsPulse(context.Context, *AnalyticsPulse) (*AnalyticsPulseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAnalyticsPulse not implemented")
}
func (UnimplementedConfigurationSyncServiceServer) mustEmbedUnimplementedConfigurationSyncServiceServer() {
}
func (UnimplementedConfigurationSyncServiceServer) testEmbeddedByValue() {}

// UnsafeConfigurationSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigurationSyncServiceServer will
// result in compilation errors.
type UnsafeConfigurationSyncServiceServer interface {
	mustEmbedUnimplementedConfigurationSyncServiceServer()
}

func RegisterConfigurationSyncServiceServer(s grpc.ServiceRegistrar, srv ConfigurationSyncServiceServer) {
	// If the following call pancis, it indicates UnimplementedConfigurationSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigurationSyncService_ServiceDesc, srv)
}

func _ConfigurationSyncService_RegisterEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EdgeRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationSyncServiceServer).RegisterEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationSyncService_RegisterEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationSyncServiceServer).RegisterEdge(ctx, req.(*EdgeRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationSyncService_GetFullConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationSyncServiceServer).GetFullConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationSyncService_GetFullConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationSyncServiceServer).GetFullConfiguration(ctx, req.(*ConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationSyncService_SubscribeToChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConfigurationSyncServiceServer).SubscribeToChanges(&grpc.GenericServerStream[EdgeMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigurationSyncService_SubscribeToChangesServer = grpc.BidiStreamingServer[EdgeMessage, ControlMessage]

func _ConfigurationSyncService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationSyncServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationSyncService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationSyncServiceServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationSyncService_UnregisterEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EdgeUnregistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationSyncServiceServer).UnregisterEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationSyncService_UnregisterEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationSyncServiceServer).UnregisterEdge(ctx, req.(*EdgeUnregistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationSyncService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationSyncServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationSyncService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationSyncServiceServer).ValidateToken(ctx, req.(*TokenValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationSyncService_SendAnalyticsPulse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyticsPulse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationSyncServiceServer).SendAnalyticsPulse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationSyncService_SendAnalyticsPulse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationSyncServiceServer).SendAnalyticsPulse(ctx, req.(*AnalyticsPulse))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigurationSyncService_ServiceDesc is the grpc.ServiceDesc for ConfigurationSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigurationSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microgateway.ConfigurationSyncService",
	HandlerType: (*ConfigurationSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterEdge",
			Handler:    _ConfigurationSyncService_RegisterEdge_Handler,
		},
		{
			MethodName: "GetFullConfiguration",
			Handler:    _ConfigurationSyncService_GetFullConfiguration_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _ConfigurationSyncService_SendHeartbeat_Handler,
		},
		{
			MethodName: "UnregisterEdge",
			Handler:    _ConfigurationSyncService_UnregisterEdge_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _ConfigurationSyncService_ValidateToken_Handler,
		},
		{
			MethodName: "SendAnalyticsPulse",
			Handler:    _ConfigurationSyncService_SendAnalyticsPulse_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToChanges",
			Handler:       _ConfigurationSyncService_SubscribeToChanges_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/config_sync.proto",
}
