// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: proto/config_sync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReloadPhase int32

const (
	ReloadPhase_PONG         ReloadPhase = 0 // Edge acknowledges reload request
	ReloadPhase_PULL_STARTED ReloadPhase = 1 // Edge starts pulling new config
	ReloadPhase_UPDATING     ReloadPhase = 2 // Edge applying new config to SQLite
	ReloadPhase_UPDATED      ReloadPhase = 3 // Edge SQLite update complete
	ReloadPhase_READY        ReloadPhase = 4 // Edge operational with new config
	ReloadPhase_FAILED       ReloadPhase = 5 // Edge failed during reload
)

// Enum value maps for ReloadPhase.
var (
	ReloadPhase_name = map[int32]string{
		0: "PONG",
		1: "PULL_STARTED",
		2: "UPDATING",
		3: "UPDATED",
		4: "READY",
		5: "FAILED",
	}
	ReloadPhase_value = map[string]int32{
		"PONG":         0,
		"PULL_STARTED": 1,
		"UPDATING":     2,
		"UPDATED":      3,
		"READY":        4,
		"FAILED":       5,
	}
)

func (x ReloadPhase) Enum() *ReloadPhase {
	p := new(ReloadPhase)
	*p = x
	return p
}

func (x ReloadPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReloadPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_config_sync_proto_enumTypes[0].Descriptor()
}

func (ReloadPhase) Type() protoreflect.EnumType {
	return &file_proto_config_sync_proto_enumTypes[0]
}

func (x ReloadPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReloadPhase.Descriptor instead.
func (ReloadPhase) EnumDescriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{0}
}

// EdgeRegistrationRequest is sent when an edge instance connects
type EdgeRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`                                                                 // Unique identifier for this edge instance
	EdgeNamespace string                 `protobuf:"bytes,2,opt,name=edge_namespace,json=edgeNamespace,proto3" json:"edge_namespace,omitempty"`                                            // Namespace this edge serves (empty = global only)
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                                                             // Microgateway version
	BuildHash     string                 `protobuf:"bytes,4,opt,name=build_hash,json=buildHash,proto3" json:"build_hash,omitempty"`                                                        // Build hash for version checking
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional edge metadata (region, environment, etc.)
	Health        *HealthStatus          `protobuf:"bytes,6,opt,name=health,proto3" json:"health,omitempty"`                                                                               // Initial health status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeRegistrationRequest) Reset() {
	*x = EdgeRegistrationRequest{}
	mi := &file_proto_config_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeRegistrationRequest) ProtoMessage() {}

func (x *EdgeRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeRegistrationRequest.ProtoReflect.Descriptor instead.
func (*EdgeRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{0}
}

func (x *EdgeRegistrationRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *EdgeRegistrationRequest) GetEdgeNamespace() string {
	if x != nil {
		return x.EdgeNamespace
	}
	return ""
}

func (x *EdgeRegistrationRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EdgeRegistrationRequest) GetBuildHash() string {
	if x != nil {
		return x.BuildHash
	}
	return ""
}

func (x *EdgeRegistrationRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EdgeRegistrationRequest) GetHealth() *HealthStatus {
	if x != nil {
		return x.Health
	}
	return nil
}

// EdgeRegistrationResponse is returned after successful registration
type EdgeRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`             // Session ID for this connection
	InitialConfig *ConfigurationSnapshot `protobuf:"bytes,4,opt,name=initial_config,json=initialConfig,proto3" json:"initial_config,omitempty"` // Initial configuration snapshot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeRegistrationResponse) Reset() {
	*x = EdgeRegistrationResponse{}
	mi := &file_proto_config_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeRegistrationResponse) ProtoMessage() {}

func (x *EdgeRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeRegistrationResponse.ProtoReflect.Descriptor instead.
func (*EdgeRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{1}
}

func (x *EdgeRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EdgeRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EdgeRegistrationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EdgeRegistrationResponse) GetInitialConfig() *ConfigurationSnapshot {
	if x != nil {
		return x.InitialConfig
	}
	return nil
}

// ConfigurationRequest requests configuration for a specific namespace
type ConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeNamespace string                 `protobuf:"bytes,1,opt,name=edge_namespace,json=edgeNamespace,proto3" json:"edge_namespace,omitempty"` // Namespace to filter for (empty = global only)
	LastSyncTime  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`  // Optional: only get changes since this time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationRequest) Reset() {
	*x = ConfigurationRequest{}
	mi := &file_proto_config_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationRequest) ProtoMessage() {}

func (x *ConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationRequest.ProtoReflect.Descriptor instead.
func (*ConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigurationRequest) GetEdgeNamespace() string {
	if x != nil {
		return x.EdgeNamespace
	}
	return ""
}

func (x *ConfigurationRequest) GetLastSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncTime
	}
	return nil
}

// EdgeMessage is sent from edge to control
type EdgeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*EdgeMessage_Registration
	//	*EdgeMessage_Heartbeat
	//	*EdgeMessage_ConfigRequest
	//	*EdgeMessage_Unregistration
	//	*EdgeMessage_ReloadResponse
	Message       isEdgeMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeMessage) Reset() {
	*x = EdgeMessage{}
	mi := &file_proto_config_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeMessage) ProtoMessage() {}

func (x *EdgeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeMessage.ProtoReflect.Descriptor instead.
func (*EdgeMessage) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{3}
}

func (x *EdgeMessage) GetMessage() isEdgeMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *EdgeMessage) GetRegistration() *EdgeRegistrationRequest {
	if x != nil {
		if x, ok := x.Message.(*EdgeMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *EdgeMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Message.(*EdgeMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *EdgeMessage) GetConfigRequest() *ConfigurationRequest {
	if x != nil {
		if x, ok := x.Message.(*EdgeMessage_ConfigRequest); ok {
			return x.ConfigRequest
		}
	}
	return nil
}

func (x *EdgeMessage) GetUnregistration() *EdgeUnregistrationRequest {
	if x != nil {
		if x, ok := x.Message.(*EdgeMessage_Unregistration); ok {
			return x.Unregistration
		}
	}
	return nil
}

func (x *EdgeMessage) GetReloadResponse() *ConfigurationReloadResponse {
	if x != nil {
		if x, ok := x.Message.(*EdgeMessage_ReloadResponse); ok {
			return x.ReloadResponse
		}
	}
	return nil
}

type isEdgeMessage_Message interface {
	isEdgeMessage_Message()
}

type EdgeMessage_Registration struct {
	Registration *EdgeRegistrationRequest `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type EdgeMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type EdgeMessage_ConfigRequest struct {
	ConfigRequest *ConfigurationRequest `protobuf:"bytes,3,opt,name=config_request,json=configRequest,proto3,oneof"`
}

type EdgeMessage_Unregistration struct {
	Unregistration *EdgeUnregistrationRequest `protobuf:"bytes,4,opt,name=unregistration,proto3,oneof"`
}

type EdgeMessage_ReloadResponse struct {
	ReloadResponse *ConfigurationReloadResponse `protobuf:"bytes,5,opt,name=reload_response,json=reloadResponse,proto3,oneof"` // NEW: Reload status reporting
}

func (*EdgeMessage_Registration) isEdgeMessage_Message() {}

func (*EdgeMessage_Heartbeat) isEdgeMessage_Message() {}

func (*EdgeMessage_ConfigRequest) isEdgeMessage_Message() {}

func (*EdgeMessage_Unregistration) isEdgeMessage_Message() {}

func (*EdgeMessage_ReloadResponse) isEdgeMessage_Message() {}

// ControlMessage is sent from control to edge
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ControlMessage_RegistrationResponse
	//	*ControlMessage_Configuration
	//	*ControlMessage_Change
	//	*ControlMessage_HeartbeatResponse
	//	*ControlMessage_Error
	//	*ControlMessage_ReloadRequest
	Message       isControlMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_proto_config_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{4}
}

func (x *ControlMessage) GetMessage() isControlMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ControlMessage) GetRegistrationResponse() *EdgeRegistrationResponse {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_RegistrationResponse); ok {
			return x.RegistrationResponse
		}
	}
	return nil
}

func (x *ControlMessage) GetConfiguration() *ConfigurationSnapshot {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_Configuration); ok {
			return x.Configuration
		}
	}
	return nil
}

func (x *ControlMessage) GetChange() *ConfigurationChange {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_Change); ok {
			return x.Change
		}
	}
	return nil
}

func (x *ControlMessage) GetHeartbeatResponse() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_HeartbeatResponse); ok {
			return x.HeartbeatResponse
		}
	}
	return nil
}

func (x *ControlMessage) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ControlMessage) GetReloadRequest() *ConfigurationReloadRequest {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_ReloadRequest); ok {
			return x.ReloadRequest
		}
	}
	return nil
}

type isControlMessage_Message interface {
	isControlMessage_Message()
}

type ControlMessage_RegistrationResponse struct {
	RegistrationResponse *EdgeRegistrationResponse `protobuf:"bytes,1,opt,name=registration_response,json=registrationResponse,proto3,oneof"`
}

type ControlMessage_Configuration struct {
	Configuration *ConfigurationSnapshot `protobuf:"bytes,2,opt,name=configuration,proto3,oneof"`
}

type ControlMessage_Change struct {
	Change *ConfigurationChange `protobuf:"bytes,3,opt,name=change,proto3,oneof"`
}

type ControlMessage_HeartbeatResponse struct {
	HeartbeatResponse *HeartbeatResponse `protobuf:"bytes,4,opt,name=heartbeat_response,json=heartbeatResponse,proto3,oneof"`
}

type ControlMessage_Error struct {
	Error *ErrorMessage `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type ControlMessage_ReloadRequest struct {
	ReloadRequest *ConfigurationReloadRequest `protobuf:"bytes,6,opt,name=reload_request,json=reloadRequest,proto3,oneof"` // NEW: Initiate reload
}

func (*ControlMessage_RegistrationResponse) isControlMessage_Message() {}

func (*ControlMessage_Configuration) isControlMessage_Message() {}

func (*ControlMessage_Change) isControlMessage_Message() {}

func (*ControlMessage_HeartbeatResponse) isControlMessage_Message() {}

func (*ControlMessage_Error) isControlMessage_Message() {}

func (*ControlMessage_ReloadRequest) isControlMessage_Message() {}

// HeartbeatRequest contains health and status information from edge
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Health        *HealthStatus          `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	Metrics       *EdgeMetrics           `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_config_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetHealth() *HealthStatus {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *HeartbeatRequest) GetMetrics() *EdgeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// HeartbeatResponse acknowledges heartbeat and may contain control directives
type HeartbeatResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Message      string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Control directives (if any)
	RequestFullSync   bool `protobuf:"varint,3,opt,name=request_full_sync,json=requestFullSync,proto3" json:"request_full_sync,omitempty"`     // Request edge to perform full configuration sync
	ShutdownRequested bool `protobuf:"varint,4,opt,name=shutdown_requested,json=shutdownRequested,proto3" json:"shutdown_requested,omitempty"` // Request graceful shutdown
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_config_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HeartbeatResponse) GetRequestFullSync() bool {
	if x != nil {
		return x.RequestFullSync
	}
	return false
}

func (x *HeartbeatResponse) GetShutdownRequested() bool {
	if x != nil {
		return x.ShutdownRequested
	}
	return false
}

// EdgeUnregistrationRequest is sent when edge is shutting down
type EdgeUnregistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // Shutdown reason
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeUnregistrationRequest) Reset() {
	*x = EdgeUnregistrationRequest{}
	mi := &file_proto_config_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeUnregistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeUnregistrationRequest) ProtoMessage() {}

func (x *EdgeUnregistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeUnregistrationRequest.ProtoReflect.Descriptor instead.
func (*EdgeUnregistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{7}
}

func (x *EdgeUnregistrationRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *EdgeUnregistrationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EdgeUnregistrationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// EdgeMetrics contains operational metrics from edge instance
type EdgeMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestsProcessed uint64                 `protobuf:"varint,1,opt,name=requests_processed,json=requestsProcessed,proto3" json:"requests_processed,omitempty"`                                                                // Total requests processed
	ActiveConnections uint64                 `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`                                                                // Current active connections
	CpuUsagePercent   float64                `protobuf:"fixed64,3,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`                                                                   // CPU usage percentage
	MemoryUsageBytes  uint64                 `protobuf:"varint,4,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`                                                                 // Memory usage in bytes
	UptimeSeconds     uint64                 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`                                                                            // Uptime in seconds
	CustomMetrics     map[string]float64     `protobuf:"bytes,6,rep,name=custom_metrics,json=customMetrics,proto3" json:"custom_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // Custom metrics
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EdgeMetrics) Reset() {
	*x = EdgeMetrics{}
	mi := &file_proto_config_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeMetrics) ProtoMessage() {}

func (x *EdgeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeMetrics.ProtoReflect.Descriptor instead.
func (*EdgeMetrics) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{8}
}

func (x *EdgeMetrics) GetRequestsProcessed() uint64 {
	if x != nil {
		return x.RequestsProcessed
	}
	return 0
}

func (x *EdgeMetrics) GetActiveConnections() uint64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *EdgeMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *EdgeMetrics) GetMemoryUsageBytes() uint64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *EdgeMetrics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *EdgeMetrics) GetCustomMetrics() map[string]float64 {
	if x != nil {
		return x.CustomMetrics
	}
	return nil
}

// ErrorMessage represents an error from control to edge
type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`       // Error code
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Human readable error message
	Fatal         bool                   `protobuf:"varint,3,opt,name=fatal,proto3" json:"fatal,omitempty"`    // Whether this error requires edge restart
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_proto_config_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorMessage) GetFatal() bool {
	if x != nil {
		return x.Fatal
	}
	return false
}

// Authentication and authorization messages
type AuthenticationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                 // Authentication token
	EdgeId        string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"` // Edge instance ID
	Challenge     string                 `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"`         // Optional challenge for enhanced security
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationRequest) Reset() {
	*x = AuthenticationRequest{}
	mi := &file_proto_config_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationRequest) ProtoMessage() {}

func (x *AuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{10}
}

func (x *AuthenticationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticationRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *AuthenticationRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

type AuthenticationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authenticated bool                   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // Session token for subsequent requests
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`         // Session expiration timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationResponse) Reset() {
	*x = AuthenticationResponse{}
	mi := &file_proto_config_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationResponse) ProtoMessage() {}

func (x *AuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{11}
}

func (x *AuthenticationResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *AuthenticationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthenticationResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AuthenticationResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// Token validation messages for on-demand validation (NEW)
type TokenValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                      // The API token to validate
	EdgeId        string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`                      // Edge ID making the request
	EdgeNamespace string                 `protobuf:"bytes,3,opt,name=edge_namespace,json=edgeNamespace,proto3" json:"edge_namespace,omitempty"` // Edge namespace for filtering
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValidationRequest) Reset() {
	*x = TokenValidationRequest{}
	mi := &file_proto_config_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValidationRequest) ProtoMessage() {}

func (x *TokenValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValidationRequest.ProtoReflect.Descriptor instead.
func (*TokenValidationRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{12}
}

func (x *TokenValidationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenValidationRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *TokenValidationRequest) GetEdgeNamespace() string {
	if x != nil {
		return x.EdgeNamespace
	}
	return ""
}

type TokenValidationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`                                  // Whether token is valid
	AppId         uint32                 `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                     // App ID if valid (0 if invalid)
	AppName       string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`                // App name for logging
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`                                 // Token scopes if valid
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if invalid
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`          // Token expiration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValidationResponse) Reset() {
	*x = TokenValidationResponse{}
	mi := &file_proto_config_sync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValidationResponse) ProtoMessage() {}

func (x *TokenValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValidationResponse.ProtoReflect.Descriptor instead.
func (*TokenValidationResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{13}
}

func (x *TokenValidationResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *TokenValidationResponse) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *TokenValidationResponse) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *TokenValidationResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *TokenValidationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TokenValidationResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Distributed configuration reload messages (NEW)
type ConfigurationReloadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OperationId     string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`             // Unique operation ID for tracking
	TargetNamespace string                 `protobuf:"bytes,2,opt,name=target_namespace,json=targetNamespace,proto3" json:"target_namespace,omitempty"` // Namespace to reload ("" = all)
	TargetEdges     []string               `protobuf:"bytes,3,rep,name=target_edges,json=targetEdges,proto3" json:"target_edges,omitempty"`             // Specific edge IDs (empty = all in namespace)
	InitiatedBy     string                 `protobuf:"bytes,4,opt,name=initiated_by,json=initiatedBy,proto3" json:"initiated_by,omitempty"`             // CLI user/admin who initiated
	TimeoutSeconds  int64                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`   // Operation timeout
	InitiatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=initiated_at,json=initiatedAt,proto3" json:"initiated_at,omitempty"`             // When reload was initiated
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigurationReloadRequest) Reset() {
	*x = ConfigurationReloadRequest{}
	mi := &file_proto_config_sync_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationReloadRequest) ProtoMessage() {}

func (x *ConfigurationReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationReloadRequest.ProtoReflect.Descriptor instead.
func (*ConfigurationReloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigurationReloadRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ConfigurationReloadRequest) GetTargetNamespace() string {
	if x != nil {
		return x.TargetNamespace
	}
	return ""
}

func (x *ConfigurationReloadRequest) GetTargetEdges() []string {
	if x != nil {
		return x.TargetEdges
	}
	return nil
}

func (x *ConfigurationReloadRequest) GetInitiatedBy() string {
	if x != nil {
		return x.InitiatedBy
	}
	return ""
}

func (x *ConfigurationReloadRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ConfigurationReloadRequest) GetInitiatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InitiatedAt
	}
	return nil
}

type ConfigurationReloadResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OperationId         string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`                           // Operation ID from request
	EdgeId              string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`                                          // Edge reporting status
	Phase               ReloadPhase            `protobuf:"varint,3,opt,name=phase,proto3,enum=microgateway.ReloadPhase" json:"phase,omitempty"`                           // Current reload phase
	Success             bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`                                                     // Success status (valid for READY/FAILED phases)
	Message             string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                                      // Status message or error details
	ConfigVersionBefore string                 `protobuf:"bytes,6,opt,name=config_version_before,json=configVersionBefore,proto3" json:"config_version_before,omitempty"` // Config version before reload
	ConfigVersionAfter  string                 `protobuf:"bytes,7,opt,name=config_version_after,json=configVersionAfter,proto3" json:"config_version_after,omitempty"`    // Config version after reload (if successful)
	Timestamp           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                  // When this status was reported
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfigurationReloadResponse) Reset() {
	*x = ConfigurationReloadResponse{}
	mi := &file_proto_config_sync_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationReloadResponse) ProtoMessage() {}

func (x *ConfigurationReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationReloadResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationReloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigurationReloadResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ConfigurationReloadResponse) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *ConfigurationReloadResponse) GetPhase() ReloadPhase {
	if x != nil {
		return x.Phase
	}
	return ReloadPhase_PONG
}

func (x *ConfigurationReloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigurationReloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigurationReloadResponse) GetConfigVersionBefore() string {
	if x != nil {
		return x.ConfigVersionBefore
	}
	return ""
}

func (x *ConfigurationReloadResponse) GetConfigVersionAfter() string {
	if x != nil {
		return x.ConfigVersionAfter
	}
	return ""
}

func (x *ConfigurationReloadResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// AnalyticsPulse contains batched analytics data from edge to control
type AnalyticsPulse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EdgeId         string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`                          // Edge instance sending the pulse
	EdgeNamespace  string                 `protobuf:"bytes,2,opt,name=edge_namespace,json=edgeNamespace,proto3" json:"edge_namespace,omitempty"`     // Edge namespace
	PulseTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=pulse_timestamp,json=pulseTimestamp,proto3" json:"pulse_timestamp,omitempty"`  // When pulse was generated
	DataFrom       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=data_from,json=dataFrom,proto3" json:"data_from,omitempty"`                    // Start time of data in this pulse
	DataTo         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=data_to,json=dataTo,proto3" json:"data_to,omitempty"`                          // End time of data in this pulse
	SequenceNumber uint64                 `protobuf:"varint,6,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // Incremental sequence for ordering
	// Batched analytics data
	AnalyticsEvents []*AnalyticsEvent   `protobuf:"bytes,7,rep,name=analytics_events,json=analyticsEvents,proto3" json:"analytics_events,omitempty"` // Analytics/token usage events
	BudgetEvents    []*BudgetUsageEvent `protobuf:"bytes,8,rep,name=budget_events,json=budgetEvents,proto3" json:"budget_events,omitempty"`          // Budget usage events
	ProxySummaries  []*ProxyLogSummary  `protobuf:"bytes,9,rep,name=proxy_summaries,json=proxySummaries,proto3" json:"proxy_summaries,omitempty"`    // Summarized proxy logs (not full payloads)
	// Pulse metadata
	IsCompressed  bool   `protobuf:"varint,10,opt,name=is_compressed,json=isCompressed,proto3" json:"is_compressed,omitempty"`      // Whether data is compressed
	TotalRecords  uint32 `protobuf:"varint,11,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`      // Total number of records in pulse
	DataSizeBytes uint64 `protobuf:"varint,12,opt,name=data_size_bytes,json=dataSizeBytes,proto3" json:"data_size_bytes,omitempty"` // Uncompressed data size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsPulse) Reset() {
	*x = AnalyticsPulse{}
	mi := &file_proto_config_sync_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsPulse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsPulse) ProtoMessage() {}

func (x *AnalyticsPulse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsPulse.ProtoReflect.Descriptor instead.
func (*AnalyticsPulse) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{16}
}

func (x *AnalyticsPulse) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *AnalyticsPulse) GetEdgeNamespace() string {
	if x != nil {
		return x.EdgeNamespace
	}
	return ""
}

func (x *AnalyticsPulse) GetPulseTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.PulseTimestamp
	}
	return nil
}

func (x *AnalyticsPulse) GetDataFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DataFrom
	}
	return nil
}

func (x *AnalyticsPulse) GetDataTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DataTo
	}
	return nil
}

func (x *AnalyticsPulse) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *AnalyticsPulse) GetAnalyticsEvents() []*AnalyticsEvent {
	if x != nil {
		return x.AnalyticsEvents
	}
	return nil
}

func (x *AnalyticsPulse) GetBudgetEvents() []*BudgetUsageEvent {
	if x != nil {
		return x.BudgetEvents
	}
	return nil
}

func (x *AnalyticsPulse) GetProxySummaries() []*ProxyLogSummary {
	if x != nil {
		return x.ProxySummaries
	}
	return nil
}

func (x *AnalyticsPulse) GetIsCompressed() bool {
	if x != nil {
		return x.IsCompressed
	}
	return false
}

func (x *AnalyticsPulse) GetTotalRecords() uint32 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *AnalyticsPulse) GetDataSizeBytes() uint64 {
	if x != nil {
		return x.DataSizeBytes
	}
	return 0
}

// AnalyticsPulseResponse acknowledges receipt of analytics pulse
type AnalyticsPulseResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                           // Whether pulse was successfully processed
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                            // Status message or error details
	ProcessedRecords uint64                 `protobuf:"varint,3,opt,name=processed_records,json=processedRecords,proto3" json:"processed_records,omitempty"` // Number of records successfully processed
	SequenceNumber   uint64                 `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`       // Echo sequence number from request
	ProcessedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`                 // When control processed the pulse
	// Pulse configuration updates (if any)
	UpdatedConfig *AnalyticsPulseConfig `protobuf:"bytes,6,opt,name=updated_config,json=updatedConfig,proto3" json:"updated_config,omitempty"` // Updated pulse configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsPulseResponse) Reset() {
	*x = AnalyticsPulseResponse{}
	mi := &file_proto_config_sync_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsPulseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsPulseResponse) ProtoMessage() {}

func (x *AnalyticsPulseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsPulseResponse.ProtoReflect.Descriptor instead.
func (*AnalyticsPulseResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{17}
}

func (x *AnalyticsPulseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnalyticsPulseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AnalyticsPulseResponse) GetProcessedRecords() uint64 {
	if x != nil {
		return x.ProcessedRecords
	}
	return 0
}

func (x *AnalyticsPulseResponse) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *AnalyticsPulseResponse) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *AnalyticsPulseResponse) GetUpdatedConfig() *AnalyticsPulseConfig {
	if x != nil {
		return x.UpdatedConfig
	}
	return nil
}

// AnalyticsPulseConfig configures pulse behavior for an edge
type AnalyticsPulseConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Enabled               bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`                                                            // Whether analytics pulse is enabled
	IntervalSeconds       uint32                 `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`                     // Pulse frequency in seconds (default: 300)
	MaxBatchSize          uint32                 `protobuf:"varint,3,opt,name=max_batch_size,json=maxBatchSize,proto3" json:"max_batch_size,omitempty"`                            // Maximum records per pulse (default: 1000)
	CompressionEnabled    bool                   `protobuf:"varint,4,opt,name=compression_enabled,json=compressionEnabled,proto3" json:"compression_enabled,omitempty"`            // Whether to compress pulse data (default: true)
	MaxBufferSize         uint32                 `protobuf:"varint,5,opt,name=max_buffer_size,json=maxBufferSize,proto3" json:"max_buffer_size,omitempty"`                         // Maximum edge buffer size (default: 10000)
	IncludeProxySummaries bool                   `protobuf:"varint,6,opt,name=include_proxy_summaries,json=includeProxySummaries,proto3" json:"include_proxy_summaries,omitempty"` // Whether to include proxy log summaries (default: true)
	// Data retention settings
	EdgeRetentionHours uint32   `protobuf:"varint,7,opt,name=edge_retention_hours,json=edgeRetentionHours,proto3" json:"edge_retention_hours,omitempty"` // How long edge keeps data after successful pulse (default: 24)
	ExcludedVendors    []string `protobuf:"bytes,8,rep,name=excluded_vendors,json=excludedVendors,proto3" json:"excluded_vendors,omitempty"`             // Vendor patterns to exclude from pulses
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AnalyticsPulseConfig) Reset() {
	*x = AnalyticsPulseConfig{}
	mi := &file_proto_config_sync_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsPulseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsPulseConfig) ProtoMessage() {}

func (x *AnalyticsPulseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsPulseConfig.ProtoReflect.Descriptor instead.
func (*AnalyticsPulseConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{18}
}

func (x *AnalyticsPulseConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AnalyticsPulseConfig) GetIntervalSeconds() uint32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *AnalyticsPulseConfig) GetMaxBatchSize() uint32 {
	if x != nil {
		return x.MaxBatchSize
	}
	return 0
}

func (x *AnalyticsPulseConfig) GetCompressionEnabled() bool {
	if x != nil {
		return x.CompressionEnabled
	}
	return false
}

func (x *AnalyticsPulseConfig) GetMaxBufferSize() uint32 {
	if x != nil {
		return x.MaxBufferSize
	}
	return 0
}

func (x *AnalyticsPulseConfig) GetIncludeProxySummaries() bool {
	if x != nil {
		return x.IncludeProxySummaries
	}
	return false
}

func (x *AnalyticsPulseConfig) GetEdgeRetentionHours() uint32 {
	if x != nil {
		return x.EdgeRetentionHours
	}
	return 0
}

func (x *AnalyticsPulseConfig) GetExcludedVendors() []string {
	if x != nil {
		return x.ExcludedVendors
	}
	return nil
}

// Individual analytics event for pulse batching
type AnalyticsEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                 // Unique request identifier
	AppId          uint32                 `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                            // Application ID
	LlmId          uint32                 `protobuf:"varint,3,opt,name=llm_id,json=llmId,proto3" json:"llm_id,omitempty"`                            // LLM ID (optional)
	Endpoint       string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                    // API endpoint called
	Method         string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`                                        // HTTP method
	StatusCode     int32                  `protobuf:"varint,6,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`             // Response status code
	RequestTokens  uint32                 `protobuf:"varint,7,opt,name=request_tokens,json=requestTokens,proto3" json:"request_tokens,omitempty"`    // Input tokens consumed
	ResponseTokens uint32                 `protobuf:"varint,8,opt,name=response_tokens,json=responseTokens,proto3" json:"response_tokens,omitempty"` // Output tokens generated
	TotalTokens    uint32                 `protobuf:"varint,9,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`          // Total tokens used
	Cost           float64                `protobuf:"fixed64,10,opt,name=cost,proto3" json:"cost,omitempty"`                                         // Cost in dollars (4 decimal precision)
	LatencyMs      uint32                 `protobuf:"varint,11,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`               // Request latency in milliseconds
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                 // When the event occurred
	ErrorMessage   string                 `protobuf:"bytes,13,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`       // Error message if failed (optional)
	// Optional request/response size summary (not full payloads)
	RequestSizeBytes  uint32 `protobuf:"varint,14,opt,name=request_size_bytes,json=requestSizeBytes,proto3" json:"request_size_bytes,omitempty"`    // Size of request body
	ResponseSizeBytes uint32 `protobuf:"varint,15,opt,name=response_size_bytes,json=responseSizeBytes,proto3" json:"response_size_bytes,omitempty"` // Size of response body
	// Model information (NEW)
	ModelName string `protobuf:"bytes,16,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"` // Actual model name from request (e.g., "claude-sonnet-4-20250514")
	Vendor    string `protobuf:"bytes,17,opt,name=vendor,proto3" json:"vendor,omitempty"`                        // Vendor name (e.g., "anthropic", "openai")
	// Optional request/response data (controlled by include_request_response_data flag)
	RequestBody  string `protobuf:"bytes,18,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`    // Request body (if include_request_response_data = true)
	ResponseBody string `protobuf:"bytes,19,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"` // Response body (if include_request_response_data = true)
	// Cache token tracking (for prompt caching features like Anthropic's)
	CacheWritePromptTokens uint32 `protobuf:"varint,20,opt,name=cache_write_prompt_tokens,json=cacheWritePromptTokens,proto3" json:"cache_write_prompt_tokens,omitempty"` // Cache creation/write tokens
	CacheReadPromptTokens  uint32 `protobuf:"varint,21,opt,name=cache_read_prompt_tokens,json=cacheReadPromptTokens,proto3" json:"cache_read_prompt_tokens,omitempty"`    // Cache read tokens
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AnalyticsEvent) Reset() {
	*x = AnalyticsEvent{}
	mi := &file_proto_config_sync_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsEvent) ProtoMessage() {}

func (x *AnalyticsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsEvent.ProtoReflect.Descriptor instead.
func (*AnalyticsEvent) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{19}
}

func (x *AnalyticsEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalyticsEvent) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *AnalyticsEvent) GetLlmId() uint32 {
	if x != nil {
		return x.LlmId
	}
	return 0
}

func (x *AnalyticsEvent) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AnalyticsEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AnalyticsEvent) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AnalyticsEvent) GetRequestTokens() uint32 {
	if x != nil {
		return x.RequestTokens
	}
	return 0
}

func (x *AnalyticsEvent) GetResponseTokens() uint32 {
	if x != nil {
		return x.ResponseTokens
	}
	return 0
}

func (x *AnalyticsEvent) GetTotalTokens() uint32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *AnalyticsEvent) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *AnalyticsEvent) GetLatencyMs() uint32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *AnalyticsEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AnalyticsEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AnalyticsEvent) GetRequestSizeBytes() uint32 {
	if x != nil {
		return x.RequestSizeBytes
	}
	return 0
}

func (x *AnalyticsEvent) GetResponseSizeBytes() uint32 {
	if x != nil {
		return x.ResponseSizeBytes
	}
	return 0
}

func (x *AnalyticsEvent) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *AnalyticsEvent) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *AnalyticsEvent) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

func (x *AnalyticsEvent) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *AnalyticsEvent) GetCacheWritePromptTokens() uint32 {
	if x != nil {
		return x.CacheWritePromptTokens
	}
	return 0
}

func (x *AnalyticsEvent) GetCacheReadPromptTokens() uint32 {
	if x != nil {
		return x.CacheReadPromptTokens
	}
	return 0
}

// Budget usage event for pulse batching
type BudgetUsageEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AppId            uint32                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                                  // Application ID
	LlmId            uint32                 `protobuf:"varint,2,opt,name=llm_id,json=llmId,proto3" json:"llm_id,omitempty"`                                  // LLM ID (optional, 0 if not specific)
	TokensUsed       int64                  `protobuf:"varint,3,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`                   // Tokens consumed in this event
	Cost             float64                `protobuf:"fixed64,4,opt,name=cost,proto3" json:"cost,omitempty"`                                                // Cost in dollars
	PromptTokens     int64                  `protobuf:"varint,5,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`             // Prompt tokens used
	CompletionTokens int64                  `protobuf:"varint,6,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"` // Completion tokens used
	RequestsCount    uint32                 `protobuf:"varint,7,opt,name=requests_count,json=requestsCount,proto3" json:"requests_count,omitempty"`          // Number of requests in this usage event
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                        // When the usage occurred
	PeriodStart      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`                 // Budget period start
	PeriodEnd        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`                      // Budget period end
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BudgetUsageEvent) Reset() {
	*x = BudgetUsageEvent{}
	mi := &file_proto_config_sync_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetUsageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetUsageEvent) ProtoMessage() {}

func (x *BudgetUsageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetUsageEvent.ProtoReflect.Descriptor instead.
func (*BudgetUsageEvent) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{20}
}

func (x *BudgetUsageEvent) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *BudgetUsageEvent) GetLlmId() uint32 {
	if x != nil {
		return x.LlmId
	}
	return 0
}

func (x *BudgetUsageEvent) GetTokensUsed() int64 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *BudgetUsageEvent) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *BudgetUsageEvent) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *BudgetUsageEvent) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *BudgetUsageEvent) GetRequestsCount() uint32 {
	if x != nil {
		return x.RequestsCount
	}
	return 0
}

func (x *BudgetUsageEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BudgetUsageEvent) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *BudgetUsageEvent) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

// Summarized proxy log information (not full request/response)
type ProxyLogSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AppId              uint32                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                                          // Application ID
	UserId             uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                       // User ID
	Vendor             string                 `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`                                                      // LLM vendor
	ResponseCode       int32                  `protobuf:"varint,4,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`                     // HTTP response code
	RequestCount       uint32                 `protobuf:"varint,5,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`                     // Number of requests in this summary
	TotalRequestBytes  uint64                 `protobuf:"varint,6,opt,name=total_request_bytes,json=totalRequestBytes,proto3" json:"total_request_bytes,omitempty"`    // Total bytes of all requests
	TotalResponseBytes uint64                 `protobuf:"varint,7,opt,name=total_response_bytes,json=totalResponseBytes,proto3" json:"total_response_bytes,omitempty"` // Total bytes of all responses
	AvgLatencyMs       uint32                 `protobuf:"varint,8,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`                   // Average latency across requests
	ErrorCount         uint32                 `protobuf:"varint,9,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`                           // Number of failed requests
	FirstRequest       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=first_request,json=firstRequest,proto3" json:"first_request,omitempty"`                     // Timestamp of first request in summary
	LastRequest        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_request,json=lastRequest,proto3" json:"last_request,omitempty"`                        // Timestamp of last request in summary
	// Request pattern summary
	UniqueModels  []string `protobuf:"bytes,12,rep,name=unique_models,json=uniqueModels,proto3" json:"unique_models,omitempty"` // List of unique model names called
	TotalTokens   uint32   `protobuf:"varint,13,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`   // Total tokens across all requests
	TotalCost     float64  `protobuf:"fixed64,14,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`        // Total cost across all requests
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyLogSummary) Reset() {
	*x = ProxyLogSummary{}
	mi := &file_proto_config_sync_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyLogSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyLogSummary) ProtoMessage() {}

func (x *ProxyLogSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyLogSummary.ProtoReflect.Descriptor instead.
func (*ProxyLogSummary) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{21}
}

func (x *ProxyLogSummary) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ProxyLogSummary) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProxyLogSummary) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *ProxyLogSummary) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *ProxyLogSummary) GetRequestCount() uint32 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *ProxyLogSummary) GetTotalRequestBytes() uint64 {
	if x != nil {
		return x.TotalRequestBytes
	}
	return 0
}

func (x *ProxyLogSummary) GetTotalResponseBytes() uint64 {
	if x != nil {
		return x.TotalResponseBytes
	}
	return 0
}

func (x *ProxyLogSummary) GetAvgLatencyMs() uint32 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *ProxyLogSummary) GetErrorCount() uint32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *ProxyLogSummary) GetFirstRequest() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstRequest
	}
	return nil
}

func (x *ProxyLogSummary) GetLastRequest() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRequest
	}
	return nil
}

func (x *ProxyLogSummary) GetUniqueModels() []string {
	if x != nil {
		return x.UniqueModels
	}
	return nil
}

func (x *ProxyLogSummary) GetTotalTokens() uint32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ProxyLogSummary) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

var File_proto_config_sync_proto protoreflect.FileDescriptor

const file_proto_config_sync_proto_rawDesc = "" +
	"\n" +
	"\x17proto/config_sync.proto\x12\fmicrogateway\x1a\x12proto/common.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x02\n" +
	"\x17EdgeRegistrationRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12%\n" +
	"\x0eedge_namespace\x18\x02 \x01(\tR\redgeNamespace\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"build_hash\x18\x04 \x01(\tR\tbuildHash\x12O\n" +
	"\bmetadata\x18\x05 \x03(\v23.microgateway.EdgeRegistrationRequest.MetadataEntryR\bmetadata\x122\n" +
	"\x06health\x18\x06 \x01(\v2\x1a.microgateway.HealthStatusR\x06health\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\x18EdgeRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12J\n" +
	"\x0einitial_config\x18\x04 \x01(\v2#.microgateway.ConfigurationSnapshotR\rinitialConfig\"\x7f\n" +
	"\x14ConfigurationRequest\x12%\n" +
	"\x0eedge_namespace\x18\x01 \x01(\tR\redgeNamespace\x12@\n" +
	"\x0elast_sync_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncTime\"\x9b\x03\n" +
	"\vEdgeMessage\x12K\n" +
	"\fregistration\x18\x01 \x01(\v2%.microgateway.EdgeRegistrationRequestH\x00R\fregistration\x12>\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1e.microgateway.HeartbeatRequestH\x00R\theartbeat\x12K\n" +
	"\x0econfig_request\x18\x03 \x01(\v2\".microgateway.ConfigurationRequestH\x00R\rconfigRequest\x12Q\n" +
	"\x0eunregistration\x18\x04 \x01(\v2'.microgateway.EdgeUnregistrationRequestH\x00R\x0eunregistration\x12T\n" +
	"\x0freload_response\x18\x05 \x01(\v2).microgateway.ConfigurationReloadResponseH\x00R\x0ereloadResponseB\t\n" +
	"\amessage\"\xdd\x03\n" +
	"\x0eControlMessage\x12]\n" +
	"\x15registration_response\x18\x01 \x01(\v2&.microgateway.EdgeRegistrationResponseH\x00R\x14registrationResponse\x12K\n" +
	"\rconfiguration\x18\x02 \x01(\v2#.microgateway.ConfigurationSnapshotH\x00R\rconfiguration\x12;\n" +
	"\x06change\x18\x03 \x01(\v2!.microgateway.ConfigurationChangeH\x00R\x06change\x12P\n" +
	"\x12heartbeat_response\x18\x04 \x01(\v2\x1f.microgateway.HeartbeatResponseH\x00R\x11heartbeatResponse\x122\n" +
	"\x05error\x18\x05 \x01(\v2\x1a.microgateway.ErrorMessageH\x00R\x05error\x12Q\n" +
	"\x0ereload_request\x18\x06 \x01(\v2(.microgateway.ConfigurationReloadRequestH\x00R\rreloadRequestB\t\n" +
	"\amessage\"\xed\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x122\n" +
	"\x06health\x18\x03 \x01(\v2\x1a.microgateway.HealthStatusR\x06health\x123\n" +
	"\ametrics\x18\x04 \x01(\v2\x19.microgateway.EdgeMetricsR\ametrics\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xac\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x11request_full_sync\x18\x03 \x01(\bR\x0frequestFullSync\x12-\n" +
	"\x12shutdown_requested\x18\x04 \x01(\bR\x11shutdownRequested\"k\n" +
	"\x19EdgeUnregistrationRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x83\x03\n" +
	"\vEdgeMetrics\x12-\n" +
	"\x12requests_processed\x18\x01 \x01(\x04R\x11requestsProcessed\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x04R\x11activeConnections\x12*\n" +
	"\x11cpu_usage_percent\x18\x03 \x01(\x01R\x0fcpuUsagePercent\x12,\n" +
	"\x12memory_usage_bytes\x18\x04 \x01(\x04R\x10memoryUsageBytes\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x04R\ruptimeSeconds\x12S\n" +
	"\x0ecustom_metrics\x18\x06 \x03(\v2,.microgateway.EdgeMetrics.CustomMetricsEntryR\rcustomMetrics\x1a@\n" +
	"\x12CustomMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"R\n" +
	"\fErrorMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05fatal\x18\x03 \x01(\bR\x05fatal\"d\n" +
	"\x15AuthenticationRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12\x1c\n" +
	"\tchallenge\x18\x03 \x01(\tR\tchallenge\"\x9c\x01\n" +
	"\x16AuthenticationResponse\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"n\n" +
	"\x16TokenValidationRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12%\n" +
	"\x0eedge_namespace\x18\x03 \x01(\tR\redgeNamespace\"\xd9\x01\n" +
	"\x17TokenValidationResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\rR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x98\x02\n" +
	"\x1aConfigurationReloadRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12)\n" +
	"\x10target_namespace\x18\x02 \x01(\tR\x0ftargetNamespace\x12!\n" +
	"\ftarget_edges\x18\x03 \x03(\tR\vtargetEdges\x12!\n" +
	"\finitiated_by\x18\x04 \x01(\tR\vinitiatedBy\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x03R\x0etimeoutSeconds\x12=\n" +
	"\finitiated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vinitiatedAt\"\xde\x02\n" +
	"\x1bConfigurationReloadResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12/\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x19.microgateway.ReloadPhaseR\x05phase\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x122\n" +
	"\x15config_version_before\x18\x06 \x01(\tR\x13configVersionBefore\x120\n" +
	"\x14config_version_after\x18\a \x01(\tR\x12configVersionAfter\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xf4\x04\n" +
	"\x0eAnalyticsPulse\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12%\n" +
	"\x0eedge_namespace\x18\x02 \x01(\tR\redgeNamespace\x12C\n" +
	"\x0fpulse_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0epulseTimestamp\x127\n" +
	"\tdata_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdataFrom\x123\n" +
	"\adata_to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06dataTo\x12'\n" +
	"\x0fsequence_number\x18\x06 \x01(\x04R\x0esequenceNumber\x12G\n" +
	"\x10analytics_events\x18\a \x03(\v2\x1c.microgateway.AnalyticsEventR\x0fanalyticsEvents\x12C\n" +
	"\rbudget_events\x18\b \x03(\v2\x1e.microgateway.BudgetUsageEventR\fbudgetEvents\x12F\n" +
	"\x0fproxy_summaries\x18\t \x03(\v2\x1d.microgateway.ProxyLogSummaryR\x0eproxySummaries\x12#\n" +
	"\ris_compressed\x18\n" +
	" \x01(\bR\fisCompressed\x12#\n" +
	"\rtotal_records\x18\v \x01(\rR\ftotalRecords\x12&\n" +
	"\x0fdata_size_bytes\x18\f \x01(\x04R\rdataSizeBytes\"\xac\x02\n" +
	"\x16AnalyticsPulseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11processed_records\x18\x03 \x01(\x04R\x10processedRecords\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x04R\x0esequenceNumber\x12=\n" +
	"\fprocessed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x12I\n" +
	"\x0eupdated_config\x18\x06 \x01(\v2\".microgateway.AnalyticsPulseConfigR\rupdatedConfig\"\xef\x02\n" +
	"\x14AnalyticsPulseConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\rR\x0fintervalSeconds\x12$\n" +
	"\x0emax_batch_size\x18\x03 \x01(\rR\fmaxBatchSize\x12/\n" +
	"\x13compression_enabled\x18\x04 \x01(\bR\x12compressionEnabled\x12&\n" +
	"\x0fmax_buffer_size\x18\x05 \x01(\rR\rmaxBufferSize\x126\n" +
	"\x17include_proxy_summaries\x18\x06 \x01(\bR\x15includeProxySummaries\x120\n" +
	"\x14edge_retention_hours\x18\a \x01(\rR\x12edgeRetentionHours\x12)\n" +
	"\x10excluded_vendors\x18\b \x03(\tR\x0fexcludedVendors\"\x88\x06\n" +
	"\x0eAnalyticsEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\rR\x05appId\x12\x15\n" +
	"\x06llm_id\x18\x03 \x01(\rR\x05llmId\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x1f\n" +
	"\vstatus_code\x18\x06 \x01(\x05R\n" +
	"statusCode\x12%\n" +
	"\x0erequest_tokens\x18\a \x01(\rR\rrequestTokens\x12'\n" +
	"\x0fresponse_tokens\x18\b \x01(\rR\x0eresponseTokens\x12!\n" +
	"\ftotal_tokens\x18\t \x01(\rR\vtotalTokens\x12\x12\n" +
	"\x04cost\x18\n" +
	" \x01(\x01R\x04cost\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\v \x01(\rR\tlatencyMs\x128\n" +
	"\ttimestamp\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\rerror_message\x18\r \x01(\tR\ferrorMessage\x12,\n" +
	"\x12request_size_bytes\x18\x0e \x01(\rR\x10requestSizeBytes\x12.\n" +
	"\x13response_size_bytes\x18\x0f \x01(\rR\x11responseSizeBytes\x12\x1d\n" +
	"\n" +
	"model_name\x18\x10 \x01(\tR\tmodelName\x12\x16\n" +
	"\x06vendor\x18\x11 \x01(\tR\x06vendor\x12!\n" +
	"\frequest_body\x18\x12 \x01(\tR\vrequestBody\x12#\n" +
	"\rresponse_body\x18\x13 \x01(\tR\fresponseBody\x129\n" +
	"\x19cache_write_prompt_tokens\x18\x14 \x01(\rR\x16cacheWritePromptTokens\x127\n" +
	"\x18cache_read_prompt_tokens\x18\x15 \x01(\rR\x15cacheReadPromptTokens\"\xa2\x03\n" +
	"\x10BudgetUsageEvent\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x12\x15\n" +
	"\x06llm_id\x18\x02 \x01(\rR\x05llmId\x12\x1f\n" +
	"\vtokens_used\x18\x03 \x01(\x03R\n" +
	"tokensUsed\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x01R\x04cost\x12#\n" +
	"\rprompt_tokens\x18\x05 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x06 \x01(\x03R\x10completionTokens\x12%\n" +
	"\x0erequests_count\x18\a \x01(\rR\rrequestsCount\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12=\n" +
	"\fperiod_start\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\"\xb3\x04\n" +
	"\x0fProxyLogSummary\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\tR\x06vendor\x12#\n" +
	"\rresponse_code\x18\x04 \x01(\x05R\fresponseCode\x12#\n" +
	"\rrequest_count\x18\x05 \x01(\rR\frequestCount\x12.\n" +
	"\x13total_request_bytes\x18\x06 \x01(\x04R\x11totalRequestBytes\x120\n" +
	"\x14total_response_bytes\x18\a \x01(\x04R\x12totalResponseBytes\x12$\n" +
	"\x0eavg_latency_ms\x18\b \x01(\rR\favgLatencyMs\x12\x1f\n" +
	"\verror_count\x18\t \x01(\rR\n" +
	"errorCount\x12?\n" +
	"\rfirst_request\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\ffirstRequest\x12=\n" +
	"\flast_request\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vlastRequest\x12#\n" +
	"\runique_models\x18\f \x03(\tR\funiqueModels\x12!\n" +
	"\ftotal_tokens\x18\r \x01(\rR\vtotalTokens\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x0e \x01(\x01R\ttotalCost*[\n" +
	"\vReloadPhase\x12\b\n" +
	"\x04PONG\x10\x00\x12\x10\n" +
	"\fPULL_STARTED\x10\x01\x12\f\n" +
	"\bUPDATING\x10\x02\x12\v\n" +
	"\aUPDATED\x10\x03\x12\t\n" +
	"\x05READY\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x052\x8a\x05\n" +
	"\x18ConfigurationSyncService\x12]\n" +
	"\fRegisterEdge\x12%.microgateway.EdgeRegistrationRequest\x1a&.microgateway.EdgeRegistrationResponse\x12_\n" +
	"\x14GetFullConfiguration\x12\".microgateway.ConfigurationRequest\x1a#.microgateway.ConfigurationSnapshot\x12Q\n" +
	"\x12SubscribeToChanges\x12\x19.microgateway.EdgeMessage\x1a\x1c.microgateway.ControlMessage(\x010\x01\x12P\n" +
	"\rSendHeartbeat\x12\x1e.microgateway.HeartbeatRequest\x1a\x1f.microgateway.HeartbeatResponse\x12Q\n" +
	"\x0eUnregisterEdge\x12'.microgateway.EdgeUnregistrationRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\rValidateToken\x12$.microgateway.TokenValidationRequest\x1a%.microgateway.TokenValidationResponse\x12X\n" +
	"\x12SendAnalyticsPulse\x12\x1c.microgateway.AnalyticsPulse\x1a$.microgateway.AnalyticsPulseResponseB/Z-github.com/TykTechnologies/midsommar/v2/protob\x06proto3"

var (
	file_proto_config_sync_proto_rawDescOnce sync.Once
	file_proto_config_sync_proto_rawDescData []byte
)

func file_proto_config_sync_proto_rawDescGZIP() []byte {
	file_proto_config_sync_proto_rawDescOnce.Do(func() {
		file_proto_config_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_sync_proto_rawDesc), len(file_proto_config_sync_proto_rawDesc)))
	})
	return file_proto_config_sync_proto_rawDescData
}

var file_proto_config_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_config_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_config_sync_proto_goTypes = []any{
	(ReloadPhase)(0),                    // 0: microgateway.ReloadPhase
	(*EdgeRegistrationRequest)(nil),     // 1: microgateway.EdgeRegistrationRequest
	(*EdgeRegistrationResponse)(nil),    // 2: microgateway.EdgeRegistrationResponse
	(*ConfigurationRequest)(nil),        // 3: microgateway.ConfigurationRequest
	(*EdgeMessage)(nil),                 // 4: microgateway.EdgeMessage
	(*ControlMessage)(nil),              // 5: microgateway.ControlMessage
	(*HeartbeatRequest)(nil),            // 6: microgateway.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 7: microgateway.HeartbeatResponse
	(*EdgeUnregistrationRequest)(nil),   // 8: microgateway.EdgeUnregistrationRequest
	(*EdgeMetrics)(nil),                 // 9: microgateway.EdgeMetrics
	(*ErrorMessage)(nil),                // 10: microgateway.ErrorMessage
	(*AuthenticationRequest)(nil),       // 11: microgateway.AuthenticationRequest
	(*AuthenticationResponse)(nil),      // 12: microgateway.AuthenticationResponse
	(*TokenValidationRequest)(nil),      // 13: microgateway.TokenValidationRequest
	(*TokenValidationResponse)(nil),     // 14: microgateway.TokenValidationResponse
	(*ConfigurationReloadRequest)(nil),  // 15: microgateway.ConfigurationReloadRequest
	(*ConfigurationReloadResponse)(nil), // 16: microgateway.ConfigurationReloadResponse
	(*AnalyticsPulse)(nil),              // 17: microgateway.AnalyticsPulse
	(*AnalyticsPulseResponse)(nil),      // 18: microgateway.AnalyticsPulseResponse
	(*AnalyticsPulseConfig)(nil),        // 19: microgateway.AnalyticsPulseConfig
	(*AnalyticsEvent)(nil),              // 20: microgateway.AnalyticsEvent
	(*BudgetUsageEvent)(nil),            // 21: microgateway.BudgetUsageEvent
	(*ProxyLogSummary)(nil),             // 22: microgateway.ProxyLogSummary
	nil,                                 // 23: microgateway.EdgeRegistrationRequest.MetadataEntry
	nil,                                 // 24: microgateway.EdgeMetrics.CustomMetricsEntry
	(*HealthStatus)(nil),                // 25: microgateway.HealthStatus
	(*ConfigurationSnapshot)(nil),       // 26: microgateway.ConfigurationSnapshot
	(*timestamppb.Timestamp)(nil),       // 27: google.protobuf.Timestamp
	(*ConfigurationChange)(nil),         // 28: microgateway.ConfigurationChange
	(*emptypb.Empty)(nil),               // 29: google.protobuf.Empty
}
var file_proto_config_sync_proto_depIdxs = []int32{
	23, // 0: microgateway.EdgeRegistrationRequest.metadata:type_name -> microgateway.EdgeRegistrationRequest.MetadataEntry
	25, // 1: microgateway.EdgeRegistrationRequest.health:type_name -> microgateway.HealthStatus
	26, // 2: microgateway.EdgeRegistrationResponse.initial_config:type_name -> microgateway.ConfigurationSnapshot
	27, // 3: microgateway.ConfigurationRequest.last_sync_time:type_name -> google.protobuf.Timestamp
	1,  // 4: microgateway.EdgeMessage.registration:type_name -> microgateway.EdgeRegistrationRequest
	6,  // 5: microgateway.EdgeMessage.heartbeat:type_name -> microgateway.HeartbeatRequest
	3,  // 6: microgateway.EdgeMessage.config_request:type_name -> microgateway.ConfigurationRequest
	8,  // 7: microgateway.EdgeMessage.unregistration:type_name -> microgateway.EdgeUnregistrationRequest
	16, // 8: microgateway.EdgeMessage.reload_response:type_name -> microgateway.ConfigurationReloadResponse
	2,  // 9: microgateway.ControlMessage.registration_response:type_name -> microgateway.EdgeRegistrationResponse
	26, // 10: microgateway.ControlMessage.configuration:type_name -> microgateway.ConfigurationSnapshot
	28, // 11: microgateway.ControlMessage.change:type_name -> microgateway.ConfigurationChange
	7,  // 12: microgateway.ControlMessage.heartbeat_response:type_name -> microgateway.HeartbeatResponse
	10, // 13: microgateway.ControlMessage.error:type_name -> microgateway.ErrorMessage
	15, // 14: microgateway.ControlMessage.reload_request:type_name -> microgateway.ConfigurationReloadRequest
	25, // 15: microgateway.HeartbeatRequest.health:type_name -> microgateway.HealthStatus
	9,  // 16: microgateway.HeartbeatRequest.metrics:type_name -> microgateway.EdgeMetrics
	27, // 17: microgateway.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	24, // 18: microgateway.EdgeMetrics.custom_metrics:type_name -> microgateway.EdgeMetrics.CustomMetricsEntry
	27, // 19: microgateway.TokenValidationResponse.expires_at:type_name -> google.protobuf.Timestamp
	27, // 20: microgateway.ConfigurationReloadRequest.initiated_at:type_name -> google.protobuf.Timestamp
	0,  // 21: microgateway.ConfigurationReloadResponse.phase:type_name -> microgateway.ReloadPhase
	27, // 22: microgateway.ConfigurationReloadResponse.timestamp:type_name -> google.protobuf.Timestamp
	27, // 23: microgateway.AnalyticsPulse.pulse_timestamp:type_name -> google.protobuf.Timestamp
	27, // 24: microgateway.AnalyticsPulse.data_from:type_name -> google.protobuf.Timestamp
	27, // 25: microgateway.AnalyticsPulse.data_to:type_name -> google.protobuf.Timestamp
	20, // 26: microgateway.AnalyticsPulse.analytics_events:type_name -> microgateway.AnalyticsEvent
	21, // 27: microgateway.AnalyticsPulse.budget_events:type_name -> microgateway.BudgetUsageEvent
	22, // 28: microgateway.AnalyticsPulse.proxy_summaries:type_name -> microgateway.ProxyLogSummary
	27, // 29: microgateway.AnalyticsPulseResponse.processed_at:type_name -> google.protobuf.Timestamp
	19, // 30: microgateway.AnalyticsPulseResponse.updated_config:type_name -> microgateway.AnalyticsPulseConfig
	27, // 31: microgateway.AnalyticsEvent.timestamp:type_name -> google.protobuf.Timestamp
	27, // 32: microgateway.BudgetUsageEvent.timestamp:type_name -> google.protobuf.Timestamp
	27, // 33: microgateway.BudgetUsageEvent.period_start:type_name -> google.protobuf.Timestamp
	27, // 34: microgateway.BudgetUsageEvent.period_end:type_name -> google.protobuf.Timestamp
	27, // 35: microgateway.ProxyLogSummary.first_request:type_name -> google.protobuf.Timestamp
	27, // 36: microgateway.ProxyLogSummary.last_request:type_name -> google.protobuf.Timestamp
	1,  // 37: microgateway.ConfigurationSyncService.RegisterEdge:input_type -> microgateway.EdgeRegistrationRequest
	3,  // 38: microgateway.ConfigurationSyncService.GetFullConfiguration:input_type -> microgateway.ConfigurationRequest
	4,  // 39: microgateway.ConfigurationSyncService.SubscribeToChanges:input_type -> microgateway.EdgeMessage
	6,  // 40: microgateway.ConfigurationSyncService.SendHeartbeat:input_type -> microgateway.HeartbeatRequest
	8,  // 41: microgateway.ConfigurationSyncService.UnregisterEdge:input_type -> microgateway.EdgeUnregistrationRequest
	13, // 42: microgateway.ConfigurationSyncService.ValidateToken:input_type -> microgateway.TokenValidationRequest
	17, // 43: microgateway.ConfigurationSyncService.SendAnalyticsPulse:input_type -> microgateway.AnalyticsPulse
	2,  // 44: microgateway.ConfigurationSyncService.RegisterEdge:output_type -> microgateway.EdgeRegistrationResponse
	26, // 45: microgateway.ConfigurationSyncService.GetFullConfiguration:output_type -> microgateway.ConfigurationSnapshot
	5,  // 46: microgateway.ConfigurationSyncService.SubscribeToChanges:output_type -> microgateway.ControlMessage
	7,  // 47: microgateway.ConfigurationSyncService.SendHeartbeat:output_type -> microgateway.HeartbeatResponse
	29, // 48: microgateway.ConfigurationSyncService.UnregisterEdge:output_type -> google.protobuf.Empty
	14, // 49: microgateway.ConfigurationSyncService.ValidateToken:output_type -> microgateway.TokenValidationResponse
	18, // 50: microgateway.ConfigurationSyncService.SendAnalyticsPulse:output_type -> microgateway.AnalyticsPulseResponse
	44, // [44:51] is the sub-list for method output_type
	37, // [37:44] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_proto_config_sync_proto_init() }
func file_proto_config_sync_proto_init() {
	if File_proto_config_sync_proto != nil {
		return
	}
	file_proto_common_proto_init()
	file_proto_config_sync_proto_msgTypes[3].OneofWrappers = []any{
		(*EdgeMessage_Registration)(nil),
		(*EdgeMessage_Heartbeat)(nil),
		(*EdgeMessage_ConfigRequest)(nil),
		(*EdgeMessage_Unregistration)(nil),
		(*EdgeMessage_ReloadResponse)(nil),
	}
	file_proto_config_sync_proto_msgTypes[4].OneofWrappers = []any{
		(*ControlMessage_RegistrationResponse)(nil),
		(*ControlMessage_Configuration)(nil),
		(*ControlMessage_Change)(nil),
		(*ControlMessage_HeartbeatResponse)(nil),
		(*ControlMessage_Error)(nil),
		(*ControlMessage_ReloadRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_sync_proto_rawDesc), len(file_proto_config_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_sync_proto_goTypes,
		DependencyIndexes: file_proto_config_sync_proto_depIdxs,
		EnumInfos:         file_proto_config_sync_proto_enumTypes,
		MessageInfos:      file_proto_config_sync_proto_msgTypes,
	}.Build()
	File_proto_config_sync_proto = out.File
	file_proto_config_sync_proto_goTypes = nil
	file_proto_config_sync_proto_depIdxs = nil
}
