// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PingResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type ShutdownRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TimeoutSeconds int64                  `protobuf:"varint,1,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ShutdownRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PluginContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	LlmId         uint32                 `protobuf:"varint,3,opt,name=llm_id,json=llmId,proto3" json:"llm_id,omitempty"`
	LlmSlug       string                 `protobuf:"bytes,4,opt,name=llm_slug,json=llmSlug,proto3" json:"llm_slug,omitempty"`
	AppId         uint32                 `protobuf:"varint,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TraceContext  map[string]string      `protobuf:"bytes,8,rep,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginContext) Reset() {
	*x = PluginContext{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginContext) ProtoMessage() {}

func (x *PluginContext) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginContext.ProtoReflect.Descriptor instead.
func (*PluginContext) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *PluginContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PluginContext) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *PluginContext) GetLlmId() uint32 {
	if x != nil {
		return x.LlmId
	}
	return 0
}

func (x *PluginContext) GetLlmSlug() string {
	if x != nil {
		return x.LlmSlug
	}
	return ""
}

func (x *PluginContext) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *PluginContext) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PluginContext) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PluginContext) GetTraceContext() map[string]string {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

type PluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Context       *PluginContext         `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,6,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginRequest) Reset() {
	*x = PluginRequest{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRequest) ProtoMessage() {}

func (x *PluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRequest.ProtoReflect.Descriptor instead.
func (*PluginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *PluginRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PluginRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PluginRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *PluginRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PluginRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *PluginRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

type PluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modified      bool                   `protobuf:"varint,1,opt,name=modified,proto3" json:"modified,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Block         bool                   `protobuf:"varint,5,opt,name=block,proto3" json:"block,omitempty"` // Stop processing if true
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginResponse) Reset() {
	*x = PluginResponse{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginResponse) ProtoMessage() {}

func (x *PluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginResponse.ProtoReflect.Descriptor instead.
func (*PluginResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *PluginResponse) GetModified() bool {
	if x != nil {
		return x.Modified
	}
	return false
}

func (x *PluginResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *PluginResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *PluginResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PluginResponse) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

func (x *PluginResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    string                 `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	AuthType      string                 `protobuf:"bytes,2,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	Request       *PluginRequest         `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Context       *PluginContext         `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *AuthRequest) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *AuthRequest) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *AuthRequest) GetRequest() *PluginRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AuthRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authenticated bool                   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Claims        map[string]string      `protobuf:"bytes,4,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *AuthResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AuthResponse) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *AuthResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type EnrichedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *PluginRequest         `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AuthClaims    map[string]string      `protobuf:"bytes,4,rep,name=auth_claims,json=authClaims,proto3" json:"auth_claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Authenticated bool                   `protobuf:"varint,5,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichedRequest) Reset() {
	*x = EnrichedRequest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedRequest) ProtoMessage() {}

func (x *EnrichedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedRequest.ProtoReflect.Descriptor instead.
func (*EnrichedRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *EnrichedRequest) GetRequest() *PluginRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *EnrichedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnrichedRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *EnrichedRequest) GetAuthClaims() map[string]string {
	if x != nil {
		return x.AuthClaims
	}
	return nil
}

func (x *EnrichedRequest) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

type HeadersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       map[string]string      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Context       *PluginContext         `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadersRequest) Reset() {
	*x = HeadersRequest{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadersRequest) ProtoMessage() {}

func (x *HeadersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadersRequest.ProtoReflect.Descriptor instead.
func (*HeadersRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *HeadersRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HeadersRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type HeadersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modified      bool                   `protobuf:"varint,1,opt,name=modified,proto3" json:"modified,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadersResponse) Reset() {
	*x = HeadersResponse{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadersResponse) ProtoMessage() {}

func (x *HeadersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadersResponse.ProtoReflect.Descriptor instead.
func (*HeadersResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *HeadersResponse) GetModified() bool {
	if x != nil {
		return x.Modified
	}
	return false
}

func (x *HeadersResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ResponseWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsStreamChunk bool                   `protobuf:"varint,3,opt,name=is_stream_chunk,json=isStreamChunk,proto3" json:"is_stream_chunk,omitempty"`
	Context       *PluginContext         `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseWriteRequest) Reset() {
	*x = ResponseWriteRequest{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseWriteRequest) ProtoMessage() {}

func (x *ResponseWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseWriteRequest.ProtoReflect.Descriptor instead.
func (*ResponseWriteRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ResponseWriteRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ResponseWriteRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ResponseWriteRequest) GetIsStreamChunk() bool {
	if x != nil {
		return x.IsStreamChunk
	}
	return false
}

func (x *ResponseWriteRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ResponseWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modified      bool                   `protobuf:"varint,1,opt,name=modified,proto3" json:"modified,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseWriteResponse) Reset() {
	*x = ResponseWriteResponse{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseWriteResponse) ProtoMessage() {}

func (x *ResponseWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseWriteResponse.ProtoReflect.Descriptor instead.
func (*ResponseWriteResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *ResponseWriteResponse) GetModified() bool {
	if x != nil {
		return x.Modified
	}
	return false
}

func (x *ResponseWriteResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ResponseWriteResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type GetAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    string                 `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Context       *PluginContext         `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppRequest) Reset() {
	*x = GetAppRequest{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppRequest) ProtoMessage() {}

func (x *GetAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppRequest.ProtoReflect.Descriptor instead.
func (*GetAppRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *GetAppRequest) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *GetAppRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type GetAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	App           *App                   `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppResponse) Reset() {
	*x = GetAppResponse{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppResponse) ProtoMessage() {}

func (x *GetAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppResponse.ProtoReflect.Descriptor instead.
func (*GetAppResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *GetAppResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAppResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetAppResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    string                 `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Context       *PluginContext         `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserRequest) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *GetUserRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerEmail    string                 `protobuf:"bytes,4,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	MonthlyBudget float64                `protobuf:"fixed64,6,opt,name=monthly_budget,json=monthlyBudget,proto3" json:"monthly_budget,omitempty"`
	RateLimit     int32                  `protobuf:"varint,7,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *App) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *App) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

func (x *App) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *App) GetMonthlyBudget() float64 {
	if x != nil {
		return x.MonthlyBudget
	}
	return 0
}

func (x *App) GetRateLimit() int32 {
	if x != nil {
		return x.RateLimit
	}
	return 0
}

func (x *App) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ProxyLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         uint32                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Vendor        string                 `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	RequestBody   []byte                 `protobuf:"bytes,4,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	ResponseBody  []byte                 `protobuf:"bytes,5,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	ResponseCode  int32                  `protobuf:"varint,6,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in seconds
	RequestId     string                 `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Context       *PluginContext         `protobuf:"bytes,9,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyLogRequest) Reset() {
	*x = ProxyLogRequest{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyLogRequest) ProtoMessage() {}

func (x *ProxyLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyLogRequest.ProtoReflect.Descriptor instead.
func (*ProxyLogRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *ProxyLogRequest) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ProxyLogRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProxyLogRequest) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *ProxyLogRequest) GetRequestBody() []byte {
	if x != nil {
		return x.RequestBody
	}
	return nil
}

func (x *ProxyLogRequest) GetResponseBody() []byte {
	if x != nil {
		return x.ResponseBody
	}
	return nil
}

func (x *ProxyLogRequest) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *ProxyLogRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProxyLogRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProxyLogRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type AnalyticsRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LlmId                  uint32                 `protobuf:"varint,1,opt,name=llm_id,json=llmId,proto3" json:"llm_id,omitempty"`
	ModelName              string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Vendor                 string                 `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	PromptTokens           int32                  `protobuf:"varint,4,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	ResponseTokens         int32                  `protobuf:"varint,5,opt,name=response_tokens,json=responseTokens,proto3" json:"response_tokens,omitempty"`
	CacheWritePromptTokens int32                  `protobuf:"varint,6,opt,name=cache_write_prompt_tokens,json=cacheWritePromptTokens,proto3" json:"cache_write_prompt_tokens,omitempty"`
	CacheReadPromptTokens  int32                  `protobuf:"varint,7,opt,name=cache_read_prompt_tokens,json=cacheReadPromptTokens,proto3" json:"cache_read_prompt_tokens,omitempty"`
	TotalTokens            int32                  `protobuf:"varint,8,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	Cost                   float64                `protobuf:"fixed64,9,opt,name=cost,proto3" json:"cost,omitempty"`
	Currency               string                 `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	AppId                  uint32                 `protobuf:"varint,11,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId                 uint32                 `protobuf:"varint,12,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp              int64                  `protobuf:"varint,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in seconds
	ToolCalls              int32                  `protobuf:"varint,14,opt,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Choices                int32                  `protobuf:"varint,15,opt,name=choices,proto3" json:"choices,omitempty"`
	RequestId              string                 `protobuf:"bytes,16,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Context                *PluginContext         `protobuf:"bytes,17,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AnalyticsRequest) Reset() {
	*x = AnalyticsRequest{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsRequest) ProtoMessage() {}

func (x *AnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsRequest.ProtoReflect.Descriptor instead.
func (*AnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *AnalyticsRequest) GetLlmId() uint32 {
	if x != nil {
		return x.LlmId
	}
	return 0
}

func (x *AnalyticsRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *AnalyticsRequest) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *AnalyticsRequest) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *AnalyticsRequest) GetResponseTokens() int32 {
	if x != nil {
		return x.ResponseTokens
	}
	return 0
}

func (x *AnalyticsRequest) GetCacheWritePromptTokens() int32 {
	if x != nil {
		return x.CacheWritePromptTokens
	}
	return 0
}

func (x *AnalyticsRequest) GetCacheReadPromptTokens() int32 {
	if x != nil {
		return x.CacheReadPromptTokens
	}
	return 0
}

func (x *AnalyticsRequest) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *AnalyticsRequest) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *AnalyticsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AnalyticsRequest) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *AnalyticsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AnalyticsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AnalyticsRequest) GetToolCalls() int32 {
	if x != nil {
		return x.ToolCalls
	}
	return 0
}

func (x *AnalyticsRequest) GetChoices() int32 {
	if x != nil {
		return x.Choices
	}
	return 0
}

func (x *AnalyticsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalyticsRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type BudgetUsageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AppId            uint32                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	LlmId            uint32                 `protobuf:"varint,2,opt,name=llm_id,json=llmId,proto3" json:"llm_id,omitempty"`
	TokensUsed       int64                  `protobuf:"varint,3,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	Cost             float64                `protobuf:"fixed64,4,opt,name=cost,proto3" json:"cost,omitempty"`
	RequestsCount    int32                  `protobuf:"varint,5,opt,name=requests_count,json=requestsCount,proto3" json:"requests_count,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,6,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,7,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	PeriodStart      int64                  `protobuf:"varint,8,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"` // Unix timestamp in seconds
	PeriodEnd        int64                  `protobuf:"varint,9,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`       // Unix timestamp in seconds
	Timestamp        int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                       // Unix timestamp in seconds
	RequestId        string                 `protobuf:"bytes,11,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Context          *PluginContext         `protobuf:"bytes,12,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BudgetUsageRequest) Reset() {
	*x = BudgetUsageRequest{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetUsageRequest) ProtoMessage() {}

func (x *BudgetUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetUsageRequest.ProtoReflect.Descriptor instead.
func (*BudgetUsageRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *BudgetUsageRequest) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *BudgetUsageRequest) GetLlmId() uint32 {
	if x != nil {
		return x.LlmId
	}
	return 0
}

func (x *BudgetUsageRequest) GetTokensUsed() int64 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *BudgetUsageRequest) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *BudgetUsageRequest) GetRequestsCount() int32 {
	if x != nil {
		return x.RequestsCount
	}
	return 0
}

func (x *BudgetUsageRequest) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *BudgetUsageRequest) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *BudgetUsageRequest) GetPeriodStart() int64 {
	if x != nil {
		return x.PeriodStart
	}
	return 0
}

func (x *BudgetUsageRequest) GetPeriodEnd() int64 {
	if x != nil {
		return x.PeriodEnd
	}
	return 0
}

func (x *BudgetUsageRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BudgetUsageRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BudgetUsageRequest) GetContext() *PluginContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type DataCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Handled       bool                   `protobuf:"varint,2,opt,name=handled,proto3" json:"handled,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCollectionResponse) Reset() {
	*x = DataCollectionResponse{}
	mi := &file_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCollectionResponse) ProtoMessage() {}

func (x *DataCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCollectionResponse.ProtoReflect.Descriptor instead.
func (*DataCollectionResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *DataCollectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DataCollectionResponse) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

func (x *DataCollectionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DataCollectionResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetPath     string                 `protobuf:"bytes,1,opt,name=asset_path,json=assetPath,proto3" json:"asset_path,omitempty"` // Relative path to asset (e.g., "ui/webc/dashboard.js")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *GetAssetRequest) GetAssetPath() string {
	if x != nil {
		return x.AssetPath
	}
	return ""
}

type GetAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                   // Asset file content
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"` // MIME type (e.g., "application/javascript")
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ContentLength int64                  `protobuf:"varint,5,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetResponse) Reset() {
	*x = GetAssetResponse{}
	mi := &file_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetResponse) ProtoMessage() {}

func (x *GetAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetResponse.ProtoReflect.Descriptor instead.
func (*GetAssetResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *GetAssetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAssetResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetAssetResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetAssetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetAssetResponse) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

type ListAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathPrefix    string                 `protobuf:"bytes,1,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"` // Optional filter (e.g., "ui/")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	mi := &file_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *ListAssetsRequest) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

type ListAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Assets        []*AssetInfo           `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsResponse) Reset() {
	*x = ListAssetsResponse{}
	mi := &file_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsResponse) ProtoMessage() {}

func (x *ListAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListAssetsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *ListAssetsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListAssetsResponse) GetAssets() []*AssetInfo {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *ListAssetsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AssetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                         // Asset path
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"` // MIME type
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`                        // File size in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetInfo) Reset() {
	*x = AssetInfo{}
	mi := &file_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetInfo) ProtoMessage() {}

func (x *AssetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetInfo.ProtoReflect.Descriptor instead.
func (*AssetInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{30}
}

func (x *AssetInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AssetInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AssetInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{31}
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ManifestJson  string                 `protobuf:"bytes,2,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"` // Complete manifest as JSON string
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_plugin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{32}
}

func (x *GetManifestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetManifestResponse) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

func (x *GetManifestResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Generic RPC call messages (for AI Studio plugins)
type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`   // RPC method name (e.g., "get_statistics")
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON payload as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_plugin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{33}
}

func (x *CallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // JSON response data as string
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_plugin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{34}
}

func (x *CallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CallResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *CallResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Configuration schema messages
type GetConfigSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigSchemaRequest) Reset() {
	*x = GetConfigSchemaRequest{}
	mi := &file_plugin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigSchemaRequest) ProtoMessage() {}

func (x *GetConfigSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetConfigSchemaRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{35}
}

type GetConfigSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SchemaJson    string                 `protobuf:"bytes,2,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"` // JSON Schema as string (jsonschema.org format)
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigSchemaResponse) Reset() {
	*x = GetConfigSchemaResponse{}
	mi := &file_plugin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigSchemaResponse) ProtoMessage() {}

func (x *GetConfigSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetConfigSchemaResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{36}
}

func (x *GetConfigSchemaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetConfigSchemaResponse) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

func (x *GetConfigSchemaResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x06plugin\"\x81\x01\n" +
	"\vInitRequest\x127\n" +
	"\x06config\x18\x01 \x03(\v2\x1f.plugin.InitRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\fInitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"+\n" +
	"\vPingRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"F\n" +
	"\fPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\":\n" +
	"\x0fShutdownRequest\x12'\n" +
	"\x0ftimeout_seconds\x18\x01 \x01(\x03R\x0etimeoutSeconds\",\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb5\x03\n" +
	"\rPluginContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x15\n" +
	"\x06llm_id\x18\x03 \x01(\rR\x05llmId\x12\x19\n" +
	"\bllm_slug\x18\x04 \x01(\tR\allmSlug\x12\x15\n" +
	"\x06app_id\x18\x05 \x01(\rR\x05appId\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\rR\x06userId\x12?\n" +
	"\bmetadata\x18\a \x03(\v2#.plugin.PluginContext.MetadataEntryR\bmetadata\x12L\n" +
	"\rtrace_context\x18\b \x03(\v2'.plugin.PluginContext.TraceContextEntryR\ftraceContext\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11TraceContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x02\n" +
	"\rPluginRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12<\n" +
	"\aheaders\x18\x03 \x03(\v2\".plugin.PluginRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12/\n" +
	"\acontext\x18\x05 \x01(\v2\x15.plugin.PluginContextR\acontext\x12\x1f\n" +
	"\vremote_addr\x18\x06 \x01(\tR\n" +
	"remoteAddr\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x02\n" +
	"\x0ePluginResponse\x12\x1a\n" +
	"\bmodified\x18\x01 \x01(\bR\bmodified\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12=\n" +
	"\aheaders\x18\x03 \x03(\v2#.plugin.PluginResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x14\n" +
	"\x05block\x18\x05 \x01(\bR\x05block\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\vAuthRequest\x12\x1e\n" +
	"\n" +
	"credential\x18\x01 \x01(\tR\n" +
	"credential\x12\x1b\n" +
	"\tauth_type\x18\x02 \x01(\tR\bauthType\x12/\n" +
	"\arequest\x18\x03 \x01(\v2\x15.plugin.PluginRequestR\arequest\x12/\n" +
	"\acontext\x18\x04 \x01(\v2\x15.plugin.PluginContextR\acontext\"\xfe\x01\n" +
	"\fAuthResponse\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x128\n" +
	"\x06claims\x18\x04 \x03(\v2 .plugin.AuthResponse.ClaimsEntryR\x06claims\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x02\n" +
	"\x0fEnrichedRequest\x12/\n" +
	"\arequest\x18\x01 \x01(\v2\x15.plugin.PluginRequestR\arequest\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12H\n" +
	"\vauth_claims\x18\x04 \x03(\v2'.plugin.EnrichedRequest.AuthClaimsEntryR\n" +
	"authClaims\x12$\n" +
	"\rauthenticated\x18\x05 \x01(\bR\rauthenticated\x1a=\n" +
	"\x0fAuthClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x01\n" +
	"\x0eHeadersRequest\x12=\n" +
	"\aheaders\x18\x01 \x03(\v2#.plugin.HeadersRequest.HeadersEntryR\aheaders\x12/\n" +
	"\acontext\x18\x02 \x01(\v2\x15.plugin.PluginContextR\acontext\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\x0fHeadersResponse\x12\x1a\n" +
	"\bmodified\x18\x01 \x01(\bR\bmodified\x12>\n" +
	"\aheaders\x18\x02 \x03(\v2$.plugin.HeadersResponse.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x02\n" +
	"\x14ResponseWriteRequest\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12C\n" +
	"\aheaders\x18\x02 \x03(\v2).plugin.ResponseWriteRequest.HeadersEntryR\aheaders\x12&\n" +
	"\x0fis_stream_chunk\x18\x03 \x01(\bR\risStreamChunk\x12/\n" +
	"\acontext\x18\x04 \x01(\v2\x15.plugin.PluginContextR\acontext\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x01\n" +
	"\x15ResponseWriteResponse\x12\x1a\n" +
	"\bmodified\x18\x01 \x01(\bR\bmodified\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12D\n" +
	"\aheaders\x18\x03 \x03(\v2*.plugin.ResponseWriteResponse.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\rGetAppRequest\x12\x1e\n" +
	"\n" +
	"credential\x18\x01 \x01(\tR\n" +
	"credential\x12/\n" +
	"\acontext\x18\x02 \x01(\v2\x15.plugin.PluginContextR\acontext\"n\n" +
	"\x0eGetAppResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\x03app\x18\x03 \x01(\v2\v.plugin.AppR\x03app\"a\n" +
	"\x0eGetUserRequest\x12\x1e\n" +
	"\n" +
	"credential\x18\x01 \x01(\tR\n" +
	"credential\x12/\n" +
	"\acontext\x18\x02 \x01(\v2\x15.plugin.PluginContextR\acontext\"r\n" +
	"\x0fGetUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12 \n" +
	"\x04user\x18\x03 \x01(\v2\f.plugin.UserR\x04user\"\xc3\x02\n" +
	"\x03App\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vowner_email\x18\x04 \x01(\tR\n" +
	"ownerEmail\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12%\n" +
	"\x0emonthly_budget\x18\x06 \x01(\x01R\rmonthlyBudget\x12\x1d\n" +
	"\n" +
	"rate_limit\x18\a \x01(\x05R\trateLimit\x125\n" +
	"\bmetadata\x18\b \x03(\v2\x19.plugin.App.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd2\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x126\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1a.plugin.User.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x02\n" +
	"\x0fProxyLogRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\tR\x06vendor\x12!\n" +
	"\frequest_body\x18\x04 \x01(\fR\vrequestBody\x12#\n" +
	"\rresponse_body\x18\x05 \x01(\fR\fresponseBody\x12#\n" +
	"\rresponse_code\x18\x06 \x01(\x05R\fresponseCode\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId\x12/\n" +
	"\acontext\x18\t \x01(\v2\x15.plugin.PluginContextR\acontext\"\xcc\x04\n" +
	"\x10AnalyticsRequest\x12\x15\n" +
	"\x06llm_id\x18\x01 \x01(\rR\x05llmId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\tR\x06vendor\x12#\n" +
	"\rprompt_tokens\x18\x04 \x01(\x05R\fpromptTokens\x12'\n" +
	"\x0fresponse_tokens\x18\x05 \x01(\x05R\x0eresponseTokens\x129\n" +
	"\x19cache_write_prompt_tokens\x18\x06 \x01(\x05R\x16cacheWritePromptTokens\x127\n" +
	"\x18cache_read_prompt_tokens\x18\a \x01(\x05R\x15cacheReadPromptTokens\x12!\n" +
	"\ftotal_tokens\x18\b \x01(\x05R\vtotalTokens\x12\x12\n" +
	"\x04cost\x18\t \x01(\x01R\x04cost\x12\x1a\n" +
	"\bcurrency\x18\n" +
	" \x01(\tR\bcurrency\x12\x15\n" +
	"\x06app_id\x18\v \x01(\rR\x05appId\x12\x17\n" +
	"\auser_id\x18\f \x01(\rR\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\r \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"tool_calls\x18\x0e \x01(\x05R\ttoolCalls\x12\x18\n" +
	"\achoices\x18\x0f \x01(\x05R\achoices\x12\x1d\n" +
	"\n" +
	"request_id\x18\x10 \x01(\tR\trequestId\x12/\n" +
	"\acontext\x18\x11 \x01(\v2\x15.plugin.PluginContextR\acontext\"\xa0\x03\n" +
	"\x12BudgetUsageRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x12\x15\n" +
	"\x06llm_id\x18\x02 \x01(\rR\x05llmId\x12\x1f\n" +
	"\vtokens_used\x18\x03 \x01(\x03R\n" +
	"tokensUsed\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x01R\x04cost\x12%\n" +
	"\x0erequests_count\x18\x05 \x01(\x05R\rrequestsCount\x12#\n" +
	"\rprompt_tokens\x18\x06 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\a \x01(\x03R\x10completionTokens\x12!\n" +
	"\fperiod_start\x18\b \x01(\x03R\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\t \x01(\x03R\tperiodEnd\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"request_id\x18\v \x01(\tR\trequestId\x12/\n" +
	"\acontext\x18\f \x01(\v2\x15.plugin.PluginContextR\acontext\"\xf8\x01\n" +
	"\x16DataCollectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\ahandled\x18\x02 \x01(\bR\ahandled\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12H\n" +
	"\bmetadata\x18\x04 \x03(\v2,.plugin.DataCollectionResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x0fGetAssetRequest\x12\x1d\n" +
	"\n" +
	"asset_path\x18\x01 \x01(\tR\tassetPath\"\xaf\x01\n" +
	"\x10GetAssetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0econtent_length\x18\x05 \x01(\x03R\rcontentLength\"4\n" +
	"\x11ListAssetsRequest\x12\x1f\n" +
	"\vpath_prefix\x18\x01 \x01(\tR\n" +
	"pathPrefix\"~\n" +
	"\x12ListAssetsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x06assets\x18\x02 \x03(\v2\x11.plugin.AssetInfoR\x06assets\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"P\n" +
	"\tAssetInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\x14\n" +
	"\x12GetManifestRequest\"y\n" +
	"\x13GetManifestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rmanifest_json\x18\x02 \x01(\tR\fmanifestJson\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"?\n" +
	"\vCallRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"a\n" +
	"\fCallResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x18\n" +
	"\x16GetConfigSchemaRequest\"y\n" +
	"\x17GetConfigSchemaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vschema_json\x18\x02 \x01(\tR\n" +
	"schemaJson\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2\xda\t\n" +
	"\rPluginService\x127\n" +
	"\n" +
	"Initialize\x12\x13.plugin.InitRequest\x1a\x14.plugin.InitResponse\x121\n" +
	"\x04Ping\x12\x13.plugin.PingRequest\x1a\x14.plugin.PingResponse\x12=\n" +
	"\bShutdown\x12\x17.plugin.ShutdownRequest\x1a\x18.plugin.ShutdownResponse\x12?\n" +
	"\x0eProcessPreAuth\x12\x15.plugin.PluginRequest\x1a\x16.plugin.PluginResponse\x129\n" +
	"\fAuthenticate\x12\x13.plugin.AuthRequest\x1a\x14.plugin.AuthResponse\x12C\n" +
	"\x12GetAppByCredential\x12\x15.plugin.GetAppRequest\x1a\x16.plugin.GetAppResponse\x12F\n" +
	"\x13GetUserByCredential\x12\x16.plugin.GetUserRequest\x1a\x17.plugin.GetUserResponse\x12B\n" +
	"\x0fProcessPostAuth\x12\x17.plugin.EnrichedRequest\x1a\x16.plugin.PluginResponse\x12G\n" +
	"\x14OnBeforeWriteHeaders\x12\x16.plugin.HeadersRequest\x1a\x17.plugin.HeadersResponse\x12L\n" +
	"\rOnBeforeWrite\x12\x1c.plugin.ResponseWriteRequest\x1a\x1d.plugin.ResponseWriteResponse\x12I\n" +
	"\x0eHandleProxyLog\x12\x17.plugin.ProxyLogRequest\x1a\x1e.plugin.DataCollectionResponse\x12K\n" +
	"\x0fHandleAnalytics\x12\x18.plugin.AnalyticsRequest\x1a\x1e.plugin.DataCollectionResponse\x12O\n" +
	"\x11HandleBudgetUsage\x12\x1a.plugin.BudgetUsageRequest\x1a\x1e.plugin.DataCollectionResponse\x12=\n" +
	"\bGetAsset\x12\x17.plugin.GetAssetRequest\x1a\x18.plugin.GetAssetResponse\x12C\n" +
	"\n" +
	"ListAssets\x12\x19.plugin.ListAssetsRequest\x1a\x1a.plugin.ListAssetsResponse\x12F\n" +
	"\vGetManifest\x12\x1a.plugin.GetManifestRequest\x1a\x1b.plugin.GetManifestResponse\x121\n" +
	"\x04Call\x12\x13.plugin.CallRequest\x1a\x14.plugin.CallResponse\x12R\n" +
	"\x0fGetConfigSchema\x12\x1e.plugin.GetConfigSchemaRequest\x1a\x1f.plugin.GetConfigSchemaResponseB/Z-github.com/TykTechnologies/midsommar/v2/protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 51)
var file_plugin_proto_goTypes = []any{
	(*InitRequest)(nil),             // 0: plugin.InitRequest
	(*InitResponse)(nil),            // 1: plugin.InitResponse
	(*PingRequest)(nil),             // 2: plugin.PingRequest
	(*PingResponse)(nil),            // 3: plugin.PingResponse
	(*ShutdownRequest)(nil),         // 4: plugin.ShutdownRequest
	(*ShutdownResponse)(nil),        // 5: plugin.ShutdownResponse
	(*PluginContext)(nil),           // 6: plugin.PluginContext
	(*PluginRequest)(nil),           // 7: plugin.PluginRequest
	(*PluginResponse)(nil),          // 8: plugin.PluginResponse
	(*AuthRequest)(nil),             // 9: plugin.AuthRequest
	(*AuthResponse)(nil),            // 10: plugin.AuthResponse
	(*EnrichedRequest)(nil),         // 11: plugin.EnrichedRequest
	(*HeadersRequest)(nil),          // 12: plugin.HeadersRequest
	(*HeadersResponse)(nil),         // 13: plugin.HeadersResponse
	(*ResponseWriteRequest)(nil),    // 14: plugin.ResponseWriteRequest
	(*ResponseWriteResponse)(nil),   // 15: plugin.ResponseWriteResponse
	(*GetAppRequest)(nil),           // 16: plugin.GetAppRequest
	(*GetAppResponse)(nil),          // 17: plugin.GetAppResponse
	(*GetUserRequest)(nil),          // 18: plugin.GetUserRequest
	(*GetUserResponse)(nil),         // 19: plugin.GetUserResponse
	(*App)(nil),                     // 20: plugin.App
	(*User)(nil),                    // 21: plugin.User
	(*ProxyLogRequest)(nil),         // 22: plugin.ProxyLogRequest
	(*AnalyticsRequest)(nil),        // 23: plugin.AnalyticsRequest
	(*BudgetUsageRequest)(nil),      // 24: plugin.BudgetUsageRequest
	(*DataCollectionResponse)(nil),  // 25: plugin.DataCollectionResponse
	(*GetAssetRequest)(nil),         // 26: plugin.GetAssetRequest
	(*GetAssetResponse)(nil),        // 27: plugin.GetAssetResponse
	(*ListAssetsRequest)(nil),       // 28: plugin.ListAssetsRequest
	(*ListAssetsResponse)(nil),      // 29: plugin.ListAssetsResponse
	(*AssetInfo)(nil),               // 30: plugin.AssetInfo
	(*GetManifestRequest)(nil),      // 31: plugin.GetManifestRequest
	(*GetManifestResponse)(nil),     // 32: plugin.GetManifestResponse
	(*CallRequest)(nil),             // 33: plugin.CallRequest
	(*CallResponse)(nil),            // 34: plugin.CallResponse
	(*GetConfigSchemaRequest)(nil),  // 35: plugin.GetConfigSchemaRequest
	(*GetConfigSchemaResponse)(nil), // 36: plugin.GetConfigSchemaResponse
	nil,                             // 37: plugin.InitRequest.ConfigEntry
	nil,                             // 38: plugin.PluginContext.MetadataEntry
	nil,                             // 39: plugin.PluginContext.TraceContextEntry
	nil,                             // 40: plugin.PluginRequest.HeadersEntry
	nil,                             // 41: plugin.PluginResponse.HeadersEntry
	nil,                             // 42: plugin.AuthResponse.ClaimsEntry
	nil,                             // 43: plugin.EnrichedRequest.AuthClaimsEntry
	nil,                             // 44: plugin.HeadersRequest.HeadersEntry
	nil,                             // 45: plugin.HeadersResponse.HeadersEntry
	nil,                             // 46: plugin.ResponseWriteRequest.HeadersEntry
	nil,                             // 47: plugin.ResponseWriteResponse.HeadersEntry
	nil,                             // 48: plugin.App.MetadataEntry
	nil,                             // 49: plugin.User.MetadataEntry
	nil,                             // 50: plugin.DataCollectionResponse.MetadataEntry
}
var file_plugin_proto_depIdxs = []int32{
	37, // 0: plugin.InitRequest.config:type_name -> plugin.InitRequest.ConfigEntry
	38, // 1: plugin.PluginContext.metadata:type_name -> plugin.PluginContext.MetadataEntry
	39, // 2: plugin.PluginContext.trace_context:type_name -> plugin.PluginContext.TraceContextEntry
	40, // 3: plugin.PluginRequest.headers:type_name -> plugin.PluginRequest.HeadersEntry
	6,  // 4: plugin.PluginRequest.context:type_name -> plugin.PluginContext
	41, // 5: plugin.PluginResponse.headers:type_name -> plugin.PluginResponse.HeadersEntry
	7,  // 6: plugin.AuthRequest.request:type_name -> plugin.PluginRequest
	6,  // 7: plugin.AuthRequest.context:type_name -> plugin.PluginContext
	42, // 8: plugin.AuthResponse.claims:type_name -> plugin.AuthResponse.ClaimsEntry
	7,  // 9: plugin.EnrichedRequest.request:type_name -> plugin.PluginRequest
	43, // 10: plugin.EnrichedRequest.auth_claims:type_name -> plugin.EnrichedRequest.AuthClaimsEntry
	44, // 11: plugin.HeadersRequest.headers:type_name -> plugin.HeadersRequest.HeadersEntry
	6,  // 12: plugin.HeadersRequest.context:type_name -> plugin.PluginContext
	45, // 13: plugin.HeadersResponse.headers:type_name -> plugin.HeadersResponse.HeadersEntry
	46, // 14: plugin.ResponseWriteRequest.headers:type_name -> plugin.ResponseWriteRequest.HeadersEntry
	6,  // 15: plugin.ResponseWriteRequest.context:type_name -> plugin.PluginContext
	47, // 16: plugin.ResponseWriteResponse.headers:type_name -> plugin.ResponseWriteResponse.HeadersEntry
	6,  // 17: plugin.GetAppRequest.context:type_name -> plugin.PluginContext
	20, // 18: plugin.GetAppResponse.app:type_name -> plugin.App
	6,  // 19: plugin.GetUserRequest.context:type_name -> plugin.PluginContext
	21, // 20: plugin.GetUserResponse.user:type_name -> plugin.User
	48, // 21: plugin.App.metadata:type_name -> plugin.App.MetadataEntry
	49, // 22: plugin.User.metadata:type_name -> plugin.User.MetadataEntry
	6,  // 23: plugin.ProxyLogRequest.context:type_name -> plugin.PluginContext
	6,  // 24: plugin.AnalyticsRequest.context:type_name -> plugin.PluginContext
	6,  // 25: plugin.BudgetUsageRequest.context:type_name -> plugin.PluginContext
	50, // 26: plugin.DataCollectionResponse.metadata:type_name -> plugin.DataCollectionResponse.MetadataEntry
	30, // 27: plugin.ListAssetsResponse.assets:type_name -> plugin.AssetInfo
	0,  // 28: plugin.PluginService.Initialize:input_type -> plugin.InitRequest
	2,  // 29: plugin.PluginService.Ping:input_type -> plugin.PingRequest
	4,  // 30: plugin.PluginService.Shutdown:input_type -> plugin.ShutdownRequest
	7,  // 31: plugin.PluginService.ProcessPreAuth:input_type -> plugin.PluginRequest
	9,  // 32: plugin.PluginService.Authenticate:input_type -> plugin.AuthRequest
	16, // 33: plugin.PluginService.GetAppByCredential:input_type -> plugin.GetAppRequest
	18, // 34: plugin.PluginService.GetUserByCredential:input_type -> plugin.GetUserRequest
	11, // 35: plugin.PluginService.ProcessPostAuth:input_type -> plugin.EnrichedRequest
	12, // 36: plugin.PluginService.OnBeforeWriteHeaders:input_type -> plugin.HeadersRequest
	14, // 37: plugin.PluginService.OnBeforeWrite:input_type -> plugin.ResponseWriteRequest
	22, // 38: plugin.PluginService.HandleProxyLog:input_type -> plugin.ProxyLogRequest
	23, // 39: plugin.PluginService.HandleAnalytics:input_type -> plugin.AnalyticsRequest
	24, // 40: plugin.PluginService.HandleBudgetUsage:input_type -> plugin.BudgetUsageRequest
	26, // 41: plugin.PluginService.GetAsset:input_type -> plugin.GetAssetRequest
	28, // 42: plugin.PluginService.ListAssets:input_type -> plugin.ListAssetsRequest
	31, // 43: plugin.PluginService.GetManifest:input_type -> plugin.GetManifestRequest
	33, // 44: plugin.PluginService.Call:input_type -> plugin.CallRequest
	35, // 45: plugin.PluginService.GetConfigSchema:input_type -> plugin.GetConfigSchemaRequest
	1,  // 46: plugin.PluginService.Initialize:output_type -> plugin.InitResponse
	3,  // 47: plugin.PluginService.Ping:output_type -> plugin.PingResponse
	5,  // 48: plugin.PluginService.Shutdown:output_type -> plugin.ShutdownResponse
	8,  // 49: plugin.PluginService.ProcessPreAuth:output_type -> plugin.PluginResponse
	10, // 50: plugin.PluginService.Authenticate:output_type -> plugin.AuthResponse
	17, // 51: plugin.PluginService.GetAppByCredential:output_type -> plugin.GetAppResponse
	19, // 52: plugin.PluginService.GetUserByCredential:output_type -> plugin.GetUserResponse
	8,  // 53: plugin.PluginService.ProcessPostAuth:output_type -> plugin.PluginResponse
	13, // 54: plugin.PluginService.OnBeforeWriteHeaders:output_type -> plugin.HeadersResponse
	15, // 55: plugin.PluginService.OnBeforeWrite:output_type -> plugin.ResponseWriteResponse
	25, // 56: plugin.PluginService.HandleProxyLog:output_type -> plugin.DataCollectionResponse
	25, // 57: plugin.PluginService.HandleAnalytics:output_type -> plugin.DataCollectionResponse
	25, // 58: plugin.PluginService.HandleBudgetUsage:output_type -> plugin.DataCollectionResponse
	27, // 59: plugin.PluginService.GetAsset:output_type -> plugin.GetAssetResponse
	29, // 60: plugin.PluginService.ListAssets:output_type -> plugin.ListAssetsResponse
	32, // 61: plugin.PluginService.GetManifest:output_type -> plugin.GetManifestResponse
	34, // 62: plugin.PluginService.Call:output_type -> plugin.CallResponse
	36, // 63: plugin.PluginService.GetConfigSchema:output_type -> plugin.GetConfigSchemaResponse
	46, // [46:64] is the sub-list for method output_type
	28, // [28:46] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   51,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
