// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: proto/config_sync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EdgeRegistrationRequest is sent when an edge instance connects
type EdgeRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`                                                                 // Unique identifier for this edge instance
	EdgeNamespace string                 `protobuf:"bytes,2,opt,name=edge_namespace,json=edgeNamespace,proto3" json:"edge_namespace,omitempty"`                                            // Namespace this edge serves (empty = global only)
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                                                             // Microgateway version
	BuildHash     string                 `protobuf:"bytes,4,opt,name=build_hash,json=buildHash,proto3" json:"build_hash,omitempty"`                                                        // Build hash for version checking
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional edge metadata (region, environment, etc.)
	Health        *HealthStatus          `protobuf:"bytes,6,opt,name=health,proto3" json:"health,omitempty"`                                                                               // Initial health status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeRegistrationRequest) Reset() {
	*x = EdgeRegistrationRequest{}
	mi := &file_proto_config_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeRegistrationRequest) ProtoMessage() {}

func (x *EdgeRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeRegistrationRequest.ProtoReflect.Descriptor instead.
func (*EdgeRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{0}
}

func (x *EdgeRegistrationRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *EdgeRegistrationRequest) GetEdgeNamespace() string {
	if x != nil {
		return x.EdgeNamespace
	}
	return ""
}

func (x *EdgeRegistrationRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EdgeRegistrationRequest) GetBuildHash() string {
	if x != nil {
		return x.BuildHash
	}
	return ""
}

func (x *EdgeRegistrationRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EdgeRegistrationRequest) GetHealth() *HealthStatus {
	if x != nil {
		return x.Health
	}
	return nil
}

// EdgeRegistrationResponse is returned after successful registration
type EdgeRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`             // Session ID for this connection
	InitialConfig *ConfigurationSnapshot `protobuf:"bytes,4,opt,name=initial_config,json=initialConfig,proto3" json:"initial_config,omitempty"` // Initial configuration snapshot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeRegistrationResponse) Reset() {
	*x = EdgeRegistrationResponse{}
	mi := &file_proto_config_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeRegistrationResponse) ProtoMessage() {}

func (x *EdgeRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeRegistrationResponse.ProtoReflect.Descriptor instead.
func (*EdgeRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{1}
}

func (x *EdgeRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EdgeRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EdgeRegistrationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EdgeRegistrationResponse) GetInitialConfig() *ConfigurationSnapshot {
	if x != nil {
		return x.InitialConfig
	}
	return nil
}

// ConfigurationRequest requests configuration for a specific namespace
type ConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeNamespace string                 `protobuf:"bytes,1,opt,name=edge_namespace,json=edgeNamespace,proto3" json:"edge_namespace,omitempty"` // Namespace to filter for (empty = global only)
	LastSyncTime  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`  // Optional: only get changes since this time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationRequest) Reset() {
	*x = ConfigurationRequest{}
	mi := &file_proto_config_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationRequest) ProtoMessage() {}

func (x *ConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationRequest.ProtoReflect.Descriptor instead.
func (*ConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigurationRequest) GetEdgeNamespace() string {
	if x != nil {
		return x.EdgeNamespace
	}
	return ""
}

func (x *ConfigurationRequest) GetLastSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncTime
	}
	return nil
}

// EdgeMessage is sent from edge to control
type EdgeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*EdgeMessage_Registration
	//	*EdgeMessage_Heartbeat
	//	*EdgeMessage_ConfigRequest
	//	*EdgeMessage_Unregistration
	Message       isEdgeMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeMessage) Reset() {
	*x = EdgeMessage{}
	mi := &file_proto_config_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeMessage) ProtoMessage() {}

func (x *EdgeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeMessage.ProtoReflect.Descriptor instead.
func (*EdgeMessage) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{3}
}

func (x *EdgeMessage) GetMessage() isEdgeMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *EdgeMessage) GetRegistration() *EdgeRegistrationRequest {
	if x != nil {
		if x, ok := x.Message.(*EdgeMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *EdgeMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Message.(*EdgeMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *EdgeMessage) GetConfigRequest() *ConfigurationRequest {
	if x != nil {
		if x, ok := x.Message.(*EdgeMessage_ConfigRequest); ok {
			return x.ConfigRequest
		}
	}
	return nil
}

func (x *EdgeMessage) GetUnregistration() *EdgeUnregistrationRequest {
	if x != nil {
		if x, ok := x.Message.(*EdgeMessage_Unregistration); ok {
			return x.Unregistration
		}
	}
	return nil
}

type isEdgeMessage_Message interface {
	isEdgeMessage_Message()
}

type EdgeMessage_Registration struct {
	Registration *EdgeRegistrationRequest `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type EdgeMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type EdgeMessage_ConfigRequest struct {
	ConfigRequest *ConfigurationRequest `protobuf:"bytes,3,opt,name=config_request,json=configRequest,proto3,oneof"`
}

type EdgeMessage_Unregistration struct {
	Unregistration *EdgeUnregistrationRequest `protobuf:"bytes,4,opt,name=unregistration,proto3,oneof"`
}

func (*EdgeMessage_Registration) isEdgeMessage_Message() {}

func (*EdgeMessage_Heartbeat) isEdgeMessage_Message() {}

func (*EdgeMessage_ConfigRequest) isEdgeMessage_Message() {}

func (*EdgeMessage_Unregistration) isEdgeMessage_Message() {}

// ControlMessage is sent from control to edge
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ControlMessage_RegistrationResponse
	//	*ControlMessage_Configuration
	//	*ControlMessage_Change
	//	*ControlMessage_HeartbeatResponse
	//	*ControlMessage_Error
	Message       isControlMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_proto_config_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{4}
}

func (x *ControlMessage) GetMessage() isControlMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ControlMessage) GetRegistrationResponse() *EdgeRegistrationResponse {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_RegistrationResponse); ok {
			return x.RegistrationResponse
		}
	}
	return nil
}

func (x *ControlMessage) GetConfiguration() *ConfigurationSnapshot {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_Configuration); ok {
			return x.Configuration
		}
	}
	return nil
}

func (x *ControlMessage) GetChange() *ConfigurationChange {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_Change); ok {
			return x.Change
		}
	}
	return nil
}

func (x *ControlMessage) GetHeartbeatResponse() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_HeartbeatResponse); ok {
			return x.HeartbeatResponse
		}
	}
	return nil
}

func (x *ControlMessage) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isControlMessage_Message interface {
	isControlMessage_Message()
}

type ControlMessage_RegistrationResponse struct {
	RegistrationResponse *EdgeRegistrationResponse `protobuf:"bytes,1,opt,name=registration_response,json=registrationResponse,proto3,oneof"`
}

type ControlMessage_Configuration struct {
	Configuration *ConfigurationSnapshot `protobuf:"bytes,2,opt,name=configuration,proto3,oneof"`
}

type ControlMessage_Change struct {
	Change *ConfigurationChange `protobuf:"bytes,3,opt,name=change,proto3,oneof"`
}

type ControlMessage_HeartbeatResponse struct {
	HeartbeatResponse *HeartbeatResponse `protobuf:"bytes,4,opt,name=heartbeat_response,json=heartbeatResponse,proto3,oneof"`
}

type ControlMessage_Error struct {
	Error *ErrorMessage `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*ControlMessage_RegistrationResponse) isControlMessage_Message() {}

func (*ControlMessage_Configuration) isControlMessage_Message() {}

func (*ControlMessage_Change) isControlMessage_Message() {}

func (*ControlMessage_HeartbeatResponse) isControlMessage_Message() {}

func (*ControlMessage_Error) isControlMessage_Message() {}

// HeartbeatRequest contains health and status information from edge
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Health        *HealthStatus          `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	Metrics       *EdgeMetrics           `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_config_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetHealth() *HealthStatus {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *HeartbeatRequest) GetMetrics() *EdgeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// HeartbeatResponse acknowledges heartbeat and may contain control directives
type HeartbeatResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Message      string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Control directives (if any)
	RequestFullSync   bool `protobuf:"varint,3,opt,name=request_full_sync,json=requestFullSync,proto3" json:"request_full_sync,omitempty"`     // Request edge to perform full configuration sync
	ShutdownRequested bool `protobuf:"varint,4,opt,name=shutdown_requested,json=shutdownRequested,proto3" json:"shutdown_requested,omitempty"` // Request graceful shutdown
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_config_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HeartbeatResponse) GetRequestFullSync() bool {
	if x != nil {
		return x.RequestFullSync
	}
	return false
}

func (x *HeartbeatResponse) GetShutdownRequested() bool {
	if x != nil {
		return x.ShutdownRequested
	}
	return false
}

// EdgeUnregistrationRequest is sent when edge is shutting down
type EdgeUnregistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // Shutdown reason
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeUnregistrationRequest) Reset() {
	*x = EdgeUnregistrationRequest{}
	mi := &file_proto_config_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeUnregistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeUnregistrationRequest) ProtoMessage() {}

func (x *EdgeUnregistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeUnregistrationRequest.ProtoReflect.Descriptor instead.
func (*EdgeUnregistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{7}
}

func (x *EdgeUnregistrationRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *EdgeUnregistrationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EdgeUnregistrationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// EdgeMetrics contains operational metrics from edge instance
type EdgeMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestsProcessed uint64                 `protobuf:"varint,1,opt,name=requests_processed,json=requestsProcessed,proto3" json:"requests_processed,omitempty"`                                                                // Total requests processed
	ActiveConnections uint64                 `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`                                                                // Current active connections
	CpuUsagePercent   float64                `protobuf:"fixed64,3,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`                                                                   // CPU usage percentage
	MemoryUsageBytes  uint64                 `protobuf:"varint,4,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`                                                                 // Memory usage in bytes
	UptimeSeconds     uint64                 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`                                                                            // Uptime in seconds
	CustomMetrics     map[string]float64     `protobuf:"bytes,6,rep,name=custom_metrics,json=customMetrics,proto3" json:"custom_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // Custom metrics
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EdgeMetrics) Reset() {
	*x = EdgeMetrics{}
	mi := &file_proto_config_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeMetrics) ProtoMessage() {}

func (x *EdgeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeMetrics.ProtoReflect.Descriptor instead.
func (*EdgeMetrics) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{8}
}

func (x *EdgeMetrics) GetRequestsProcessed() uint64 {
	if x != nil {
		return x.RequestsProcessed
	}
	return 0
}

func (x *EdgeMetrics) GetActiveConnections() uint64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *EdgeMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *EdgeMetrics) GetMemoryUsageBytes() uint64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *EdgeMetrics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *EdgeMetrics) GetCustomMetrics() map[string]float64 {
	if x != nil {
		return x.CustomMetrics
	}
	return nil
}

// ErrorMessage represents an error from control to edge
type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`       // Error code
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Human readable error message
	Fatal         bool                   `protobuf:"varint,3,opt,name=fatal,proto3" json:"fatal,omitempty"`    // Whether this error requires edge restart
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_proto_config_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorMessage) GetFatal() bool {
	if x != nil {
		return x.Fatal
	}
	return false
}

// Authentication and authorization messages
type AuthenticationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                 // Authentication token
	EdgeId        string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"` // Edge instance ID
	Challenge     string                 `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"`         // Optional challenge for enhanced security
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationRequest) Reset() {
	*x = AuthenticationRequest{}
	mi := &file_proto_config_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationRequest) ProtoMessage() {}

func (x *AuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{10}
}

func (x *AuthenticationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticationRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *AuthenticationRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

type AuthenticationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authenticated bool                   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // Session token for subsequent requests
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`         // Session expiration timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationResponse) Reset() {
	*x = AuthenticationResponse{}
	mi := &file_proto_config_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationResponse) ProtoMessage() {}

func (x *AuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{11}
}

func (x *AuthenticationResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *AuthenticationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthenticationResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AuthenticationResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// Token validation messages for on-demand validation (NEW)
type TokenValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                      // The API token to validate
	EdgeId        string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`                      // Edge ID making the request
	EdgeNamespace string                 `protobuf:"bytes,3,opt,name=edge_namespace,json=edgeNamespace,proto3" json:"edge_namespace,omitempty"` // Edge namespace for filtering
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValidationRequest) Reset() {
	*x = TokenValidationRequest{}
	mi := &file_proto_config_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValidationRequest) ProtoMessage() {}

func (x *TokenValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValidationRequest.ProtoReflect.Descriptor instead.
func (*TokenValidationRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{12}
}

func (x *TokenValidationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenValidationRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *TokenValidationRequest) GetEdgeNamespace() string {
	if x != nil {
		return x.EdgeNamespace
	}
	return ""
}

type TokenValidationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`                                  // Whether token is valid
	AppId         uint32                 `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                     // App ID if valid (0 if invalid)
	AppName       string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`                // App name for logging
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`                                 // Token scopes if valid
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if invalid
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`          // Token expiration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValidationResponse) Reset() {
	*x = TokenValidationResponse{}
	mi := &file_proto_config_sync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValidationResponse) ProtoMessage() {}

func (x *TokenValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_sync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValidationResponse.ProtoReflect.Descriptor instead.
func (*TokenValidationResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_sync_proto_rawDescGZIP(), []int{13}
}

func (x *TokenValidationResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *TokenValidationResponse) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *TokenValidationResponse) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *TokenValidationResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *TokenValidationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TokenValidationResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_proto_config_sync_proto protoreflect.FileDescriptor

const file_proto_config_sync_proto_rawDesc = "" +
	"\n" +
	"\x17proto/config_sync.proto\x12\fmicrogateway\x1a\x12proto/common.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x02\n" +
	"\x17EdgeRegistrationRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12%\n" +
	"\x0eedge_namespace\x18\x02 \x01(\tR\redgeNamespace\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"build_hash\x18\x04 \x01(\tR\tbuildHash\x12O\n" +
	"\bmetadata\x18\x05 \x03(\v23.microgateway.EdgeRegistrationRequest.MetadataEntryR\bmetadata\x122\n" +
	"\x06health\x18\x06 \x01(\v2\x1a.microgateway.HealthStatusR\x06health\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\x18EdgeRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12J\n" +
	"\x0einitial_config\x18\x04 \x01(\v2#.microgateway.ConfigurationSnapshotR\rinitialConfig\"\x7f\n" +
	"\x14ConfigurationRequest\x12%\n" +
	"\x0eedge_namespace\x18\x01 \x01(\tR\redgeNamespace\x12@\n" +
	"\x0elast_sync_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncTime\"\xc5\x02\n" +
	"\vEdgeMessage\x12K\n" +
	"\fregistration\x18\x01 \x01(\v2%.microgateway.EdgeRegistrationRequestH\x00R\fregistration\x12>\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1e.microgateway.HeartbeatRequestH\x00R\theartbeat\x12K\n" +
	"\x0econfig_request\x18\x03 \x01(\v2\".microgateway.ConfigurationRequestH\x00R\rconfigRequest\x12Q\n" +
	"\x0eunregistration\x18\x04 \x01(\v2'.microgateway.EdgeUnregistrationRequestH\x00R\x0eunregistrationB\t\n" +
	"\amessage\"\x8a\x03\n" +
	"\x0eControlMessage\x12]\n" +
	"\x15registration_response\x18\x01 \x01(\v2&.microgateway.EdgeRegistrationResponseH\x00R\x14registrationResponse\x12K\n" +
	"\rconfiguration\x18\x02 \x01(\v2#.microgateway.ConfigurationSnapshotH\x00R\rconfiguration\x12;\n" +
	"\x06change\x18\x03 \x01(\v2!.microgateway.ConfigurationChangeH\x00R\x06change\x12P\n" +
	"\x12heartbeat_response\x18\x04 \x01(\v2\x1f.microgateway.HeartbeatResponseH\x00R\x11heartbeatResponse\x122\n" +
	"\x05error\x18\x05 \x01(\v2\x1a.microgateway.ErrorMessageH\x00R\x05errorB\t\n" +
	"\amessage\"\xed\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x122\n" +
	"\x06health\x18\x03 \x01(\v2\x1a.microgateway.HealthStatusR\x06health\x123\n" +
	"\ametrics\x18\x04 \x01(\v2\x19.microgateway.EdgeMetricsR\ametrics\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xac\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x11request_full_sync\x18\x03 \x01(\bR\x0frequestFullSync\x12-\n" +
	"\x12shutdown_requested\x18\x04 \x01(\bR\x11shutdownRequested\"k\n" +
	"\x19EdgeUnregistrationRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x83\x03\n" +
	"\vEdgeMetrics\x12-\n" +
	"\x12requests_processed\x18\x01 \x01(\x04R\x11requestsProcessed\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x04R\x11activeConnections\x12*\n" +
	"\x11cpu_usage_percent\x18\x03 \x01(\x01R\x0fcpuUsagePercent\x12,\n" +
	"\x12memory_usage_bytes\x18\x04 \x01(\x04R\x10memoryUsageBytes\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x04R\ruptimeSeconds\x12S\n" +
	"\x0ecustom_metrics\x18\x06 \x03(\v2,.microgateway.EdgeMetrics.CustomMetricsEntryR\rcustomMetrics\x1a@\n" +
	"\x12CustomMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"R\n" +
	"\fErrorMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05fatal\x18\x03 \x01(\bR\x05fatal\"d\n" +
	"\x15AuthenticationRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12\x1c\n" +
	"\tchallenge\x18\x03 \x01(\tR\tchallenge\"\x9c\x01\n" +
	"\x16AuthenticationResponse\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"n\n" +
	"\x16TokenValidationRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12%\n" +
	"\x0eedge_namespace\x18\x03 \x01(\tR\redgeNamespace\"\xd9\x01\n" +
	"\x17TokenValidationResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\rR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt2\xb0\x04\n" +
	"\x18ConfigurationSyncService\x12]\n" +
	"\fRegisterEdge\x12%.microgateway.EdgeRegistrationRequest\x1a&.microgateway.EdgeRegistrationResponse\x12_\n" +
	"\x14GetFullConfiguration\x12\".microgateway.ConfigurationRequest\x1a#.microgateway.ConfigurationSnapshot\x12Q\n" +
	"\x12SubscribeToChanges\x12\x19.microgateway.EdgeMessage\x1a\x1c.microgateway.ControlMessage(\x010\x01\x12P\n" +
	"\rSendHeartbeat\x12\x1e.microgateway.HeartbeatRequest\x1a\x1f.microgateway.HeartbeatResponse\x12Q\n" +
	"\x0eUnregisterEdge\x12'.microgateway.EdgeUnregistrationRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\rValidateToken\x12$.microgateway.TokenValidationRequest\x1a%.microgateway.TokenValidationResponseB9Z7github.com/TykTechnologies/midsommar/microgateway/protob\x06proto3"

var (
	file_proto_config_sync_proto_rawDescOnce sync.Once
	file_proto_config_sync_proto_rawDescData []byte
)

func file_proto_config_sync_proto_rawDescGZIP() []byte {
	file_proto_config_sync_proto_rawDescOnce.Do(func() {
		file_proto_config_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_sync_proto_rawDesc), len(file_proto_config_sync_proto_rawDesc)))
	})
	return file_proto_config_sync_proto_rawDescData
}

var file_proto_config_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_config_sync_proto_goTypes = []any{
	(*EdgeRegistrationRequest)(nil),   // 0: microgateway.EdgeRegistrationRequest
	(*EdgeRegistrationResponse)(nil),  // 1: microgateway.EdgeRegistrationResponse
	(*ConfigurationRequest)(nil),      // 2: microgateway.ConfigurationRequest
	(*EdgeMessage)(nil),               // 3: microgateway.EdgeMessage
	(*ControlMessage)(nil),            // 4: microgateway.ControlMessage
	(*HeartbeatRequest)(nil),          // 5: microgateway.HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 6: microgateway.HeartbeatResponse
	(*EdgeUnregistrationRequest)(nil), // 7: microgateway.EdgeUnregistrationRequest
	(*EdgeMetrics)(nil),               // 8: microgateway.EdgeMetrics
	(*ErrorMessage)(nil),              // 9: microgateway.ErrorMessage
	(*AuthenticationRequest)(nil),     // 10: microgateway.AuthenticationRequest
	(*AuthenticationResponse)(nil),    // 11: microgateway.AuthenticationResponse
	(*TokenValidationRequest)(nil),    // 12: microgateway.TokenValidationRequest
	(*TokenValidationResponse)(nil),   // 13: microgateway.TokenValidationResponse
	nil,                               // 14: microgateway.EdgeRegistrationRequest.MetadataEntry
	nil,                               // 15: microgateway.EdgeMetrics.CustomMetricsEntry
	(*HealthStatus)(nil),              // 16: microgateway.HealthStatus
	(*ConfigurationSnapshot)(nil),     // 17: microgateway.ConfigurationSnapshot
	(*timestamppb.Timestamp)(nil),     // 18: google.protobuf.Timestamp
	(*ConfigurationChange)(nil),       // 19: microgateway.ConfigurationChange
	(*emptypb.Empty)(nil),             // 20: google.protobuf.Empty
}
var file_proto_config_sync_proto_depIdxs = []int32{
	14, // 0: microgateway.EdgeRegistrationRequest.metadata:type_name -> microgateway.EdgeRegistrationRequest.MetadataEntry
	16, // 1: microgateway.EdgeRegistrationRequest.health:type_name -> microgateway.HealthStatus
	17, // 2: microgateway.EdgeRegistrationResponse.initial_config:type_name -> microgateway.ConfigurationSnapshot
	18, // 3: microgateway.ConfigurationRequest.last_sync_time:type_name -> google.protobuf.Timestamp
	0,  // 4: microgateway.EdgeMessage.registration:type_name -> microgateway.EdgeRegistrationRequest
	5,  // 5: microgateway.EdgeMessage.heartbeat:type_name -> microgateway.HeartbeatRequest
	2,  // 6: microgateway.EdgeMessage.config_request:type_name -> microgateway.ConfigurationRequest
	7,  // 7: microgateway.EdgeMessage.unregistration:type_name -> microgateway.EdgeUnregistrationRequest
	1,  // 8: microgateway.ControlMessage.registration_response:type_name -> microgateway.EdgeRegistrationResponse
	17, // 9: microgateway.ControlMessage.configuration:type_name -> microgateway.ConfigurationSnapshot
	19, // 10: microgateway.ControlMessage.change:type_name -> microgateway.ConfigurationChange
	6,  // 11: microgateway.ControlMessage.heartbeat_response:type_name -> microgateway.HeartbeatResponse
	9,  // 12: microgateway.ControlMessage.error:type_name -> microgateway.ErrorMessage
	16, // 13: microgateway.HeartbeatRequest.health:type_name -> microgateway.HealthStatus
	8,  // 14: microgateway.HeartbeatRequest.metrics:type_name -> microgateway.EdgeMetrics
	18, // 15: microgateway.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	15, // 16: microgateway.EdgeMetrics.custom_metrics:type_name -> microgateway.EdgeMetrics.CustomMetricsEntry
	18, // 17: microgateway.TokenValidationResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 18: microgateway.ConfigurationSyncService.RegisterEdge:input_type -> microgateway.EdgeRegistrationRequest
	2,  // 19: microgateway.ConfigurationSyncService.GetFullConfiguration:input_type -> microgateway.ConfigurationRequest
	3,  // 20: microgateway.ConfigurationSyncService.SubscribeToChanges:input_type -> microgateway.EdgeMessage
	5,  // 21: microgateway.ConfigurationSyncService.SendHeartbeat:input_type -> microgateway.HeartbeatRequest
	7,  // 22: microgateway.ConfigurationSyncService.UnregisterEdge:input_type -> microgateway.EdgeUnregistrationRequest
	12, // 23: microgateway.ConfigurationSyncService.ValidateToken:input_type -> microgateway.TokenValidationRequest
	1,  // 24: microgateway.ConfigurationSyncService.RegisterEdge:output_type -> microgateway.EdgeRegistrationResponse
	17, // 25: microgateway.ConfigurationSyncService.GetFullConfiguration:output_type -> microgateway.ConfigurationSnapshot
	4,  // 26: microgateway.ConfigurationSyncService.SubscribeToChanges:output_type -> microgateway.ControlMessage
	6,  // 27: microgateway.ConfigurationSyncService.SendHeartbeat:output_type -> microgateway.HeartbeatResponse
	20, // 28: microgateway.ConfigurationSyncService.UnregisterEdge:output_type -> google.protobuf.Empty
	13, // 29: microgateway.ConfigurationSyncService.ValidateToken:output_type -> microgateway.TokenValidationResponse
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_config_sync_proto_init() }
func file_proto_config_sync_proto_init() {
	if File_proto_config_sync_proto != nil {
		return
	}
	file_proto_common_proto_init()
	file_proto_config_sync_proto_msgTypes[3].OneofWrappers = []any{
		(*EdgeMessage_Registration)(nil),
		(*EdgeMessage_Heartbeat)(nil),
		(*EdgeMessage_ConfigRequest)(nil),
		(*EdgeMessage_Unregistration)(nil),
	}
	file_proto_config_sync_proto_msgTypes[4].OneofWrappers = []any{
		(*ControlMessage_RegistrationResponse)(nil),
		(*ControlMessage_Configuration)(nil),
		(*ControlMessage_Change)(nil),
		(*ControlMessage_HeartbeatResponse)(nil),
		(*ControlMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_sync_proto_rawDesc), len(file_proto_config_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_sync_proto_goTypes,
		DependencyIndexes: file_proto_config_sync_proto_depIdxs,
		MessageInfos:      file_proto_config_sync_proto_msgTypes,
	}.Build()
	File_proto_config_sync_proto = out.File
	file_proto_config_sync_proto_goTypes = nil
	file_proto_config_sync_proto_depIdxs = nil
}
