// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: proto/config_provider.proto

package configpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration schema messages
type ConfigSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchemaRequest) Reset() {
	*x = ConfigSchemaRequest{}
	mi := &file_proto_config_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchemaRequest) ProtoMessage() {}

func (x *ConfigSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchemaRequest.ProtoReflect.Descriptor instead.
func (*ConfigSchemaRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_provider_proto_rawDescGZIP(), []int{0}
}

type ConfigSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SchemaJson    string                 `protobuf:"bytes,2,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"` // JSON Schema as string (jsonschema.org format)
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchemaResponse) Reset() {
	*x = ConfigSchemaResponse{}
	mi := &file_proto_config_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchemaResponse) ProtoMessage() {}

func (x *ConfigSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchemaResponse.ProtoReflect.Descriptor instead.
func (*ConfigSchemaResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigSchemaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigSchemaResponse) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

func (x *ConfigSchemaResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Health check messages
type ConfigPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPingRequest) Reset() {
	*x = ConfigPingRequest{}
	mi := &file_proto_config_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPingRequest) ProtoMessage() {}

func (x *ConfigPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPingRequest.ProtoReflect.Descriptor instead.
func (*ConfigPingRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigPingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ConfigPingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPingResponse) Reset() {
	*x = ConfigPingResponse{}
	mi := &file_proto_config_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPingResponse) ProtoMessage() {}

func (x *ConfigPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPingResponse.ProtoReflect.Descriptor instead.
func (*ConfigPingResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigPingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConfigPingResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

// Manifest messages (reusing same structure as main plugin service)
type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_proto_config_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_provider_proto_rawDescGZIP(), []int{4}
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ManifestJson  string                 `protobuf:"bytes,2,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"` // Complete manifest as JSON string
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_proto_config_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_provider_proto_rawDescGZIP(), []int{5}
}

func (x *GetManifestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetManifestResponse) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

func (x *GetManifestResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_config_provider_proto protoreflect.FileDescriptor

const file_proto_config_provider_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/config_provider.proto\x12\x0fconfig_provider\"\x15\n" +
	"\x13ConfigSchemaRequest\"v\n" +
	"\x14ConfigSchemaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vschema_json\x18\x02 \x01(\tR\n" +
	"schemaJson\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"1\n" +
	"\x11ConfigPingRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"L\n" +
	"\x12ConfigPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\"\x14\n" +
	"\x12GetManifestRequest\"y\n" +
	"\x13GetManifestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rmanifest_json\x18\x02 \x01(\tR\fmanifestJson\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2\xa2\x02\n" +
	"\x15ConfigProviderService\x12^\n" +
	"\x0fGetConfigSchema\x12$.config_provider.ConfigSchemaRequest\x1a%.config_provider.ConfigSchemaResponse\x12X\n" +
	"\vGetManifest\x12#.config_provider.GetManifestRequest\x1a$.config_provider.GetManifestResponse\x12O\n" +
	"\x04Ping\x12\".config_provider.ConfigPingRequest\x1a#.config_provider.ConfigPingResponseB8Z6github.com/TykTechnologies/midsommar/v2/proto/configpbb\x06proto3"

var (
	file_proto_config_provider_proto_rawDescOnce sync.Once
	file_proto_config_provider_proto_rawDescData []byte
)

func file_proto_config_provider_proto_rawDescGZIP() []byte {
	file_proto_config_provider_proto_rawDescOnce.Do(func() {
		file_proto_config_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_provider_proto_rawDesc), len(file_proto_config_provider_proto_rawDesc)))
	})
	return file_proto_config_provider_proto_rawDescData
}

var file_proto_config_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_config_provider_proto_goTypes = []any{
	(*ConfigSchemaRequest)(nil),  // 0: config_provider.ConfigSchemaRequest
	(*ConfigSchemaResponse)(nil), // 1: config_provider.ConfigSchemaResponse
	(*ConfigPingRequest)(nil),    // 2: config_provider.ConfigPingRequest
	(*ConfigPingResponse)(nil),   // 3: config_provider.ConfigPingResponse
	(*GetManifestRequest)(nil),   // 4: config_provider.GetManifestRequest
	(*GetManifestResponse)(nil),  // 5: config_provider.GetManifestResponse
}
var file_proto_config_provider_proto_depIdxs = []int32{
	0, // 0: config_provider.ConfigProviderService.GetConfigSchema:input_type -> config_provider.ConfigSchemaRequest
	4, // 1: config_provider.ConfigProviderService.GetManifest:input_type -> config_provider.GetManifestRequest
	2, // 2: config_provider.ConfigProviderService.Ping:input_type -> config_provider.ConfigPingRequest
	1, // 3: config_provider.ConfigProviderService.GetConfigSchema:output_type -> config_provider.ConfigSchemaResponse
	5, // 4: config_provider.ConfigProviderService.GetManifest:output_type -> config_provider.GetManifestResponse
	3, // 5: config_provider.ConfigProviderService.Ping:output_type -> config_provider.ConfigPingResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_config_provider_proto_init() }
func file_proto_config_provider_proto_init() {
	if File_proto_config_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_provider_proto_rawDesc), len(file_proto_config_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_provider_proto_goTypes,
		DependencyIndexes: file_proto_config_provider_proto_depIdxs,
		MessageInfos:      file_proto_config_provider_proto_msgTypes,
	}.Build()
	File_proto_config_provider_proto = out.File
	file_proto_config_provider_proto_goTypes = nil
	file_proto_config_provider_proto_depIdxs = nil
}
