// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/config_provider.proto

package configpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigProviderService_GetConfigSchema_FullMethodName = "/config_provider.ConfigProviderService/GetConfigSchema"
	ConfigProviderService_Ping_FullMethodName            = "/config_provider.ConfigProviderService/Ping"
)

// ConfigProviderServiceClient is the client API for ConfigProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigProviderService defines a minimal gRPC interface for configuration schema extraction
// This service runs independently of the main plugin service and uses a universal handshake
// that works with any plugin type (microgateway or AI Studio)
type ConfigProviderServiceClient interface {
	// Get the JSON Schema for this plugin's configuration
	GetConfigSchema(ctx context.Context, in *ConfigSchemaRequest, opts ...grpc.CallOption) (*ConfigSchemaResponse, error)
	// Health check for the config service
	Ping(ctx context.Context, in *ConfigPingRequest, opts ...grpc.CallOption) (*ConfigPingResponse, error)
}

type configProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigProviderServiceClient(cc grpc.ClientConnInterface) ConfigProviderServiceClient {
	return &configProviderServiceClient{cc}
}

func (c *configProviderServiceClient) GetConfigSchema(ctx context.Context, in *ConfigSchemaRequest, opts ...grpc.CallOption) (*ConfigSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigSchemaResponse)
	err := c.cc.Invoke(ctx, ConfigProviderService_GetConfigSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configProviderServiceClient) Ping(ctx context.Context, in *ConfigPingRequest, opts ...grpc.CallOption) (*ConfigPingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigPingResponse)
	err := c.cc.Invoke(ctx, ConfigProviderService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigProviderServiceServer is the server API for ConfigProviderService service.
// All implementations must embed UnimplementedConfigProviderServiceServer
// for forward compatibility.
//
// ConfigProviderService defines a minimal gRPC interface for configuration schema extraction
// This service runs independently of the main plugin service and uses a universal handshake
// that works with any plugin type (microgateway or AI Studio)
type ConfigProviderServiceServer interface {
	// Get the JSON Schema for this plugin's configuration
	GetConfigSchema(context.Context, *ConfigSchemaRequest) (*ConfigSchemaResponse, error)
	// Health check for the config service
	Ping(context.Context, *ConfigPingRequest) (*ConfigPingResponse, error)
	mustEmbedUnimplementedConfigProviderServiceServer()
}

// UnimplementedConfigProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigProviderServiceServer struct{}

func (UnimplementedConfigProviderServiceServer) GetConfigSchema(context.Context, *ConfigSchemaRequest) (*ConfigSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigSchema not implemented")
}
func (UnimplementedConfigProviderServiceServer) Ping(context.Context, *ConfigPingRequest) (*ConfigPingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedConfigProviderServiceServer) mustEmbedUnimplementedConfigProviderServiceServer() {}
func (UnimplementedConfigProviderServiceServer) testEmbeddedByValue()                               {}

// UnsafeConfigProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigProviderServiceServer will
// result in compilation errors.
type UnsafeConfigProviderServiceServer interface {
	mustEmbedUnimplementedConfigProviderServiceServer()
}

func RegisterConfigProviderServiceServer(s grpc.ServiceRegistrar, srv ConfigProviderServiceServer) {
	// If the following call pancis, it indicates UnimplementedConfigProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigProviderService_ServiceDesc, srv)
}

func _ConfigProviderService_GetConfigSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigProviderServiceServer).GetConfigSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigProviderService_GetConfigSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigProviderServiceServer).GetConfigSchema(ctx, req.(*ConfigSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigProviderService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigProviderServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigProviderService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigProviderServiceServer).Ping(ctx, req.(*ConfigPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigProviderService_ServiceDesc is the grpc.ServiceDesc for ConfigProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "config_provider.ConfigProviderService",
	HandlerType: (*ConfigProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfigSchema",
			Handler:    _ConfigProviderService_GetConfigSchema_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _ConfigProviderService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/config_provider.proto",
}
