FROM debian:bookworm-slim@sha256:f06537653ac770703bc45b4b113475bd402f451e85223f0f2837acbf89ab020a as DEB
ARG TARGETARCH

ENV DEBIAN_FRONTEND=noninteractive

COPY *${TARGETARCH}.deb /
RUN rm -f /*fips*.deb && dpkg -i /tyk-microgateway*${TARGETARCH}.deb && rm /*.deb

FROM gcr.io/distroless/base-debian12:nonroot@sha256:8b9f2e503e55aff85b79d6b22c7a63a65170e8698ae80de680e3f5ea600977bf

COPY --from=DEB /opt/tyk-microgateway /opt/tyk-microgateway

EXPOSE 8080 9090

WORKDIR /opt/tyk-microgateway/

ENTRYPOINT ["/opt/tyk-microgateway/tyk-microgateway"]
