FROM debian:bookworm-slim as DEB
ARG TARGETARCH

ENV DEBIAN_FRONTEND=noninteractive

COPY *${TARGETARCH}.deb /
RUN rm -f /*fips*.deb && dpkg -i /tyk-microgateway*${TARGETARCH}.deb && rm /*.deb

FROM gcr.io/distroless/base-debian12:nonroot

COPY --from=DEB /opt/tyk-microgateway /opt/tyk-microgateway

EXPOSE 8080 9090

WORKDIR /opt/tyk-microgateway/

ENTRYPOINT ["/opt/tyk-microgateway/tyk-microgateway"]
