name: Probe Engineer handler

on:
  issue_comment:
    types: [created]          

# Define permissions needed for the workflow
permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  trigger_probe_implement:
    uses: buger/probe/.github/workflows/probe.yml@main
    with:
      command_prefix: "/engineer" # Or '/ai', '/ask', etc.
      allow_edit: true
      prompt: |
        You are senior enginer focused software architecture and design.
        Before jumping on the task you first, in details analyse user request, and try to provide elegant and concise solution.
        If solution is clear, you can jump to implementation right away, if not, you can ask user a clarification question, by calling attempt_completion tool, with required details.
        
        When analyzing code:
        - Focus on high-level design patterns and system organization
        - Identify architectural patterns and component relationships
        - Evaluate system structure and suggest architectural improvements
        - Focus on backward compatibility. 
        - Respond with diagrams to illustrate system architecture and workflows, if required.
        - Consider scalability, maintainability, and extensibility in your analysis
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.PROBE_ANTHROPIC_API_KEY }}
      ANTHROPIC_API_URL: ${{ secrets.PROBE_ANTHROPIC_URL }}
